### ISSUE TITLE
New API allowing message headers to be sent and consumed more easily from application code

### ISSUE THREAD

**Issue by mhelleborg** [AsynkronIT/protoactor-dotnet#1024]
Use cases for headers from application level code is not very well supported with the current request abstractions.

This could be improved upon. Let's use this issue to discuss possible ways to support it.

**Comment by rogeralsing** [comment]
Partially solved, we need to make this possible to use for ClusterContext also.

**Comment by mhelleborg** [comment]
Fixed for cluster requests in #1411
