### ISSUE TITLE
Dependency Injection: Internal Null Reference Exception when Spawning unregistered actor

### ISSUE THREAD

**Issue by kaep7n** [AsynkronIT/protoactor-dotnet#1030]
Hi, 

first of all great work! I playing around with your framework for home automation 🥇 

Yesterday I stumbled over a little bug.

## Expected Behavior

When using Dependency Injection and an Actor that should be spawned is not registered in the `ServiceProvider,` some kind of error should be thrown. Otherwise it is hard to see what the problem is.

## Actual Behavior

```   
//Get props for dependency injected actor 
var props = _actorSystem.DI().PropsFor<DependencyInjectedActor>();

//spawn the actor
var pid = _actorSystem.Root.Spawn(props);
``` 
does nothing, because a `NullReferenceException` is thrown and catched internally, the exception is only visible when activating the log

The exception happens in class `Proto.Context.ActorContext` in method `DefaultReceive` in the `default` case. 
Because property `Actor` is `null`
```
private Task DefaultReceive() =>
            Message switch
            {
                PoisonPill               => HandlePoisonPill(),
                IAutoRespond autoRespond => HandleAutoRespond(autoRespond),
                _                        => Actor!.ReceiveAsync(_props.ContextDecoratorChain is not null ? EnsureExtras().Context : this)
            };
```

## Steps to Reproduce the Problem

  1. Open the Dependency Injection example (https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/examples/DependencyInjection)
  2. Remove `services.AddTransient<DependencyInjectedActor>();` from `Startup`
  3. Call method `Get` from `ActorController`

## Specifications

  - Version: 0.18.1-alpha.0.19 (also reproducable in current master)

**Comment by rogeralsing** [comment]
Done
