### ISSUE TITLE
How to create/assign children

### ISSUE THREAD

**Issue by adamhathcock** [AsynkronIT/protoactor-dotnet#104]
I used `Props.Spawn(string, PID)` to try to assign an actor an parent.  However, it looks like only `Context.SpawnNamed(Props, string)` will do what I want.

Am I misunderstanding something or is there a disconnect in the code?

**Comment by cpx86** [comment]
No you should be using either `IContext.Spawn` (for child actors) or `Actor.Spawn` (for non-child actors). Perhaps we should hide `Props.Spawn` or get rid of it entirely.

**Comment by rogeralsing** [comment]
>Perhaps we should hide Props.Spawn or get rid of it entirely.

Agree

**Comment by raskolnikoov** [comment]
Me too. :)

**Comment by adamhathcock** [comment]
Cool...I'll make a PR then.

**Comment by cpx86** [comment]
Which way do we prefer? The easiest option would be to make it `internal` and add `InternalsVisibleToAttribute` where necessary. That's probably something we should do in other places as well.

**Comment by rogeralsing** [comment]
Yes, let's go for internal for now
