### ISSUE TITLE
Cluster spawn swallows errors without logging

### ISSUE THREAD

**Issue by sudsy** [AsynkronIT/protoactor-dotnet#1041]
I recently upgraded one of my projects to 0.18.0 and was receiving spawn errors without a reason. In my case it seems that the error was caused because I specified a GuardianSupervisor strategy for the cluster props which is no longer supported.

Anyway, rather than seeing the error in the log, it just failed with a can't spawn error.

It's a shame that I can no longer specify a guardian supervisor strategy for cluster kinds. I guess we are stuck with PartitionPlacementActor as the supervisor which makes it a little inflexible.

https://github.com/AsynkronIT/protoactor-dotnet/blob/f92d1ba2df6204e94e95f35d07d8b709af22f566/src/Proto.Cluster/Partition/PartitionPlacementActor.cs#L132

**Comment by rogeralsing** [comment]
>I specified a GuardianSupervisor strategy for the cluster props which is no longer supported

I'm not following, what change are we talking about here?

**Comment by sudsy** [comment]
In a much earlier version of ProtoActor you could specify a guardian strategy for Cluster kinds, but when I upgraded to 0.18.0 the cluster kinds with the guardian strategy couldn't be spawned and the error was swallowed by the PartitionPlacementActor.

**Comment by rogeralsing** [comment]
The lack of logging should absolutely be addressed. on it here.

But I'm not quite sure in what way this was possible before as the PartitionPlacementActor has not been changed recently.
So any hints on what snippet of code worked before that don't work now would be much appreciated

**Comment by sudsy** [comment]
You would have to go a long way back to find where it was possible to spawn a cluster actor with a Guardian Strategy.

See: https://github.com/AsynkronIT/protoactor-dotnet/blob/33a0e2784514b110793f626d11a7a76db895f0c2/src/Proto.Cluster/Partition.cs#L45

It previously spawned actors from the root context so a Guardian Strategy was possible.

Now it spawns cluster kinds as a child of PartitionPlacementActor:

https://github.com/AsynkronIT/protoactor-dotnet/blob/f92d1ba2df6204e94e95f35d07d8b709af22f566/src/Proto.Cluster/Partition/PartitionPlacementActor.cs#L119

So, after upgrading, when I use WithClusterKinds(clusterKindsList) to register my cluster kinds, if I specify a cluster kind with a GuardianSupervisorStrategy it fails to spawn.

For example:

```

var clusterKindsList = new List<(string kind, Props prop)>();

ISupervisorStrategy oneForOneStop = new OneForOneStrategy((pid, reason) =>
{
    _logger.LogError(reason, "Error caught by stopping strategy");
  
    return SupervisorDirective.Stop;

}, 0, null);

clusterKindsList.Add(("test_actor", Props.FromProducer(() => new TestActor()).WithGuardianSupervisorStrategy(oneForOneStop)));

//Then start the cluster with
clusterConfig.WithClusterKinds(clusterKindsList)

//Then try to spawn the test_actor using

var test_actor = await cluster.GetAsync("test_actor");
```
In my case, these particular actors shouldn't be restarted if they failed, they are subordinate to a coordinating actor on another machine. The coordinating actor watches these subordinate actors and will stop them or restart them depending upon the status of the coordinating actor, but if something does not go well I would prefer that they don't restart themselves.

Really what I would like for this particular use case is a way of spawning cluster actors so they behave the same way as a local  actor so that the lifecycle is tied to the spawning actor and that errors are bubbled up through the hierarchy even though it is across machines.

Failing that, making sure that the actors that are spawned on remote machines don't restart themselves is a good workaround.

**Comment by rogeralsing** [comment]
Partially solved. all spawning now logs if the spawn failed.
That being said, I see that it would be nice to be able to pass in a supervisor strategy for cluster actors

**Comment by rogeralsing** [comment]
Closing in favor of #1473
