### ISSUE TITLE
Make Context._logger lazy

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#108]
Having the eager init of the logger adds a few % overhead to actor creation.
By making it lazy we can shave off that overhead.

With the eager logger spawn benchmark: 1.1 sec
With lazy logger spawn benchmark: 0.97 sec

**Comment by raskolnikoov** [comment]
Yes I agree, lazy is king!

**Comment by adamhathcock** [comment]
So the assigning of the singleton instance of the null logger causes a difference of ~0.1 sec?

Did you just remove the log statement when you ran it otherwise?

**Comment by adamhathcock** [comment]
You might get more perf by doing the _behavior stack lazily.  If there's no extra receives then why do it?

I guess what I'm getting at is what is enough perf without making things too complex?

**Comment by cpx86** [comment]
@adamhathcock Good idea - in many cases you'll only have one default behavior so it might be more optimal to null-check the behavior stack on each receive and only use it when you have >1 behaviors (default + 1 alternative)

**Comment by adamhathcock** [comment]
I just went ahead and did it then :p

**Comment by cpx86** [comment]
Fixed by #112
