### ISSUE TITLE
Document deadlock when using await inside actors

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1094]
https://twitter.com/andreabalducci/status/1415226443198513153

This is a classic case of an actor passing a message to itself, and then awaiting on this task.
This will deadlock as the request is now stuck in the mailbox while the mailbox is awaiting the task to complete.

The same thing can happen in cyclic graphs of actors, so this is not unique to self messaging.

There is no generic rule that can be applied here, awaiting is fine, awaiting in cyclic message flows is not.
The only thing that can be done is to have better documentation for this.

`ReenterAfter` do prevent this type of deadlock, but will not help when the actor is supposed to be shut down. there is nothing to reenter in.

**Comment by rogeralsing** [comment]
To add some context.
Actor is awaiting.
The message that will complete the task is stuck in the mailbox as the actor is awaiting

<img width="657" alt="Skärmavbild 2021-07-14 kl  11 23 42" src="https://user-images.githubusercontent.com/647031/125598095-86626f51-3a2c-46c6-8425-bc2222a9cecf.png">

**Comment by rogeralsing** [comment]
cc @andreabalducci

**Comment by andreabalducci** [comment]
was unsure. first checked on issues, then forked the doc, then checked again the sources.
At first my suggestion was for throwing an exception if context was used to RequestAsync<> on self, but was unsure if context is "safe" to be used outside the actor message loop.

Agree for a better doc, is up to the dev.

**Comment by andreabalducci** [comment]
Usually in my code **every** RequestAsync has a timeout / cancellation token, I've checked the sources and PoisonAsync doesn't use a CancellationToken.
Tried  `await context.RequestAsync<Terminated>
                (
                    context.Self,
                    PoisonPill.Instance,
                    CancellationTokens.WithTimeout(200)
                );`
and timeout kicks in as expected without blocking the message loop.
