### ISSUE TITLE
Branch workflow

### ISSUE THREAD

**Issue by cpx86** [AsynkronIT/protoactor-dotnet#110]
We currently have master, dev and feature branches. All branches are automatically built and pushed to MyGet - with non-master branches getting a prerelease tag.

This slows down the workflow for deploying stable versions to NuGet.org, because we first need to merge dev->master, then manually push packages from MyGet to NuGet.

Two ways we could speed this up:
1. Scrap the dev branch completely and always merge to master.
2. Push stable packages automatically to NuGet.

I'm personally very much in favor of 1 - tbh I can't remember why I setup a dev branch in the first place! I'm not 100% sure about 2 - since it creates a risk of accidentally pushing broken packages to NuGet. It might be good to still have a manual verification step using MyGet before pushing.

Thoughts?

**Comment by raskolnikoov** [comment]
I vote for #1, thats how I work today at me company. Everything is features at start and when completed and valid it's merged to master and version tagged.

**Comment by adamhathcock** [comment]
Usually you'd do a dev branch to have an ongoing stream of work for a pre-defined milestone.  If there are no milestones and each feature is "done" and should be released you can just do #1.

I'd think you'd want to keep the dev branch just to have a manual step to release something that would contain N features.  I wouldn't say you could have each feature be merged then want to be automatically released.

To me, it sounds like you just need to have your CI setup to where master pushes to NuGet while all other branches push to MyGet.  Then everything else is automagic, right?

**Comment by cpx86** [comment]
I think the one thing I'd really like to achieve is making the push to NuGet as quick as possible. It's nice to be able to control the full release cycle using only Git. Right now the push to NuGet requires three manual steps:
1) merge dev to master
2) bump version number in dev
3) push packages from MyGet to NuGet

Regarding the branching, I like and have used both approaches. As @adamhathcock points out, a dev branch is nice for when you're working towards a milestone. But it can also be nice to use only a master branch, and do small incremental releases feature-by-feature.

There is a 3rd option as well that I thought of now that could give us the benefits of both: Setup the CI to automatically push both master and dev packages to NuGet. Master packages would be tagged as stable versions, and dev packages would be tagged as prerelease using build number and/or date as the suffix. That would achieve a few nice properties:
1. No manual steps to push to NuGet
2. When a PR is merged to dev the new feature can immediately be downloaded from NuGet as a prerelease version
3. We can use other branches for incomplete features, that will be published to MyGet but not to NuGet.
@adamhathcock @raskolnikoov @rogeralsing - Thoughts about this suggestion?

Yet another thing that needs consideration is how to do versioning. Currently the package version is set globally for all packages. Probably this should be changed to set the version explicitly in each package.

**Comment by adamhathcock** [comment]
What's making the release process not be as simple as the first step: merge dev to master?

For git versioning, I found this project but I don't think it works with new csproj: https://github.com/kzu/GitInfo  But it might be able to be ripped off somehow or find something similar.  Might be useful for versioning.

Could you not have the Cake script changed to see which branch you're on then publish to NuGet instead of MyGet?  You could also push `dev` releases as pre-release on NuGet like you've said.

**Comment by cpx86** [comment]
Yep the Cake script can easily read the current branch - that's actually how the package version is calculated (append branch name + build number for non-master branches)

**Comment by cpx86** [comment]
Another thing I noticed - PRs should probably be built on the CI. Not sure how to set that up though.

**Comment by cpx86** [comment]
@AsynkronIT/developers - you all now have access to restart builds on Appveyor :)

I'd like to implement the change to auto-publish `dev` and `master` packages to NuGet as well - that way anyone in the developers team can trigger a full deployment just by doing a git merge..
