### ISSUE TITLE
Cluster - RegisterServices - retry forever / throw exception on failure

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1168]
Due to the AWS outage the other day. there was a case where an ECS node tried to start, the RegisterService retried but failed. so the member was never registered as a member. even though the app itself started and worked fine.
Resulting in a sort of zombie cluster member.

We could make it so that nothing progresses until RegisterService has completed.
And we should do this for all cluster providers since it could theoretically happen anywhere.

Better to let cluster.StartMemberAsync just hang forever waiting for registration to complete. logging any issue.

**Comment by jstnlef** [comment]
Hey there. I was curious if you had a chance to look into this yet.

**Comment by rogeralsing** [comment]
Closing for now, if we need to extend this behavior, we can do this as a separate issue
