### ISSUE TITLE
Add package metrics and health to readme.md

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1170]
I just saw this lib https://github.com/BEagle1984/silverback
They have some nice quality and download badges in their readme.
We should add the same things for our readme here.

**Comment by SeanKilleen** [comment]
Adding some details in case they're helpful.

* The quality metrics in the README are surfaced from sonarcloud.io. Would need to import the repo(s) and set it up which requires permissions.
* Shields.io provides some of the other badges: https://shields.io
* I believe GitHub actions has badges for any use of GitHub Actions etc.
* I'm not sure test coverage stats are available OOTB with GitHub actions. CodeCov.io, Coveralls, or a similar service could probably provide these stats which could then be brought in via a shields.io badge or similar.
