### ISSUE TITLE
Cluster Example

### ISSUE THREAD

**Issue by suleymanyalcin** [AsynkronIT/protoactor-dotnet#1205]
Hi friends.
can you post a working cluster example?

**Comment by rogeralsing** [comment]
Have you tried the hello world cluster example?
https://github.com/asynkron/protoactor-dotnet/tree/dev/examples/ClusterGrainHelloWorld

Are there some specific features you want to see?

There is also this more advanced example
https://github.com/asynkron/realtimemap

**Comment by suleymanyalcin** [comment]
Can we use it without google.proto?

**Comment by rogeralsing** [comment]
No, not for that example. we use Protobuf service definitions for typed actor generation.

It is possible to use cluster actors without it. and the same for messages.
But protobuf is the recommended way.

**Comment by suleymanyalcin** [comment]
.nuget\packages\proto.cluster.codegen\task\net5.0 dll not found error?   net5.0 project supported?

**Comment by suleymanyalcin** [comment]
Can you make a cluster example without google.proto ?
thanks.
