### ISSUE TITLE
help for deploy docker

### ISSUE THREAD

**Issue by suleymanyalcin** [AsynkronIT/protoactor-dotnet#1209]
...

**Comment by suleymanyalcin** [comment]
In the bridge network, the actors cannot communicate, but in the host network they can.

**Comment by boguan01** [comment]
without much detail, I can only guess that you are using BindToLocalHost, which bind to 127.0.0.1 and stops working when the nodes run in different containers in bridge mode.  If that's the case, change Remote to BindTo the container IP instead.
