### ISSUE TITLE
Obsolete async methods lacking cancellation tokens?

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1214]
We have some methods that use TimeSpan, or simply no setting at all for cancellation.
I think it would make sense to obsolete these in favor for mandatory cancellation tokens.

I cannot imagine any single case where e.g. a RequestAsync should not have an explicit timeout.
Forcing cancellation tokens also makes disposing of such token possible

```csharp
public static Task<T> RequestAsync<T>(this ISenderContext self, PID target, object message)

public static Task<T> RequestAsync<T>(this ISenderContext self, PID target, object message, TimeSpan timeout)
```

**Comment by gsw945** [comment]
I think cancellation token is necessary, but with a default timeout value maybe nice. I'm lazy to supply provide a cancellation token every time explicitly, but also wish it has timeout mechanism.
