### ISSUE TITLE
ClusterKind with Props Factory to pass cluster identity and context to actor constructor

### ISSUE THREAD

**Issue by boguan01** [AsynkronIT/protoactor-dotnet#1241]
## Expected Behavior
WithClusterKind should have another overload with props factory, like WithClusterKind(KIND, Func<context, clusterIdentity, Props>), to allow producing actors with context and cluster identity parameters in its constructor.

## Actual Behavior
Actor needs its identity for persistence and other functions.  Currently the approach I found from CodeGen template and samples seems to be building a wrapper actor with inner factory to build the actual 'actor' by getting context and identity from the started message, which is cumbersome. 

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by rogeralsing** [comment]
This one is a bit tricky to do.
As you have discovered, the typed actors use a wrapper, and this wrapper is initialized on `Started` message.
Thus, the `Context` exists and can be passed in.

For constructor of actors, the context is not yet fully initialized, e.g. we cannot both have a context that points to the actor at the same time as the actor is being constructed in the constructor.

Probably all doable, but might have some unexpected side effects doing so.
I'm open for trying it out, but this will need some proper testing and discussions going forward.

**Comment by boguan01** [comment]
If not context, can we pass entityId / PID to the constructor?  Similar to the entityPropsFactory in Akka cluster sharding.

**Comment by rogeralsing** [comment]
I think we might be able to inject a smaller subset of IContext there.
That has access to the cluster identity etc. 
cc @mhelleborg

**Comment by rogeralsing** [comment]
Solved using `context.Get<ClusterIdentity>()`
