### ISSUE TITLE
Cluster members can start without connecting to cluster

### ISSUE THREAD

**Issue by sudsy** [AsynkronIT/protoactor-dotnet#1242]
## Expected Behavior
In version 0.18.0 if k8s cluster registration failed, the service would not start up and k8s would consider that as a failure restart the service and it would try again.

This is in line with my expected behaviour. I don't want the service to start up reporting that everything is working when it has failed to join the cluster. I want k8s to manage the restart of the service if it fails while connecting to the cluster or likewise if the cluster connection fails for some reason during operation. That way I can set thresholds for failures and operational alerting at the k8s level.

## Actual Behavior
In version 0.24.0 if k8s cluster registration fails, the service does not fail and retries the connection to the cluster. If there is a configuration error or some other permanent issue, the service continues to retry forever and k8s has no idea that anything is wrong. It makes it appear that the service has started up successfully. This leaves a server sitting there running but in a zombie state not connected to the cluster. 

I can see that the changes in #1168 were designed to resolve some issues with running the service under ECS but I think there might be more work that needs to be done. It seems like the fix is designed to address an issue during operation rather than on startup but has had unintended consequences.

Perhaps there should be a retry limit before crashing and allowing the service to restart? This would need to be fairly short because I would want to be aware of a problem with the cluster fairly soon after it happens and unless the service is crashing or throwing errors I will have no way to be alerted. 

Alternatively, the retry behaviour might be optional?

Thoughts?

**Comment by sudsy** [comment]
@rogeralsing I'd appreciate your thoughts on this when you get a chance!

**Comment by rogeralsing** [comment]
I missed following this one up.
But this is fixed now as members cannot get out of StartMember before the member sees themselves in the memberlist.

Closing, please reopen if this still surfaces in some way
