### ISSUE TITLE
Freeze Context

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1287]
As per discussions with @mhelleborg some time back, it would be nice to have immutable context that could be used in a threadsafe way.

This needs some careful thought though, as some aspects cannot be frozen, e.g. actor status, actor incarnation, children etc.

Likely this has to be limited to e.g. only `ISenderContext` or similar

**Comment by mhelleborg** [comment]
This is more or less solved with #1360, as message envelopes can now be captured and re-applied / received on demand.
