### ISSUE TITLE
Cluster Identity activation filter

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1310]
An idea that have come up is to be able to filter what Identities are possible to activate.

Let's say you want to guarantee that some identity exists in a database before spawning.
We could have activation middleware that allow us to prevent spawning of invalid identities.

**Comment by mhelleborg** [comment]
@rogeralsing This could just be implemented as a predicate on the ClusterKind, checked by the identity provider?

**Comment by mhelleborg** [comment]
Feature added in #1653
