### ISSUE TITLE
Persistence differences between Go and .net APIs plus other things

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#137]
The Go persistence API and the .net persistence API are different. 

The Go API looks like

```
        Restart()
	GetSnapshotInterval() int
	GetSnapshot(actorName string) (snapshot interface{}, eventIndex int, ok bool)
	GetEvents(actorName string, eventIndexStart int, callback func(e interface{}))
	PersistEvent(actorName string, eventIndex int, event proto.Message)
	PersistSnapshot(actorName string, eventIndex int, snapshot proto.Message)
```

The .net one:

```
        Task<(object Snapshot, long Index)> GetSnapshotAsync(string actorName);
        Task PersistSnapshotAsync(string actorName, long index, object snapshot);
        Task DeleteSnapshotsAsync(string actorName, long inclusiveToIndex);
        Task GetEventsAsync(string actorName, long indexStart, Action<object> callback);
        Task PersistEventAsync(string actorName, long index, object @event);
        Task DeleteEventsAsync(string actorName, long inclusiveToIndex);
```

Obvious differences are
1. You can delete events and snapshots in .net API
2. You can restart in Go API
3. You can get the Snapshot interval in Go API

There are a couple of other things I'd like to see in both:

1. allow replaying up to a certain event index
2. allow replaying up to a certain point in time
3. separate out the stores for snapshots and events see https://github.com/AsynkronIT/protoactor-dotnet/pull/136 for example

What are people's thoughts on this?

**Comment by rogeralsing** [comment]
As there are a lot of traction in the .NET side of things now, I think we could drive the API design for persistence here and then backport it to Go

**Comment by raskolnikoov** [comment]
I think that if you want to mix Redis and EventStore for snapshots/events just build a plugin that do that in the same provider instead of splitting them into two. Other way would be to introduce another persistence api, SnapshotPersistence/EventPersistence api. So If you don't wanna store the data in the same storage you go for two middleware providers to your actor. Don't really have an idea how to implement this in the actor then, since when using Persistence api you use a IPersistenceActor... And do we really wanna introduce more "IActors"?

**Comment by tomliversidge** [comment]
I'd like it to work where you just say 'I want to use provider1 for events and provider2 for snapshots'  where provider1 and provider2 are the existing implementations. There's no way of doing that with the current API as it doesn't distinguish between the two things. I don't think a new persistence API is necessary either.

My example might not be the best way to do this - I'll have a think and play around to see if I can come up with something good

**Comment by cpx86** [comment]
How about writing a wrapper provider that uses two underlying providers? Maybe not super clean, but non-intrusive at least.

**Comment by alexpantyukhin** [comment]
I think that @cpx86 workaround is okay. Btw I think that it's not a good to split infrastructure with many storages and variant that I will need separated storages for `Events` and `Snapshots` is not such vital. I think that it's preferable to have such infrastructure in one place. What do you think?

**Comment by tomliversidge** [comment]
@cpc86 - that's what I did in the example

**Comment by tomliversidge** [comment]
It's called SeparateEventAndSnapshotStateProvider

:)

**Comment by raskolnikoov** [comment]
I agree with alex, about splitting infrastructure. I vote no for this change for now.

**Comment by tomliversidge** [comment]
Just to clarify - you don't *need* to use separate storages, it's just the API allowing it if you want. It's no extra work for providers to implement either as they are already implementing it, it's just a splitting of the interface currently being implemented into two separate ones. It also has no effect on the current API - you would need to explicitly use the wrapper to split the storages. 

Having said all that, I agree that in most cases it's not needed at all and would be a bad idea :)

**Comment by tomliversidge** [comment]
Sorry accidentally closed issue then.. 

What about other ideas? I think replaying up to a certain index and time are more important to support, as is manually-initiated recovery

**Comment by alexpantyukhin** [comment]
@tomliversidge I also like the idea of splitting because it makes more... Single responsibility.. elegancy.  But the current design imposes that "You need to use one storage. If not - implement what you want yourself". It's as I read the current implementation. And I think that this principle is sutable there.

**Comment by tomliversidge** [comment]
Lets keep the example PR around for a few days just in case anyone else wants to chime in. Then we can close it.

**Comment by tomliversidge** [comment]
Another question - should you be able to delete snapshots from an index i.e. "delete all snapshots since index 6" ?

**Comment by tomliversidge** [comment]
And another - should Index in the Persistence class begin at -1 rather than 0? i.e. the first event that gets saved is position 0. This is the convention for EventStore, where a stream starts at position -1, and it is only when the first event is saved that it becomes 0. This also makes sense from the point of view of an array / collection - the first item is at index 0. 

Currently, the first item using the Persistence module right now is index 1

**Comment by raskolnikoov** [comment]
In Akka.net Persistence the index starts at 0 as far as I can read in the src code.

**Comment by edblackburn** [comment]
In my opinion snapshots (state) and events (deltas) are separate and thus the interface perhaps ought to be spilt. I actually went to raise an issue to discuss and noticed it had already been raised. 

Would you object to keeping this open until next weekend? I'd love to dig deeper and contribute but I shan't have to time until later in the week.

**Comment by edblackburn** [comment]
I've had a look and was considering how I'd implement `IPersistentActor` for[SqlStreamStore](https://github.com/damianh/SqlStreamStore). What became apparent immediately is that the interface `IProviderState` in my humble opinion looks a bit busy and conflates state and deltas. 

Humbly I would suggest separating state and delta contracts because as it stands it appears to be a leaky abstraction.

**Comment by tomliversidge** [comment]
@edblackburn did you look at the existing PR? https://github.com/AsynkronIT/protoactor-dotnet/pull/136

**Comment by edblackburn** [comment]
@tomliversidge Honestly. I think separating them entirely would make more sense. I think it's too difficult to create the perfect abstraction that works for both approaches. Personally, I'd be inclined to copy and paste and let them divulge organically. 

Just to conflate things you may choose to create state from events, but persist only the state. 

My opinion is slanted towards event sourcing, which may not be what you are trying to achieve. 

I will take a closer look this week when I'm back at work.

**Comment by tomliversidge** [comment]
You mean have a separate interface at the actor level? I.e IAmEventSourced and IUseSnapshots? That's interesting, I might have a play around with that

I think the motivation here is to be able to use event sourcing and/or snapshotting as the persistence strategy. 

I'm interested in your use case for creating state from events but not persisting the events - can you elaborate?

**Comment by raskolnikoov** [comment]
@tomliversidge I think he means that you use snapshots to persist data for the actor and not store the events because of performance maybe?

**Comment by edblackburn** [comment]
I may be getting my wires crossed here, apologies if I have.

> You mean have a separate interface at the actor level? I.e IAmEventSourced and IUseSnapshots? That's interesting, I might have a play around with that

Yes. Two different interfaces. I would propose this approach because I think the two types of persistence are so different, that munging them together is likely to cause a poor first stab at an abstraction. I think it'd reduce the complexity too.

> I think the motivation here is to be able to use event sourcing and/or snapshotting as the persistence strategy.

Yes. It seems unlikely you'll need two different persistence mechanisms in the same actor?

> I'm interested in your use case for creating state from events but not persisting the events - can you elaborate?

Projections. I need to replay events from a stream to project state to a HTTP API for consumption by another component.

I hope to look at this a bit more this week.

**Comment by tomliversidge** [comment]
It is common to use event sourcing _with_ snapshotting to improve performance. The persistence Class handles the index of the event stream too, so they are quite coupled

In terms of projections, that's not the motivation behind this. This is very much the write side of things. The persistence API uses the actor id for it's operations and reads events for one particular actor. You want more flexibility when it comes to projections I.e. specific event types, all events etc..

**Comment by tomliversidge** [comment]
I'm going to separate this issue out into individual issues as everything is all jumbled up inside here...
