### ISSUE TITLE
Seed node cluster provider

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1380]
Thinking out loud here:

1. every seed node starts "seed actor"

2. every member/seed node starts a "cluster provider actor"

3. any member node sends a join request to one of the seed nodes "seed actor"

4. "seed actor" sends Join notification to all known members, to each nodes "cluster provider actor"

5. "cluster provider actor" calls member list, updating the local topology

6. all nodes are now aware of each other, normal gossip works

7. we can use local heartbeat timestamps to detect members that no longer sends heartbeats, and mark them as blocked

**Comment by mhelleborg** [comment]
Mostly this seem like it should just work. Still some details missing perhaps, ex how does the members know where the seed node is? 

Would this be just for relatively static deployments where you hardcode the seed address?

**Comment by rogeralsing** [comment]
There is now an extension on cluster `JoinSeed(("host", port), ("host", port))`
Where you can list a number of known seed nodes.
