### ISSUE TITLE
Proto.Cluster => 'Cluster' is a namespace but is used like a type

### ISSUE THREAD

**Issue by codrutmarin** [AsynkronIT/protoactor-dotnet#1425]
## Steps to Reproduce the Problem

  1. Create a new class project .Net 6
  2. Update the `.csproj` file with the following `Package References`
  ```
    <PackageReference Include="Google.Protobuf" Version="3.19.4" />
    <PackageReference Include="Grpc.Tools" Version="2.43.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Proto.Cluster.CodeGen" Version="0.27.0" />
  ```
  3. Use the following `.proto` file 
```
syntax = "proto3";
package GroupMessages;
option csharp_namespace = "Proto.Clustered.Shared";

message GroupCreate {
	string GroupId = 1;
	string Name = 2;
}

message GroupUpdate {
	string GroupId = 1;
	string Name = 2;
}

message GroupDelete {
	string GroupId = 1;
}

message GroupStatus {
	string GroupId = 1;
}

message Error {
	string Message = 1;
}

message Group {
	string Id = 1;
	string Name = 2;
}

message GroupResponse {
	oneof Result {
		Error Error = 1;
		Group Group = 2;
	}
}

service GroupGrain {
	rpc Create(GroupCreate) returns (GroupResponse) {}
	rpc Update(GroupUpdate) returns (GroupResponse) {}
	rpc Delete(GroupDelete) returns (GroupResponse) {}
	rpc Status(GroupStatus) returns (GroupResponse) {}
}
```
4. Import into a console application build and run; results in this:
![image](https://user-images.githubusercontent.com/18661271/152335094-0d2237ca-c060-4dfb-ac25-8fd4d3cc96c9.png)

## Specifications

  - Version: 0.27.0
  - Platform: Windows +  Visual Studio 

## StackTrace
<details>

```

```

</details>

**Comment by pblachut** [comment]
I think you miss 

`<ProtoGrain Include="Grains.proto" />` grain build in your csproj.

You can check tutorial here for more details: https://proto.actor/docs/cluster/getting-started-net/

**Comment by codrutmarin** [comment]
I have both `<ProtoGrain` & `<Protobuf` included: 
```
<ItemGroup>
   <Protobuf Include="Group.proto" />
</ItemGroup>
<ItemGroup>
   <ProtoGrain  Include="Group.proto" />
</ItemGroup>
```

**Comment by pblachut** [comment]
Ok, now I spotted what is wrong :) Your proto namespace is:

`option csharp_namespace = "Proto.Clustered.Shared";`

so your classes are generated under Proto namespace and that is why it doesnt work. Try to change a first namespace part in proto file e.g. for `Protos.Clustered.Shared` and the issue should go away.

**Comment by codrutmarin** [comment]
Okay, that did it! Thank you!

**Comment by rogeralsing** [comment]
@pblachut @mhelleborg this hints that it might be a good idea for us to use fully qualified typenames in the generated code:

global::Proto.xxxx
