### ISSUE TITLE
Refactor Routing into separate project

### ISSUE THREAD

**Issue by cpx86** [AsynkronIT/protoactor-dotnet#15]
The routing package in Go has been refactored since the .NET implementation was done and is now standalone. The same should be done here.

Also a bit related, maybe the Proto namespace should be moved to Proto.Actor, so we align the Go packages/.NET assemblies.

**Comment by rogeralsing** [comment]
👍 on both parts.

**Comment by cpx86** [comment]
Will do that as well before moving on to persistence, so we have the fundamentals in order.

**Comment by rogeralsing** [comment]
Closed by #17
