### ISSUE TITLE
Proto.Cluster.CodeGen 0.28 not working anymore - Wrong version of Handlebars.dll 

### ISSUE THREAD

**Issue by Mastaleck** [AsynkronIT/protoactor-dotnet#1503]
Hi,

I upgraded today to release 0.28 and Proto.Cluster.CodeGen is not working anymore. 
Getting an System.IO.FileNotFoundException: Handlebars Version 2.1.0.0 could not be found.

In the nuget package tasks folder there is a Handlebars.dll but the wrong Version 2.0.9.0.

![screenshot_handlebars_version](https://user-images.githubusercontent.com/35456426/156749867-bd13dde3-59ad-4611-84b1-1dc135e47bab.PNG)

After manually overriding the dll with the correct version code generation works as expected.

**Comment by mhelleborg** [comment]
Downgraded the reference for now.

We should fix a better way to include the deps later, but this should fix the immediate issue
