### ISSUE TITLE
How can I get actor by name?

### ISSUE THREAD

**Issue by andreydruz** [AsynkronIT/protoactor-dotnet#152]
After I create actor by name

`var pid3 = Actor.SpawnNamed(props, "my-actor");`

Can I get this actor by "my-actor" name if I don't have pid3?

**Comment by rogeralsing** [comment]
Yes.

`var pid = new PID("localhost:8080","my-actor");`

if you are on a local system, then this would be the way:

`var pid = new PID(ProcessRegistry.Address,"my-actor");`

**Comment by andreydruz** [comment]
Thanks

**Comment by andreydruz** [comment]
About
`var pid = new PID(ProcessRegistry.Address,"my-actor");`
I get error: "An object reference is required for the non-static field, method, or property ProcessRegistry.Address"
How do I get ProcessRegistry ?

**Comment by andreydruz** [comment]
Found workaround.
For local actor I using:
`var pid = new PID("nonhost","my-actor");`
