### ISSUE TITLE
[EKS] Single time, Gossip loop failed -> Stopping Cluster

### ISSUE THREAD

**Issue by seungyongshim** [AsynkronIT/protoactor-dotnet#1535]
## Expect
* Success joining cluster

## Actual
* A single time, stopped actor system.

## Specifications
* Version: 0.28.0
* Platform: AWS EKS v1.20
* Subsystem: dotnet6
* Node: m5.large
* Limit 
```yaml
    resources:
      limits:
        cpu: 1
        memory: 2G
      requests:
        cpu: 0.5
        memory: 2G
```
   * I read https://github.com/asynkron/protoactor-dotnet/issues/1524, but SRE guy want to use resources limit for pod.

## Log

timestamp | level | message
-- | -- | --
48:04.8 | Warning | Storing keys in a directory '{path}' that may not be persisted outside of   the container. Protected data will be unavailable when container is   destroyed.
48:04.8 |   | Starting
48:04.8 |   | Starting Proto.Actor server on {Host}:{Port} ({Address})
48:04.8 |   | Started Cluster Gossip
48:04.9 |   | [Cluster][KubernetesProvider] Registering service {PodName} on {PodIp}
48:06.4 |   | Starting gossip loop
48:06.6 |   | [Cluster][KubernetesProvider] Using Kubernetes port: 34647
48:06.6 |   | [Cluster][KubernetesProvider] Using Kubernetes namespace: aums
48:06.8 |   | Started as cluster member
48:06.9 |   | [MemberList] Cluster members joined {MembersJoined}
48:06.9 |   | [MemberList] Cluster members joined {MembersJoined}
48:06.9 |   | I see myself
48:06.9 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:07.0 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:07.0 | Warning | No XML encryptor configured. Key {KeyId:B} may be persisted to storage in   unencrypted form.
48:07.2 |   | [{SystemAddress}] Connecting to {Address}...
48:07.6 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:07.6 |   | [MemberList] Cluster members joined {MembersJoined}
48:07.6 | Warning | Timeout in GossipReenterAfterSend
48:07.8 |   | [{SystemAddress}] Connecting to {Address}...
48:08.0 | Warning | Timeout in GossipReenterAfterSend
48:08.2 |   | [{SystemAddress}] Connected to {Address}
48:08.2 |   | [MemberList] Cluster members joined {MembersJoined}
48:08.2 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:08.3 | Warning | Timeout in GossipReenterAfterSend
48:08.3 | Warning | Timeout in GossipReenterAfterSend
48:08.4 |   | [{SystemAddress}] Connecting to {Address}...
48:08.6 | Warning | Timeout in GossipReenterAfterSend
48:08.6 | Warning | Timeout in GossipReenterAfterSend
48:08.8 |   | [{SystemAddress}] Connected to {Address}
48:08.8 |   | [{SystemAddress}] Connected to {Address}
48:08.8 |   | [MemberList] Cluster members left {MembersJoined}
48:08.9 | Warning | Timeout in GossipReenterAfterSend
48:08.9 | Warning | Timeout in GossipReenterAfterSend
48:08.9 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:09.2 | Warning | Timeout in GossipReenterAfterSend
48:09.3 |   | [MemberList] Cluster members joined {MembersJoined}
48:09.3 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:09.5 | Warning | Timeout in GossipReenterAfterSend
48:13.4 |   | [MemberList] Cluster members joined {MembersJoined}
48:13.4 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:13.5 |   | [MemberList] Cluster members joined {MembersJoined}
48:13.5 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:15.1 |   | [MemberList] Cluster members joined {MembersJoined}
48:15.1 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:19.4 |   | [MemberList] Cluster members joined {MembersJoined}
48:19.4 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:19.7 | Error | Gossip loop failed
48:25.0 | Error | Gossip loop failed
48:26.6 | Warning | [{SystemAddress}] Error in reader for {Address} {Reason}
48:26.6 |   | [{SystemAddress}] Connecting to {Address}...
48:26.6 | Error | Receive is taking too long {Elapsed} {Self} incoming message {Message}
48:26.6 | Warning | Timeout in GossipReenterAfterSend
48:26.6 | Warning | Timeout in GossipReenterAfterSend
48:26.6 | Warning | Timeout in GossipReenterAfterSend
48:26.6 |   | [{SystemAddress}] Connecting to {Address}...
48:26.6 |   | [{SystemAddress}] Connecting to {Address}...
48:26.6 |   | [{SystemAddress}] Connecting to {Address}...
48:26.6 |   | [{SystemAddress}] Connecting to {Address}...
48:26.6 |   | [{SystemAddress}] Connected to {Address}
48:26.6 |   | [{SystemAddress}] Connected to {Address}
48:26.6 |   | [MemberList] Cluster members left {MembersJoined}
48:26.6 | Error | [{SystemAddress}] Connection Refused to remote member {MemberId} address   {Address}, we are blocked
48:26.6 |   | [{SystemAddress}] Connected to {Address}
48:26.6 |   | [{SystemAddress}] Connected to {Address}
48:26.6 |   | Error reading message.
48:26.6 | Warning | DeadLetter in GossipReenterAfterSend
48:26.7 |   | Blocking members due to expired heartbeat {Members}
48:26.7 |   | Error reading message.
48:26.7 | Error | Error when executing service method '{ServiceMethod}'.
48:26.7 |   | {SystemId} topology {CurrentTopology} Pausing activations while rebalance   in progress, {SpawnCount} spawns waiting
48:26.7 |   | [PartitionIdentity] Pulling activations for topology {CurrentTopology}   from {@MemberAddresses}
48:26.7 | Error | Error when executing service method '{ServiceMethod}'.
48:26.7 |   | [{SystemAddress}] Disconnected from {Address}
48:26.7 |   | Error reading message.
48:26.7 | Error | Error when executing service method '{ServiceMethod}'.
48:26.7 |   | [{SystemAddress}] Connecting to {Address}...
48:26.7 |   | [{SystemAddress}] Dropped {Count} messages for {Address}
48:26.7 |   | Error reading message.
48:26.7 |   | Error reading message.
48:26.7 | Warning | DeadLetter in GossipReenterAfterSend
48:26.7 |   | Error reading message.
48:26.7 | Error | [{SystemAddress}] Connection Refused to remote member {MemberId} address   {Address}, we are blocked
48:26.7 |   | Error reading message.
48:26.7 |   | Error reading message.
48:26.8 | Error | Error when executing service method '{ServiceMethod}'.
48:26.8 | Error | Error when executing service method '{ServiceMethod}'.
48:26.8 | Warning | DeadLetter in GossipReenterAfterSend
48:26.8 | Warning | DeadLetter in GossipReenterAfterSend
48:26.8 | Warning | DeadLetter in GossipReenterAfterSend
48:26.8 | Warning | DeadLetter in GossipReenterAfterSend
48:26.8 | Error | Error when executing service method '{ServiceMethod}'.
48:26.8 | Warning | DeadLetter in GossipReenterAfterSend
48:26.8 | Warning | DeadLetter in GossipReenterAfterSend
48:26.8 | Warning | DeadLetter in GossipReenterAfterSend
48:26.8 | Error | Error when executing service method '{ServiceMethod}'.
48:26.8 | Error | Error when executing service method '{ServiceMethod}'.
48:26.8 |   | Error reading message.
48:26.8 | Error | Error when executing service method '{ServiceMethod}'.
48:26.8 | Warning | DeadLetter in GossipReenterAfterSend
48:26.8 |   | [{SystemAddress}] Dropped {Count} messages for {Address}
48:26.8 | Warning | [PartitionIdentity] Partition {Member} unreachable
48:26.8 |   | Error reading message.
48:26.8 | Error | Error when executing service method '{ServiceMethod}'.
48:26.9 |   | Error reading message.
48:26.9 | Error | Error when executing service method '{ServiceMethod}'.
48:26.9 |   | [{SystemAddress}] Connecting to {Address}...
48:26.9 | Error | [{SystemAddress}] Connection Refused to remote member {MemberId} address   {Address}, we are blocked
48:26.9 | Warning | DeadLetter in GossipReenterAfterSend
48:26.9 |   | [{SystemAddress}] Dropped {Count} messages for {Address}
48:27.0 |   | [{SystemAddress}] Connecting to {Address}...
48:27.0 | Warning | [PartitionIdentity] Partition {Member} unreachable
48:27.0 |   | [{SystemAddress}] Dropped {Count} messages for {Address}
48:27.0 | Error | [{SystemAddress}] Connection Refused to remote member {MemberId} address   {Address}, we are blocked
48:27.0 |   | [{SystemAddress}] Connecting to {Address}...
48:27.0 |   | Error reading message.
48:27.0 |   | Error reading message.
48:27.0 | Error | Error when executing service method '{ServiceMethod}'.
48:27.0 | Error | Error when executing service method '{ServiceMethod}'.
48:27.0 | Warning | DeadLetter in GossipReenterAfterSend
48:27.0 |   | [{SystemAddress}] Dropped {Count} messages for {Address}
48:27.0 | Error | [{SystemAddress}] Connection Refused to remote member {MemberId} address   {Address}, we are blocked
48:27.2 |   | [{SystemAddress}] Connecting to {Address}...
48:27.2 | Error | [{SystemAddress}] Connection Refused to remote member {MemberId} address   {Address}, we are blocked
48:27.2 | Warning | [PartitionIdentity] Partition {Member} unreachable
48:27.2 |   | [{SystemAddress}] Dropped {Count} messages for {Address}
48:27.2 | Warning | Timeout in GossipReenterAfterSend
48:27.2 | Warning | Timeout in GossipReenterAfterSend
48:27.3 |   | Shutting down heartbeat
48:27.3 |   | Stopping Cluster {Id}
48:27.3 |   | Shut down heartbeat
48:27.3 |   | [Cluster][KubernetesProvider] Unregistering service {PodName} on {PodIp}
48:27.3 | Error | Gossip loop failed
48:27.4 |   | [Cluster][KubernetesProvider] Stopping monitoring for {PodName} with ip   {PodIp}
48:27.4 |   | [Cluster][KubernetesProvider] Stopping monitoring for {PodName} with ip   {PodIp}
48:27.4 |   | [{SystemAddress}] Disconnected from {Address}
48:27.4 |   | [{SystemAddress}] Disconnected from {Address}
48:27.4 |   | [{SystemAddress}] Disconnected from {Address}
48:27.4 |   | [{SystemAddress}] Disconnected from {Address}
48:27.4 |   | [{SystemAddress}] Disconnected from {Address}
48:27.4 |   | Stopped Cluster {Id}
48:27.4 |   | Proto.Actor server stopped on {Address}. Graceful: {Graceful}

**Comment by rogeralsing** [comment]
The settings for gossip can be tweaked using these two values:
https://github.com/asynkron/protoactor-dotnet/blob/dev/src/Proto.Cluster/ClusterConfig.cs#L27-L28

It is also possible to extend the window for how long a member node is allowed to have no heartbeat before getting evicted:
https://github.com/asynkron/protoactor-dotnet/blob/dev/src/Proto.Cluster/ClusterConfig.cs#L31

But that being said. the timeouts are a clear sign that the system cannot process as much as it needs to.
e.g. the gossip timeout is 0.5 seconds by default. so getting these timeouts means that it takes longer than this to transfer a simple heartbeat message.

**Comment by rogeralsing** [comment]
I'll try to collect some more details about this

https://builders.intel.com/docs/networkbuilders/cpu-pin-and-isolation-in-kubernetes-app-note.pdf
