### ISSUE TITLE
C# How to delete actor in cluster mode?

### ISSUE THREAD

**Issue by hejiang123** [AsynkronIT/protoactor-dotnet#1543]
When the user goes online, I get an actor in the cluster through grain But this actor always exists in the service I want to delete this actor successively in the user to release the memory of the service. What should I do?

**Comment by rogeralsing** [comment]
To stop the actor, you call:
`context.Stop(context.Self)`  //stops immediately
or 
`context.Poison(context.Self)` //stops after processing all messages currently on the actors mailbox

You can use `context.SetReceiveTimeout(timeout)` to make the actor send a message to itself after x time of idling.
Meaning, if the actor does not receive any messages for `timeout` time. then it automatically sends a `ReceiveTimeout` message to itself, and you can decide to stop it then.

Or, if your infrastructure have some way of detecting that a user session ended. e.g. a closed websocket. then you could send a message to the actor which triggers the shutdown

**Comment by hejiang123** [comment]
> To stop the actor, you call: `context.Stop(context.Self)` //stops immediately or `context.Poison(context.Self)` //stops after processing all messages currently on the actors mailbox
> 
> You can use `context.SetReceiveTimeout(timeout)` to make the actor send a message to itself after x time of idling. Meaning, if the actor does not receive any messages for `timeout` time. then it automatically sends a `ReceiveTimeout` message to itself, and you can decide to stop it then.
> 
> Or, if your infrastructure have some way of detecting that a user session ended. e.g. a closed websocket. then you could send a message to the actor which triggers the shutdown

Hello, my current practice is to call after the user is offline.

ClusterIdentity clusterIdentity = ClusterIdentity. Create(_userId.ToString(), PlayerbGrainActor. Kind);

_ actorSystem. Cluster(). RequestAsync<Terminated>(clusterIdentity, Stop.Instance, new CancellationTokenSource(). Token);

To delete the actor of the service center. The actual effect will fall into a dead cycle, constantly deleting and creating this actor Excuse me, I need to implement the interface myself to delete. Can't I use the stop built in proto to delete

**Comment by rogeralsing** [comment]
`_ actorSystem. Cluster(). RequestAsync(clusterIdentity, Stop.Instance, new CancellationTokenSource(). Token);``

Here you are sending a system message via the request pipeline.
Rather you should send a custom user message. e.g. `SessionEnded` or something like that.
And internally in the actor, you do context.Stop or Poison
