### ISSUE TITLE
EndpointManager does not subscribe to EndpointTerminatedEvent

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#162]
see https://github.com/AsynkronIT/protoactor-go/blob/dev/remote/endpoint_manager.go#L19
this part is responsible for notifying the endpointmanager when a node is no longer available.

**Comment by tomliversidge** [comment]
I need to fix this as part of a test I'm writing for killing a remote node so I'll take this
