### ISSUE TITLE
Question about actor dependency in ChildN... actor

### ISSUE THREAD

**Issue by andreydruz** [AsynkronIT/protoactor-dotnet#163]
I have a question about actor dependency.

If I creating infrastructure actor Parent and this actor creating Child1 and Child1 creating Child2 ... ChildN
How can I pass dependency to ChildN?
I think about some options:

- Constructor injection with many services one by one (need to pass many services to Parent).
- Constructor injection with 1 class what have composition of all services.
- Service Locator (many people don't like this pattern).
- Static classes (good for app wide services only).

What will be the best option?

**Comment by adamhathcock** [comment]
This is exactly the problem I'm solving with my DI Extensions: https://github.com/AsynkronIT/protoactor-dotnet/pull/143

It uses an IServiceProvider to create all actors and you can create actors and PIDs with IActorFactory

**Comment by adamhathcock** [comment]
Now it's merged, you can look at the DI example for getting an `IActorFactory` injected: https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/examples/DependencyInjection/ActorManager.cs

This isn't on nuget though.

**Comment by andreydruz** [comment]
Thanks.
