### ISSUE TITLE
Replace Console.Writeline to Logger

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#167]
There are still a few places in the code that uses Console.WriteLine, we should replace this with proper logging code.

**Comment by alexpantyukhin** [comment]
Some of them:

https://github.com/AsynkronIT/protoactor-dotnet/blob/0321d6acb066f1ffca439db78bec71f7e338da0a/src/Proto.Remote/EndpointWriter.cs#L101
https://github.com/AsynkronIT/protoactor-dotnet/blob/0321d6acb066f1ffca439db78bec71f7e338da0a/src/Proto.Remote/EndpointWriter.cs#L118
https://github.com/AsynkronIT/protoactor-dotnet/blob/577ddff5fb33bd7b441bffdb50ace916923b1281/src/Proto.Cluster/Cluster.cs#L30
https://github.com/AsynkronIT/protoactor-dotnet/blob/0321d6acb066f1ffca439db78bec71f7e338da0a/src/Proto.Remote/EndpointManager.cs#L41
https://github.com/AsynkronIT/protoactor-dotnet/blob/577ddff5fb33bd7b441bffdb50ace916923b1281/src/Proto.Cluster/MemberListActor.cs#L24
https://github.com/AsynkronIT/protoactor-dotnet/blob/cb680772049d850f14abeb2fc7a0d25eff34e2ad/src/Proto.Remote/Remote.cs#L62
https://github.com/AsynkronIT/protoactor-dotnet/blob/577ddff5fb33bd7b441bffdb50ace916923b1281/src/Proto.Cluster/Partition.cs#L72

**Comment by adamhathcock** [comment]
Looking into this as I'm avoiding some work.

Should some of the statements just be deleted?  Like the ones that are just "X Started" ?

**Comment by rogeralsing** [comment]
I still think they add some value on start up of cluster and remoting, as they make it easy to see where in the start up flow something broke. maybe just do them as debug

**Comment by rogeralsing** [comment]
And should we just have a shared logger per module?
e.g.
Proto.Actor.Logger
Proto.Cluster.Logger

instead of creating different ones all over the place?

**Comment by adamhathcock** [comment]
Each logger is contextual to the class using it.  Basically, it uses the class name as part of the context of the log event.  Loggers themselves are really lightweight but there is one made per instance (unless no logging is set).

The Cluster and Remote static classes are getting a static logger each though.

**Comment by tomliversidge** [comment]
Would need to think about how this is used in tests. For example, at the moment it is useful for the [REMOTING] messages to show in the output of the tests. See example output here https://github.com/AsynkronIT/protoactor-dotnet/pull/169

Whatever mechanism is used, it would be nice if the output shows when running tests, i.e. is hooked into XUnit (I've not looked into this, but something like http://dhickey.ie/2015/06/capturing-log-output-in-tests-with-xunit2/ _might_ be a way to do it)

**Comment by adamhathcock** [comment]
If you're looking at output then it's not a unit test.  If you want just a tester app for debugging or watching it work, then just hook up the logging with the console logger like here: https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/examples/Supervision/Program.cs#L18

I'll fix more after the UK easter holidays (tuesday, maybe)

**Comment by tomliversidge** [comment]
Well, the remoting tests for example are probably best defined as system tests. In these tests it can be useful to read the output. If the default logger is console it might all just work anyway...
