### ISSUE TITLE
Terminated message is received twice when a watched remote actor is stopped

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#170]
I've noticed that the Terminated message is received twice when you have a local actor watch a remote actor and the remote actor is stopped.

Here is the output from tests when the local actor logs receiving the Terminated message:

![capture](https://cloud.githubusercontent.com/assets/1437372/25042214/e87df7ce-211e-11e7-8e41-7167ef8ae74e.JPG)

Note this does not happen when the remote node is forcibly killed, only when you call remoteActorPID.Stop();

**Comment by tomliversidge** [comment]
Looks like the difference between the two messages is that the second one says the address has been terminated also:

![capture](https://cloud.githubusercontent.com/assets/1437372/25042634/56aff596-2122-11e7-99bc-ab0eabc4c07a.JPG)

**Comment by rogeralsing** [comment]
Hmm, the Address Terminated one should only occur when the connection between nodes is lost.
So that message originates from the EndpointWatcher.
My guess is that there is a bug in there

**Comment by tomliversidge** [comment]
I just ran a test to make sure you can still create remote actors after stopping one, and you can, so i don't think it is actually terminating the address. I think the bug is probably here https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Remote/EndpointWatcher.cs#L33

But that would still mean there are two messages being sent. Is one from the remote actor itself, and the other from the endpoint watcher?

**Comment by rogeralsing** [comment]
You are right, the highlighted line is incorrect.

The terminated message from the remote actor should go through the EndpointWatcher.
Maybe it does both, e.g. both go through the EndpointWatcher and might be frowarded directly to the watching actor.. maybe a missing return in between or something

**Comment by rogeralsing** [comment]
i found the issue:
this should be an `else if` https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Remote/EndpointReader.cs#L38

**Comment by tomliversidge** [comment]
Yup, if I change that I only get a single Terminated message now - I'll add to https://github.com/AsynkronIT/protoactor-dotnet/pull/169
