### ISSUE TITLE
Context changes during message processing after calling Persistence API

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#171]
For example:

```
public async Task ReceiveAsync(IContext context)
        {
            switch (context.Message)
            {
                case Multiply msg:
                    // context.Message is Multiply
                    await Persistence.PersistEventAsync(new Multiplied { Amount = msg.Amount });
                    // context.Message is now PersistedEvent
                    break;
            }
        }
```

It has also been reported that context.Sender changes too.

**Comment by tomliversidge** [comment]
Presumably https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Persistence/Persistence.cs#L48 is what causes the context to change

**Comment by raskolnikoov** [comment]
Same goes for PersistSnapshotAsync too I guess?

**Comment by rogeralsing** [comment]
In Go, the persistence plugin does not go through the ReceiveAsync method, it simply picks the current behavior and calls that. meaning the message being processed will not be the same as the Message property. (which is not completely great either)

What we could do, is to let the persistence provider read the current (raw) message, and then re-set it after the persist* call have completed.

I also saw we have a small oddity in ReceiveAsync where it sets the current Message through the setter of that property, while the getter property unwraps potential MessageEnvelopes.

Imo, we should get rid of the setter and use the raw _message field instead as that is agnostic to raw or envelope wrapped messages.

**Comment by tomliversidge** [comment]
How about adding an UpdateState method onto the IPersistentActor interface, then just calling this:

https://github.com/AsynkronIT/protoactor-dotnet/compare/dev...tomliversidge:persistence_refactor?expand=1

Keeps it simple :)

**Comment by raskolnikoov** [comment]
I'll have a look at this in the weekend :)

**Comment by raskolnikoov** [comment]
Now we have two things to solve this issue https://github.com/AsynkronIT/protoactor-dotnet/pull/175
