### ISSUE TITLE
Generated grains don't handle DeadLetterResponse

### ISSUE THREAD

**Issue by michalnarwojsz** [AsynkronIT/protoactor-dotnet#1799]
Proto.Actor Version: 1.0.0-rc3.13
.NET 6

### Summary 
When request is sent to generated grain actor through ActorClient, `DeadLetterResponse` may be received. It is not handled well.

#### Expected behavior
In case of `DeadLetterResponse`, `default` (`null`) should be returned or `TimeoutException` thrown depending on legacy timeouts setting value, as well as other `DeadLetterResponse`'s effects should happen as in [code here](https://github.com/asynkron/protoactor-dotnet/blob/3ac947372b72bff9ada5f1bea1d7bcf3467f6698/src/Proto.Cluster/DefaultClusterContext.cs#L139).

#### Actual (wrong) behavior
`DeadLetterResponse` leaks to ActorClient, causing `NotSupportedException` thrown [here](https://github.com/asynkron/protoactor-dotnet/blob/c9ef833e97857883d57ca892f11c61b787ebb737/src/Proto.Cluster.CodeGen/Template.cs#L102).

### Details 
I think this happens because while generated client calls `_cluster.RequestAsync<object>`  [here](https://github.com/asynkron/protoactor-dotnet/blob/c9ef833e97857883d57ca892f11c61b787ebb737/src/Proto.Cluster.CodeGen/Template.cs#L89), received `DeadLetterResponse` , passes [this check](https://github.com/asynkron/protoactor-dotnet/blob/3ac947372b72bff9ada5f1bea1d7bcf3467f6698/src/Proto.Cluster/DefaultClusterContext.cs#L124) and is returned as `object` instead of being handled properly.

Possibly `DeadLetterResponse` handling could be moved up, [just after line 122 here](https://github.com/asynkron/protoactor-dotnet/blob/3ac947372b72bff9ada5f1bea1d7bcf3467f6698/src/Proto.Cluster/DefaultClusterContext.cs#L122)?

**Comment by marcinbudny** [comment]
Hey Michał, good catch and great analysis of the problem. I would also add that most probably the `DeadLetterResponse` handling code should not `break` out of the loop, but rather `continue` - virtual actors are supposed to always exist, so we expect that next iteration of the loop will just re-spawn the actor. 

Would you like to attempt a PR with a fix?

This path in the code is not exactly easy to unit test. Here's one idea on how to test this:

```csharp
    [Fact]
    public async Task ShouldRetryRequestOnDeadLetterResponseRegardlessOfResponseType()
    {
        await using var fixture = new Fixture(1);
        await fixture.InitializeAsync();

        var member = fixture.Members.First();
        var identity = CreateIdentity("slow-test");

        // make sure the actor is created and the PID is cached
        await member.RequestAsync<Pong>(identity, EchoActor.Kind, new Ping(), CancellationTokens.FromSeconds(1));

        // pretend we have an invalid PID in the cache
        var otherMember = await fixture.SpawnNode();
        if (member.PidCache.TryGet(ClusterIdentity.Create(identity, EchoActor.Kind), out var pid))
        {
            var newPid = PID.FromAddress(otherMember.System.Address, pid.Id);
            if (!member.PidCache.TryUpdate(ClusterIdentity.Create(identity, EchoActor.Kind), newPid, pid))
            {
                Assert.Fail("Failed to replace actor's pid with a fake one in the pid cache");
            }
        }
        else
        {
            Assert.Fail("Did not find expected actor identity in the pid cache");
        }

        // check if the correct response type is returned
        var response = await member.RequestAsync<object>(identity, EchoActor.Kind, new Ping(), CancellationTokens.FromSeconds(1));
        response.Should().BeOfType<Pong>();

    }

    private string CreateIdentity(string baseId) => $"{Guid.NewGuid().ToString("N").Substring(0, 6)}-{baseId}-";
    
    private class Fixture : BaseInMemoryClusterFixture
    {
        public Fixture(int clusterSize)
            : base(clusterSize, cc => cc
                .WithActorRequestTimeout(TimeSpan.FromSeconds(1))
            )
        {
        }
    }

```

**Comment by michalnarwojsz** [comment]
Hi, 

> Would you like to attempt a PR with a fix?

Yes, I'll prepare one soon
