### ISSUE TITLE
[Question] Given proto actor cluster runs in dynamic environment, would query to `ProcessRegistry.Get` slow down due lack of DEREGISTER HostResolver handlers?

### ISSUE THREAD

**Issue by mjaric** [AsynkronIT/protoactor-dotnet#1844]
I see that there is [RegsiterHostResolver](https://github.com/asynkron/protoactor-dotnet/blob/3d4168c33a41452aadbe21ffba12bd7487767b80/src/Proto.Actor/Process/ProcessRegistry.cs#L47) in ProcessRegistry, but no Deregister counterpart exists. Would this hurt a bit performance if cluster is run in dynamic environment where hostnames are dynamically generated due scaling dynamics, and cluster is running for some time (or in case of attempt to "hot-replace" release changes)?

**Comment by rogeralsing** [comment]
There is one HostResolver for the remote layer, and it is used for all remote lookups.
Meaning there is no need to deregister anything. it's the same resolver throughout the entire application's life.

Once the lookup is done, this value is cached inside the PID.

**Comment by mjaric** [comment]
That is per endpoint, right? 
If so, what would happen if endpoint is respawned with different hostname (scale up/down scenario)?

I'm not criticizing, just trying to understand code since I'm trying to make a port in rust language.

**Comment by rogeralsing** [comment]
No there is one EndpointManager for the whole actor system, which is what registers the HostResolver.
There can be many Endpoints managed by the EndpointManager, but there is still just one host resolver.

I would love to see the progress of a Rust version. there have been some requests for that  over the years

**Comment by mjaric** [comment]
I started recently, it is [here ](https://github.com/mjaric/protoactor-rs). There is not much, just draft modules.
