### ISSUE TITLE
Azure App Service Cluster Provider

### ISSUE THREAD

**Issue by sfmskywalker** [AsynkronIT/protoactor-dotnet#1845]
First of all. thank you for this wonderful project!

For [Elsa 3](https://github.com/elsa-workflows/elsa-core/tree/v3), we are using Proto.Actor as an option for the workflow runtime which works beautifully.

I am currently looking for a solution that allows us torun the Proto.Actor runtime implementation on Azure App Services and taking advantage of its ability to scale out into multiple nodes/instances.

It is my understanding that one would have to write a custom implementation of `IClusterProvider` to listen for changes (e.g. when instances are added or removed from the Azure app Service as it scales out or in).

If my understanding outlined above is correct, then I will get something started short-term, and if there's any interest, I will happily contribute the provider to this repo (or whatever repository is most appropriate for that).

If anyone has worked on this already and is willing to share, or if someone has any quick pointers to get going (for example, how to listen for Azure App Service scaling events from a .NET application), or anything else, that would be fantastic.

Last but not least, if anyone is interested in doing this as a paid project, please reach out to me directly at sipke@elsa-digital.com or sfmskywalker on Discord.

**Comment by marcinbudny** [comment]
Hi Spike,
The nodes in a cluster need to be individually addressable and you need to be able to establish gRPC connections between them. Is this possible with Azure App Service?

**Comment by sfmskywalker** [comment]
Hi Marcin,

Thank you for the info!
Frankly, I do not know if this is the case, but I will find out and come back with an update here.

**Comment by sfmskywalker** [comment]
@marcinbudny Question: assuming this is possible (addressable + gRPC supported), what might an implementation look li,e, do you have an idea? Understanding this might help me find the answer to these questions by creating a test application to do some tests from within.

**Comment by marcinbudny** [comment]
In essence, what cluster provider does is:
1. It registers current host as cluster node. E.g. with Consul this means adding a service entry to Consul. With K8S it means adding labels on the pod for other pods to detect new cluster node. With App Service - I'm not sure. Maybe you just assume all instances are cluster nodes.
2. It then monitors any changes - nodes entering and leaving cluster. It sends the updates (with proper address of the new nodes!) to `MemberList`. 
3. Cluster + Remoting make sure that connection is established to any new nodes entering the cluster. 
4. On shutdown, it deregisters current node.

Take a look at Consul implementation, it is rather straightforward and easy to reason about.

**Comment by rogeralsing** [comment]
IIRC. it is not possible to run clusters on AppServices due to various limitations.
e.g. one instance may not communicate with another instance of the same service.
And I believe AppServices also lack any public API to query the active nodes.

Azure Container Apps should be a better choice, and I know that MS Orleans have some demo for this.
We could probably copy-paste most of that.

**Comment by sfmskywalker** [comment]
Azure Container apps could be a great alternative to K8 and App Service. Will check the Orleans demo 👍🏻

**Comment by jupjohn** [comment]
I attempted to get this working a while back and also ran into the limitation of instance discovery - you're better off going the container route. Also, Azure App Services have only just received preview support for gRPC as of September (see [here](https://azure.microsoft.com/en-in/updates/public-preview-grpc-support-in-azure-app-service/)).

[Hangfire](https://www.hangfire.io/) for example centralizes its instance/host list in a cache (Redis, SQLServer etc.) alongside other operational data using a heartbeat-based system so maybe an approach like that could work? Definitely nicer to have instances talk to each other directly but Azure App Services are quite limited.

**Comment by sfmskywalker** [comment]
@rogeralsing Do you happen to know where to find the MS Orleans demo by any chance? We've been looking for it, but [we didn't get much further](https://github.com/elsa-workflows/elsa-core/issues/3418) than learning about their `IMembershipTable` abstraction and its various implementations.

@jammehcow Depending on our findings with Azure Container Apps, we might try and do a custom cluster provider that uses e.g. Redis as a central store and let each app instance register itself (assuming that's how it would work)

@marcinbudny Thanks for the clear step by step description, that's very helpful.

**Comment by gurkanguran** [comment]
Hi everyone,

I am currently implementing Azure Container Apps cluster provider by using the new sdk which is in preview. There is one issue I couldn't find a workaround yet. The issue is about registering the member as it is needed for Gossip Protocol. Please see this for the issue: https://github.com/microsoft/azure-container-apps/issues/521

I checked Orleans implementation but I couldn't quite understand it. They were using azure table storage to integrate azure container apps somehow. So I could not get an idea from their implementation as I'm using Azure Container Apps SDK. I don't know what kind of design Orleans is using but it doesn't look like gossip protocol from Proto.Actor.

Can you please check the issue I'm having in the GitHub link I provided and suggest a solution if you can think of any? Thanks!

**Comment by gurkanguran** [comment]
Solved the issue I mentioned by using the default environment variables of azure container app. There are plenty of environment variables including revision name and replica name in the running instance in azure container apps. You can use them to access the replica to update the tags which are needed by proto actor cluster provider interface.

**Comment by sfmskywalker** [comment]
@gurkanguran Great work!

@rogeralsing would you consider accepting a PR adding a cluster provider for Azure Container Apps?

**Comment by rogeralsing** [comment]
>@rogeralsing would you consider accepting a PR adding a cluster provider for Azure Container Apps?

Absolutely! 👍🏻

**Comment by sfmskywalker** [comment]
Looks like we can close this now that @gurkanguran 's PR is merged 🎉 
Thanks for the wonderful help everyone!
