### ISSUE TITLE
Persistence API - Support forward deleting of snapshots and events

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#187]
We currently support deletion of snapshots and events up to and including the passed-in index, i.e. "delete all snapshots (or events) up to and including index 6". Do we want to support the reverse of this, i.e. "delete all snapshots (or events) _since_ index 6"? Possible use case would be resetting the actor back to a previous state.

**Comment by cpx86** [comment]
This seems to relate to #188 no?

**Comment by tomliversidge** [comment]
@cpx86 yes that's true, if #188 is implemented you can achieve the goal of resetting back to a previous state, but you'll still have all the data in the db. I guess the main difference is that #188 is non-destructive, whereas this one would be.

**Comment by cpx86** [comment]
Right, this would permanently reset the actor.

I think if I were to use something like this in an application, I'd probably prefer to use a compensating transaction instead.

**Comment by tomliversidge** [comment]
I agree I think I'd do the same as you don't lose any history that way, I'm only suggesting this as there are already Delete methods on the API but they only allow up-to an event index

**Comment by tomliversidge** [comment]
Closing this as we can always reopen if anyone wants this functionality
