### ISSUE TITLE
Persistence API - Support replaying up to a certain event index and time

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#188]
We currently only support rebuilding the state of an actor to the latest version / index, but there are use cases (mainly debugging / testing) where it would be useful to be able to replay up to a certain point in time or a certain index. For example, if we want to replay until just before something happened (i.e. unexpected behavior of the system, bug, crash, "the system went down at 12:00" etc..) then apply some messages and observe what happens.

**Comment by ppXD** [comment]
`string code = "123";`
