### ISSUE TITLE
Persistence API - Support Snapshotting strategies

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#190]
The snapshotting of actor state is currently managed manually by calling PersistSnapshotAsync. We could support the concept of snapshot strategies that are automatically applied when an event is saved. Something like this (but a bit better): 

https://github.com/tomliversidge/protoactor-dotnet/blob/snapshot_strategies/src/Proto.Persistence/Persistence.cs

https://gist.github.com/tomliversidge/c4593b8e59890bf08c173bcd51e76b04

```

public async Task PersistEventAsync(object @event)
{
    Index++;
    await _state.PersistEventAsync(ActorId, Index, @event);
    _actor.UpdateState(new PersistedEvent(@event, Index));
    if (_snapshotStrategy.ShouldTakeSnapshot(Index))
    {
        await PersistSnapshotAsync(_actor.GetState());
    }
}
```

https://gist.github.com/tomliversidge/0258c5870cb1b663fe168e67db7b2087

```


    public interface ISnapshotStrategy
    {
        bool ShouldTakeSnapshot(long index);
    }

    public class EventsCountStrategy : ISnapshotStrategy
    {
        private readonly int _eventsPerSnapshot;

        public EventsCountStrategy(int eventsPerSnapshot)
        {
            _eventsPerSnapshot = eventsPerSnapshot;
        }

        public bool ShouldTakeSnapshot(long index)
        {
            return index % _eventsPerSnapshot == 0;
        }
    }

    public class NoSnapshots : ISnapshotStrategy {
        public bool ShouldTakeSnapshot(long index)
        {
            return false;
        }
    }

    public class TimeStrategy : ISnapshotStrategy
    {
        private readonly TimeSpan _interval;
        private readonly Func<DateTime> _getNow;
        private DateTime _lastTaken = DateTime.MinValue;

        public TimeStrategy(TimeSpan interval, Func<DateTime> getNow = null)
        {
            _interval = interval;
            _getNow = getNow ?? (() => DateTime.Now);
        }
        
        public bool ShouldTakeSnapshot(long index)
        {
            return _lastTaken.Add(_interval) >= _getNow();
        }
    }

```

**Comment by tomliversidge** [comment]
This can be implemented in the core Persistence API:
https://github.com/AsynkronIT/protoactor-dotnet/compare/dev...tomliversidge:add_snapshot_strategies?expand=1

Or as a contrib:

https://github.com/AsynkronIT/protoactor-dotnet/compare/dev...tomliversidge:snapshot_strategies_as_wrapper?expand=1

**Comment by cpx86** [comment]
I like the idea :) I think it's fine to include it as a feature of Persistence, since that's an opt-in module anyway.

**Comment by rogeralsing** [comment]
👍

**Comment by tomliversidge** [comment]
Ok i'll put in the PR!

**Comment by tomliversidge** [comment]
Closed by https://github.com/AsynkronIT/protoactor-dotnet/pull/206
