### ISSUE TITLE
Persistance API - Add option for only ever saving a single snapshot

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#192]
If one of the goals of the Persistence API is that you can use it without event sourcing i.e. in a traditional "just save current state" style, it would make sense to have an option to only ever save a single snapshot. Currently, it is linked to the event index and every save appends a new snapshot. If you're not using event sourcing, why have an event index? It should just be Save(someState);

This also comes back to other discussions around the Persistence API doing too much / should be split into separate contracts for event sourcing and non-event-sourcing.

**Comment by cpx86** [comment]
Is that something that Proto.Persistence needs to provide any help for though? I'm thinking if all you want to do is to save the latest state, that could be done with a regular repository where you call something like `_myState = repo.Get(ctx.Self.Id)` on the `Started` message, and `repo.Save(ctx.Self.Id, _myState)` when your state changes?

**Comment by tomliversidge** [comment]
@cpx86 isn't this one of the goals of Proto.Persistence? I was under the impression it was supposed to support _both_ traditional repository style "save current state" and event sourcing. If I've misunderstood this then yeah, this issue makes no sense :)

**Comment by rogeralsing** [comment]
IMO, Proto.Persistence should be eventsourcing + optional snapshotting.
But sure, if we can make the snapshotting work w/o the eventsourcing also, then why not(?)

**Comment by tomliversidge** [comment]
@rogeralsing I guess the "why not" argument is 
1. The term "snapshotting" is in my experience heavily associated with event sourcing - I've never heard it used when doing traditional repository style saving of current state, so it will probably confuse if people aren't using event sourcing
2. Trying to support both styles increases the API surface area, as people like me raise issues like this to change things to better support one style :) 

I think as it stands it works fine for ES + Snapshotting, and you can use it for current state only, just with a bit of a unfamiliar api.

I think we should focus on the use of eventsourcing + optional snapshotting for now

**Comment by raskolnikoov** [comment]
@tomliversidge @rogeralsing @cpx86 I use only snapshotting on some actors that dosent need event sourcing pattern. I've used this pattern on actors that do file imports so it will persist what state the import was at when stopped/crashed. So my vote is to support both event sourcing and only state snapshotting.

**Comment by tomliversidge** [comment]
What's your event index in this use case? Is it always 0?

**Comment by tomliversidge** [comment]
Going to close this issue as unless anyone else objects, I think it is working ok on this front - if just using snapshotting, the event index should always be 0

**Comment by raskolnikoov** [comment]
@tomliversidge yes it is always zero.
