### ISSUE TITLE
Cluster

### ISSUE THREAD

**Issue by Jesse1205** [AsynkronIT/protoactor-dotnet#193]
The ClusterHelloWorld example
when i restart the node1 , can not receive message from node2 like this

[REMOTING] Starting Proto.Actor server on 127.0.0.1:12000
[REMOTING] Started EndpointManager
Started PartitionActor HelloKind
Started MemberListActor
Cluster started
[REMOTING] Started EndpointWriter for address 127.0.0.1:13001
[REMOTING] EndpointWriter connecting to address 127.0.0.1:13001
[REMOTING] EndpointWriter connected to address 127.0.0.1:13001
[REMOTING] EndpointWriter lost connection to address 127.0.0.1:13001, reason Sta
tus(StatusCode=Unavailable, Detail="{"created":"@1492861722.540000000","descript
ion":"Endpoint read failed","file":"c:\jenkins\workspace\gRPC_build_artifacts\ar
chitecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\trans
port\chttp2\transport\chttp2_transport.c","file_line":1851,"grpc_status":14,"occ
urred_during_write":0,"referenced_errors":[{"created":"@1492861722.540000000","d
escription":"An existing connection was forcibly closed by the remote host.\r\n"
,"file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csh
arp\platform\windows\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line"
:176}]}")
[REMOTING] gRPC Failed to send to address 127.0.0.1:13001, reason Status(StatusC
ode=Unavailable, Detail="{"created":"@1492861722.540000000","description":"Endpo
int read failed","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\
x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2
\transport\chttp2_transport.c","file_line":1851,"grpc_status":14,"occurred_durin
g_write":0,"referenced_errors":[{"created":"@1492861722.540000000","description"
:"An existing connection was forcibly closed by the remote host.\r\n","file":"c:
\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platfor
m\windows\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":176}]}")

**Comment by rogeralsing** [comment]
1) Are you running Consul for the cluster service discovery?
2) Do you use any specific antivirus?

```
[REMOTING] EndpointWriter connected to address 127.0.0.1:13001
[REMOTING] EndpointWriter lost connection to address 127.0.0.1:13001, reason Sta
tus(StatusCode=Unavailable, 
```

Thisd section look strange to me, it looks like the node managed to connect to the other node, but then the connection was last for some reason.

**Comment by Jesse1205** [comment]
I have run the Consul service.
First time, i running the node1 like this, There is no problem.
```
[REMOTING] Starting Proto.Actor server on 127.0.0.1:13001
[REMOTING] Started EndpointManager
Started MemberListActor
Cluster started
[REMOTING] Started EndpointWriter for address 127.0.0.1:12000
[REMOTING] EndpointWriter connecting to address 127.0.0.1:12000
[REMOTING] EndpointWriter connected to address 127.0.0.1:12000
Hello from node 2
```
And then, I restart node1 ,The node2 throw exception 
```
[REMOTING] gRPC Failed to send to address 127.0.0.1:13001, reason Status(StatusC
ode=Unavailable, Detail="{"created":"@1492928176.903000000","description":"Endpo
int read failed","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\
x64\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2
\transport\chttp2_transport.c","file_line":1851,"grpc_status":14,"occurred_durin
g_write":0,"referenced_errors":[{"created":"@1492928176.903000000","description"
:"An existing connection was forcibly closed by the remote host.\r\n","file":"c:
\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platfor
m\windows\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":176}]}")
```

**Comment by rogeralsing** [comment]
Same as #251 
Fixed
