### ISSUE TITLE
Persistence API - Actor.Spawn can result in ID collisions

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#195]
As mentioned in #191, there is an issue with using the Id of the PID in persistence.  The ID needs to be something unique for each actor that survives restarts. It should also be unique across clusters. Currently I think we will see ID collisions when using Actor.Spawn with persistent actors.

**Example scenario 1:**

Node1 starts up, has a ProcessRegistry with starting sequence number of 0
Node2 starts up, has a ProcessRegistry with starting sequence number of 0

both nodes spawn a persistent actor and assign the same id = id collision.

**Example scenario 2:**

Single node, has a ProcessRegistry with starting sequence number of 0. Node spawns a persistent actor, saves to db. Node crashes and is restarted with ProcessRegistry having a starting sequence number of 0. New persistent actor is created and saved = id collision

I think this is only an issue when using Actor.Spawn, rather than Actor.SpawnNamed, as Actor.SpawnNamed passes the responsibility of id generation to the caller.

**Comment by rogeralsing** [comment]
Agree, this should however not be a problem if we enforce that we need to explicitly name the persistent actors as discussed in the #191

**Comment by tomliversidge** [comment]
Ideally enforce in code. :)

**Comment by tomliversidge** [comment]
Merge of #200 passes responsibly of managing ids to callers of persistence api
