### ISSUE TITLE
Mailbox does not use the configured IDispatcher

### ISSUE THREAD

**Issue by pcroc** [AsynkronIT/protoactor-dotnet#1952]
We have unit and integration tests which rely on the `SynchronousDispatcher` so that the test can reliably check conditions - send a message to an actor, then immedately check the expected result in the test (message posted to a queue, etc.).

Since upgrading from Proto.Actor 0.26.0 to newer versions, this no longer works. Messages are being processed on a different thread, and the control returns to the test code immediately. This means we would have to resort to passing around synchronization objects in order for tests to know that the message has been processed, and makes the use of SynchronousDispatcher pointless.

Doing some digging, I found the following change, which looks suspicious (though I am not familiar with the code base): https://github.com/asynkron/protoactor-dotnet/pull/1317/files#diff-d36bc05c95e9f9702afb7b34952ff3a36e6d074bf2985ed751270ef2704a13f0

As far as I can tell, the `Mailbox` class no longer makes use of the `IDispatcher.Schedule` method at all; only the `Throughput` property is ever used.

Contrast with `BatchingMailbox` which does use `IDispatcher.Schedule`: https://github.com/asynkron/protoactor-dotnet/blob/dev/src/Proto.Actor/Mailbox/BatchingMailbox.cs#L114

**Comment by rogeralsing** [comment]
Thank you for reporting this.
you are indeed correct. at some point, some local performance optimization test code got into the main repo.
This have now been resolved in #1955
