### ISSUE TITLE
Supervision does not get triggered if child actor throws in Started message

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#196]
If a child actor throws when receiving the `Started` message, the parent will not get notified.
I assume that there is something missing in that sequence, e.g. that the parent is not yet set or something.

**Comment by tomliversidge** [comment]
Is it because the exception is swallowed? https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Actor/LocalContext.cs#L236

**Comment by cpx86** [comment]
@rogeralsing Is there any reason why we have that catch? Wouldn't the parent always want to get notified on failed system messages, so they can be retried?

**Comment by rogeralsing** [comment]
Well spotted, agree we can get rid of the try catch there, ofc failing system messages should also be escalated to parent.

**Comment by tomliversidge** [comment]
I modified the existing supervisor tests to throw an exception when the started message is received (after cahnging the code above to rethrow the exception) and 2/4 of them failed... i think it was restart and possibly escalate strategies. It was pretty difficult to debug but i think the flow was correctly sending a restart message, but then inside the processing of that it was throwing another exception, as another started message must have been processed and this then resulted in a failed task for processing the restart message... but then my kids, partner and mother came in and that was the end of that!
