### ISSUE TITLE
Port all supervisor strategies from Go to C#

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#197]
AllForOne and ExponentialBackoff supervisor strategies needs to be ported over.

**Comment by edblackburn** [comment]
Do you think you'll take a dependency on Polly? Or will you write your own? If the later is there scope for injecting the policy as a delegate?

**Comment by rogeralsing** [comment]
We can probably have some contrib/extension package for Polly, but I would like to avoid it out of the box. 
The default supervision strategies are simple enough to just implement directly. 10-20 lines each.

**Comment by tomliversidge** [comment]
Does it matter if we just use milliseconds for the c# version rather than nanoseconds in the ExponentialBackoff strategy?

```
public async void HandleFailure(ISupervisor supervisor, PID child, RestartStatistics rs, Exception reason)
        {
            SetFailureCount(rs);
            var backoff = rs.FailureCount * _initialBackoff.TotalMilliseconds;
            var noise = _random.Next(500);
            var duration = TimeSpan.FromMilliseconds(backoff + noise);
            await Task.Delay(duration);
            supervisor.RestartChildren(child);
        }
```

or would you prefer to convert to Nanoseconds?

**Comment by tomliversidge** [comment]
Also, if I use Task.Delay(duration).Wait() it is blocking, do we want HandleFailure to be async?

**Comment by adamhathcock** [comment]
Yes.  Thanks a big sin to commit right there.

**Comment by tomliversidge** [comment]
Yeah that's what I though, but it's going to have a ripple effect as HandleFailure isn't currently awaited

**Comment by adamhathcock** [comment]
Async all the things!

**Comment by adamhathcock** [comment]
I can give it a go to async it.  Will have to be tomorrow as it's a U.K. Holiday today

**Comment by adamhathcock** [comment]
I gave it a go to make that code path be async.

**Comment by rogeralsing** [comment]
In Go ExponentialBackoff:

```go
func (strategy *exponentialBackoffStrategy) HandleFailure(supervisor Supervisor, child *PID, rs *RestartStatistics, reason interface{}, message interface{}) {
	strategy.setFailureCount(rs)

	backoff := rs.FailureCount * int(strategy.initialBackoff.Nanoseconds())
	noise := rand.Intn(500)
	dur := time.Duration(backoff + noise)
	time.AfterFunc(dur, func() {
		supervisor.RestartChildren(child)
	})
}
```

the `time.AfterFunc` would translate to `Task.Delay(...).ContinueWith(...)`
meaning, it doesnt have to be awaited by the parent actor, the process is still asynchronous but not awaited.

one child actor can only have one active failure at any given time, so there is no risk of race conditions

**Comment by adamhathcock** [comment]
Oh I see.  Yes, we don't need https://github.com/AsynkronIT/protoactor-dotnet/pull/209

It's an async timer that shouldn't be awaited.

**Comment by tomliversidge** [comment]
Ah ok, my bad sorry for the confusion!!
