### ISSUE TITLE
Give CTOR access to context

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#201]
In some cases, it might be good to have access to the context already in the CTOR of the actor.

I'm thinking it would be possible with something like this:

```csharp
var props = Actor.FromProducer(ctx => new MyActor("hello", ctx));
...
class MyActor
{
    private string _id;
    public MyActor(string someArg, IConstructContext ctx)
    {
          //Self, Parent and a few other things could be available upon creation
          _id = ctx.Self.Id; 
    }
}
```

I'm not sure if this is a good idea and if it promotes doing more than you should in the ctor.
But it would be possible technically by adding a new overload on FromProducer and introduce the constructor context.

**Comment by adamhathcock** [comment]
Not sure this is a good idea.  What info would you need that shouldn't be deferred and accessed in the start message?
