### ISSUE TITLE
Subscribe to EventStream with Channel

### ISSUE THREAD

**Issue by casper91** [AsynkronIT/protoactor-dotnet#2100]
Hi,

Looking at the code for Subscribe with a channel.

https://github.com/asynkron/protoactor-dotnet/blob/c721e272ac20458ea720378562710f0f8abce077/src/Proto.Actor/EventStream/EventStream.cs#L110

Is there any particular reason why it doesn't have an equivalent for specifying `TMsg` e.g.

`public EventStreamSubscription<T> Subscribe<TMsg>(Channel<TMsg> channel, IDispatcher? dispatcher = null) where TMsg : T`

**Comment by rogeralsing** [comment]
Hi @casper91, I´m probably misunderstanding but what would the difference be here?
the current implementation already matches sub-types via the `is` operator. 
So what would this proposed overload do additionally?

**Comment by casper91** [comment]
Hi @rogeralsing,
It could be my usage or understanding that is wrong here.
But if I would do the following:
```C#
var channel = Channel.CreateUnbound<Something>();
EventStream.Subscribe(channel);
```
Then that would yield an compile error. If I however do:
```C#
var channel = Channel.CreateUnbound<object>();
EventStream.Subscribe(channel);
```
Then it will compile.

To my understanding, using `object`, then I will receive all published messages on the event stream even though I might only be interested in `SomeType`?

Take for example the Subscribe with Actions, here there are two variants, the one getting [all messages](https://github.com/asynkron/protoactor-dotnet/blob/dev/src/Proto.Actor/EventStream/EventStream.cs#L86) and the one where you [specify the type](https://github.com/asynkron/protoactor-dotnet/blob/dev/src/Proto.Actor/EventStream/EventStream.cs#L143) and the channel is missing the opportunity to only receiving messages of a specific type.
I know I could filter them out after, but since the other (e.g. actions) have both possibilities I thought that it might be something missing for the channel?

I hope this clarifies a bit.

**Comment by rogeralsing** [comment]
Got it, I´m working on it now.
The main issue is that the eventstream in the actorsystem itself is just `object` as there can be any type of messages flowing there.
I´m using your suggestion now and applying the filter for the publish based on the channel generic type.

**Comment by rogeralsing** [comment]
https://github.com/asynkron/protoactor-dotnet/compare/eventstream-channels?expand=1

**Comment by casper91** [comment]
That looks great, thanks for the quick response!
One suggestion is to change `TC` -> `TMsg` just for consistency with the other methods.

**Comment by rogeralsing** [comment]
Published new preview to Nuget, closing
