### ISSUE TITLE
Implement non-blocking bounded mailbox

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#215]
An important factor in a high load system is the ability to shed load.
Akka has the concept of a bounded mailbox that drops new messages if the queue is full.
We should have the same, and allow dropping at both the tail and the head depending on use-case.

This will allow systems to drop messages if the actor cannot keep up with the load from whom ever is producing messages.
it's better to drop messages than to crash completely.

**Comment by tomliversidge** [comment]
First pass merged in https://github.com/AsynkronIT/protoactor-dotnet/pull/216

**Comment by rogeralsing** [comment]
System.Threading.Channel would make a perfect candidate for this as it already supports this semantics.

**Comment by rogeralsing** [comment]
Done
