### ISSUE TITLE
EndpointWriterMailbox should use a bounded mailbox for user messages

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#23]
EndpointWriterMailbox should use a big bounded mailbox for user messages.
This is what we do in Go, in C# we still use a concurrent queue here.

As there will not be a lot of endpoint writers, it's ok to have a bigger queue.

**Comment by cpx86** [comment]
Does it really? It seems to use AsynkronIT/goring which doesn't look bounded (it auto-expands when full)
https://github.com/AsynkronIT/protoactor-go/blob/dev/remote/endpoint_writer_mailbox.go#L111
https://github.com/AsynkronIT/goring/blob/master/queue.go#L39

**Comment by rogeralsing** [comment]
You are right, but it does pre allocate a fairly large initial ring. So it mostly has the zero alloc behavior of a bounded queue, which is fast.

**Comment by cpx86** [comment]
The reason I pointed it out is that it the issues with the MPMCQueue seem to occur when the buffer size is smaller than the number of messages sent. So maybe we should use a resizable queue here as well?

**Comment by rogeralsing** [comment]
Yes.
Porting the goring to C# might work.
But I would suspect that it's more sensitive to contention in .NET where a lock is an actual lock.
It Go this doesn't hog a thread indefinitely.

**Comment by rogeralsing** [comment]
Closing, the perf in C# Proto.Remote is great, no need to change anything
