### ISSUE TITLE
Using Shouldy for tests

### ISSUE THREAD

**Issue by ArturKarbone** [AsynkronIT/protoactor-dotnet#230]
Hey Guys, have you considered using [Shoudly](https://github.com/shouldly/shouldly) for assert part of the tests ?

A concrete example from https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/tests/Proto.Actor.Tests/PIDTests.cs

```
 [Fact]
        public void Given_ActorNotDead_Ref_ShouldReturnIt()
        {
            var pid = Actor.Spawn(Actor.FromFunc(EmptyReceive));

            var p = pid.Ref;

            Assert.NotNull(p);
        }
```

Might look:

```
 [Fact]
        public void Given_ActorNotDead_Ref_ShouldReturnIt()
        {
            Actor
		.Spawn(Actor.FromFunc(EmptyReceive))
		.Ref
		.ShouldNotBeNull();	

        }
```

I can contribute.

Thanks

**Comment by cpx86** [comment]
A better assertion library would definitely be nice.

What about FluentAssertions? I've never used Shouldly so I'm not sure how they compare.

**Comment by tomliversidge** [comment]
I'm not familiar with Shoudly, but looking at their docs i love the error messages it gives, so I'd like to see more examples of this - maybe half an hour spent translating some tests might serve as a good example of what it would look like?

**Comment by cpx86** [comment]
:+1: - let's do some comparison with FluentAssertions as well, I'm curious to see the difference.

**Comment by raskolnikoov** [comment]
I agree, some more examples would be nice to see. Looks more beautiful than regular assertions. :)

**Comment by cpx86** [comment]
Did a quick stab using FluentAssertion for `ActorTests` - diff here: https://github.com/AsynkronIT/protoactor-dotnet/commit/692d4601dbf5a7cc318203105581371e766c43ef

**Comment by rogeralsing** [comment]
Looks good, 
Seems like ActorClient got hidden though
```
Program.cs(49,24): error CS0122: 'ActorClient' is inaccessible due to its protection level [C:\projects\protoactor-dotnet\examples\Middleware\Middleware.csproj]
Program.cs(67,14): error CS0122: 'ActorClient.Tell(PID, object)' is inaccessible due to its protection level [C:\projects\protoactor-dotnet\examples\Middleware\Middleware.csproj]
```

**Comment by cpx86** [comment]
Ah, that's part of #233 though :) Not sure if ActorClient should be public or not TBH - let's discuss in that PR.

**Comment by rogeralsing** [comment]
I wonder why my PR comment ended up here.. might have had two tabs open :)

**Comment by tomliversidge** [comment]
Here's an example of the actor lifecycle test using shouldly:

```
[Fact]
        public void ActorLifeCycle()
        {
            var messages = new Queue<object>();

            var pid = Actor.Spawn(
                Actor
                    .FromFunc(ctx =>
                    {
                        messages.Enqueue(ctx.Message);
                        return Actor.Done;
                    })
                    .WithMailbox(() => new TestMailbox())
                );

            pid.Tell("hello");
            pid.Stop();
            messages.Count.ShouldBe(4);
            messages.ShouldBe(new object[]
            {
                Started.Instance,
                "hellos",
                Stopping.Instance,
                Stopped.Instance
            });
           
        }
```

and the error message (notice the highlighted item in the array that is different):

```
Proto.Tests.ActorTests.ActorLifeCycle

Shouldly.ShouldAssertException : [Proto.Started (14421545), "hello", Proto.Stopping (35567111), Proto.Stopped (65066874)]
    should be
[Proto.Started (14421545), "hellos", Proto.Stopping (35567111), Proto.Stopped (65066874)]
    but was not
    difference
[Proto.Started (14421545), *"hello"*, Proto.Stopping (35567111), Proto.Stopped (65066874)]
   at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](IEnumerable`1 actual, IEnumerable`1 expected, Boolean ignoreOrder, Func`1 customMessage)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](IEnumerable`1 actual, IEnumerable`1 expected, Boolean ignoreOrder)
   at Proto.Tests.ActorTests.ActorLifeCycle()
```

Using FluentAssertions gives an error like this:

```
Proto.Tests.ActorTests.ActorLifeCycle

Expected item[3] to be Proto.Stopped, but found System.String

With configuration:
- Use declared types and members
- Compare enums by value
- Match member by name (or throw)
- Be strict about the order of items in byte arrays

   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context)
   at Proto.Tests.ActorTests.ActorLifeCycle()
```

which looks like the ordering in the array is wrong.

**Comment by cpx86** [comment]
Shouldly does seem to have nicer messages! 👍

**Comment by raskolnikoov** [comment]
Yes I agree!

**Comment by tomliversidge** [comment]
😮 

<img width="929" alt="screen shot 2017-06-12 at 22 39 33" src="https://user-images.githubusercontent.com/1437372/27051857-56ed7516-4fc0-11e7-8b61-1d77d50e0b0d.png">

**Comment by tomliversidge** [comment]
I'm not actually seeing the error messages as described in the shouldly documentation. For example:

```
someVariable = 9;
someVariable.ShouldBe(10)
```

should give the error message "someVariable should be 10 but was 9", but i see "9 should be 10 but was not"...

**Comment by rogeralsing** [comment]
There is no way any library could extract that naming information w/o using e.g. Linq Expressions.
I'm guessing their docs are incorrect. unless the code is wrapped in a expression lambda

**Comment by tomliversidge** [comment]
Supposed to use the debug pdb file somehow to get the info

**Comment by cpx86** [comment]
Maybe doesn't work with .NET standard pdbs?

**Comment by cpx86** [comment]
In any case, I don't think it's super important though. If you need the variable name in the output, maybe you have too many variables in your test ;)

**Comment by adamhathcock** [comment]
Shouldly says:
```
Shouldly uses the source code to make its error messages better. Hence, on the build server you will need to have the "full" pdb files available where the tests are being run.

What is meant by "full" is that when you set up your "release" configuration in Visual Studio and you go to Project Properties > Build > Advanced > Debug, you should set it to "full" rather than "pdb-only".
```

In project.json, you could choose "full" vs "portable" pdbs.  Not sure how to do that in csproj.  Full was windows only.  Portable is xplat.  I guess Shouldly only supports windows for that now.

I think the tooling for reading xplat pdbs might be immature.
