### ISSUE TITLE
Make Tell async?

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#236]
Tell is currently synchronous and blocking, this is not an issue for now as we always just pass messages onto a mailbox.

But as we have been discussing integrating other technologies, not only actors, it might make sense to actually be able to await the Tell.
e.g. if we send messages to Kafka or SignalR, then you probably want to be able to wait until the message have actually been placed on the underlying infrastructure.

This would not have any major effect on performance of the default path as that would simply return a completed Task.
There will ofc be the overhead of returning that pointer instead of void, but that would be it.

cc @AsynkronIT/developers

**Comment by rogeralsing** [comment]
Related:

Also, should we rename Tell to Send?

This is a much more common convention. Dataflow uses it, Elixir uses it, most MQ SDK's uses it.
Tell is very Akka specific.

**Comment by tomliversidge** [comment]
I guess there are arguments for and against - sticking with it makes it more familiar to Akka users, but less familiar to non-Akka users.

I'd vote for Send as like you say it is more common overall and given that we have Receive methods would fit better with those too

**Comment by adamhathcock** [comment]
+1 for naming it Send and making it async even though it doesn't need to be.  I like the consistency.

**Comment by raskolnikoov** [comment]
I vote for change to Send. Is it a bad idea to have a Send and SendAsync method for sync/async operations?

**Comment by adamhathcock** [comment]
I personally don't like *Async methods unless the API already had sync versions.  Just have one Send and make it async

**Comment by cpx86** [comment]
+1 for Send. As for the Async suffix, I'm not sure. Suffixing seems to be pretty standard so it could make sense to stick to it to not surprise the user

**Comment by adamhathcock** [comment]
if the entire API is async, then you would put suffix it all?  I don't think async suffix is standard.  Especially for new async-only APIs.

**Comment by cpx86** [comment]
SO has a good answer here from Stephen Toub who worked on TPL :) https://stackoverflow.com/questions/15951774/does-the-use-of-the-async-suffix-in-a-method-name-depend-on-whether-the-async

**Comment by adamhathcock** [comment]
¯\_(ツ)_/¯

I guess it should be used to make it easy to distinguish I guess but I still hate it :p

**Comment by tomliversidge** [comment]
Yeah probably go with Async suffix as does make it super obvious.

**Comment by jeffdoolittle** [comment]
I'm with @adamhathcock. This isn't a Microsoft internal project so I don't think it should be a foregone conclusion to follow their naming convention. But also not a hill to die on. :)

**Comment by jrouaix** [comment]
same here, for the guys who knows it's a pain to write Async, but for the reader and newcomers, it's a relief to be that clear.

**Comment by cpx86** [comment]
Since only some methods on PID and IContext make sense to have async, I think we should suffix those to make it clear which are and aren't.

**Comment by adamhathcock** [comment]
I'm working on this.  I'm making IDispatcher's schedule be async to know that you know the message was dispatched.

**Comment by cpx86** [comment]
I'm not sure if it helps to have the dispatcher async as well. If the mailbox is already processing, then it won't be called so awaiting Tell wouldn't guarantee the message is dispatched. I think it's enough to ensure that the message has been successfully processed by the process. In case of actors that means posted to the mailbox, in the case of e.g. a Kafka producer process it means successfully sent to the target topic.

**Comment by adamhathcock** [comment]
The dispatcher being async does what you describe, no?  Otherwise, the sender has no idea when the message gets dispatched correctly.  I figured this would be required.

Basically, I'm just doing this now:

```csharp
        public async Task ScheduleAsync(Func<Task> runner)
        {
            //await the first Task to ensure dispatching happened.  Awaiting the second means blocking until the action happened.
            await Task.Factory.StartNew(runner, CancellationToken.None, TaskCreationOptions.None, _scheduler);
        }
```

if I did a double await then it would be bad.

@rogeralsing would have to say if not awaiting altogether was done for perf or something.

**Comment by cpx86** [comment]
I would say it's partially for perf, partially because it doesn't make any difference. The sender can't wait for the message to get dispatched anyway, because if the mailbox is already running, it will return immediately without scheduling the dispatcher.

**Comment by rogeralsing** [comment]
If we go for async Tell, then I'd say that it should only wait for the message to be placed on the mailbox.
Which wouldn't need any async support in the current form, it would just be returning a completed task.

If we add support for Kafka/Rabbit processes, then the await could await for the message to be stored on the queue/topic.

**Comment by cpx86** [comment]
That would be consistent - we don't guarantee that the message was processed, only that it was successfully sent to it's destination.

**Comment by adamhathcock** [comment]
Understood.  I should get a pull request open this evening as I have a lot of nothing else to do once the kids are asleep.
