### ISSUE TITLE
Better Protogen user experience

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#237]
Protobuf and Protoc are notoriously hard to set up, use and debug.
Therefore I have ported the C# cluster grain generator from Go + protoc to @mgravell's Protogen(WIP)

The current code can be found here https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/src/ProtoGenerator

This would open up for VS.NET or dotnet CLI integration and most importantly, it could be an opening for a decent F# API.

We could potentially generate F# DU/Record types with this approach.

Related to #217

**Comment by adamhathcock** [comment]
We'd make a dotnet CLI command to generate the proto files as a build step?

**Comment by mgravell** [comment]
(I don't mean to jump in, but... github pinged me)

A lot of that we're still figuring out - or at least I am, @rogeralsing  may well know more about those things. But if I were to put together a wishlist spec sheet together for *what I want* (which is probably pretty similar to what is wanted for protoactor), it would be:

- must be "installed" via nuget (installed isn't really the right word)
- must work inside the more restrictive "dotnet restore" style nuget sandbox
- must be *some mechanism* to generate without the IDE - could be msbuild, could be dotnet cli
- must work xplat; same process should work on linux, mac, windows, etc
- may have optional IDE features (whether some kind of custom task, analyzer, whatever)
- should have mechanism to build entirely inside IDE (which may or may not be as simple as running the build)

I don't know how many of those "must"s are technically impossible; my plan is to finish shipping 2.3.0 (which will include protogen 0.something), then focus on it.

**Comment by adamhathcock** [comment]
A dotnet cli tool covers a lot of that.  I guess I'll wait to see what you come up with :)

**Comment by raskolnikoov** [comment]
#249 work started here

**Comment by rogeralsing** [comment]
We should extend the template used to allow for passing cancellation tokens, and also allow for retries if no response is received.

**Comment by rogeralsing** [comment]
Closing this one as we do have a .NET based generator now
