### ISSUE TITLE
ProtoGenerator dosen't compile

### ISSUE THREAD

**Issue by raskolnikoov** [AsynkronIT/protoactor-dotnet#245]
Can't compile ProtoGenerator located here: https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/tools/ProtoGenerator

Missing references to project "protogen\protogen.csproj".

Or is this the generator to use for c#?

https://github.com/AsynkronIT/protoactor-go/tree/dev/protobuf/protoc-gen-csgrain

**Comment by raskolnikoov** [comment]
ping @rogeralsing @cpx86

**Comment by rogeralsing** [comment]
https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/protobuf/ProtoGrainGenerator

The generator now compiles and can generate the correct output.
We do however have to make the console app accept filenames as input, and write the generated files to disk.

Up-for-grabs for anyone who want to do some CLI coding

**Comment by raskolnikoov** [comment]
added input & output args to use with fixed generetor #249
