### ISSUE TITLE
Port the MessageInvoker EscalateFailure

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#25]
In Go we have switched from catching exceptions per message, to catching per mailbox run and invoke the `MessageInvoker.EscalateFailure` from there.

This means that the mailbox must keep track of the current message, be it system or user msg.

**Comment by cpx86** [comment]
What is missing for this to be done?

**Comment by rogeralsing** [comment]
This one is completed, thanks for the heads up, closing
