### ISSUE TITLE
Add CancelReceiveTimeout method to IContext

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#253]
The way you cancel at the moment is SetReceiveTimeout(TimeSpan.MinValue) which isn't easily descovered (you have to read the method description) 

Let's make it explicit?

**Comment by rogeralsing** [comment]
Im all for this.

**Comment by tomliversidge** [comment]
Also, as far as I can tell, setting the timeout value to TimeSpan.Zero doesn't actually stop the timer. The code does this:

```
 if (duration < TimeSpan.FromMilliseconds(1))
            {
                duration = TimeSpan.FromMilliseconds(1);
            }
```

so it will set the duration to 1 millisecond.... then reset the timer to be 1 millisecond:

```
ReceiveTimeout = duration;
            if (ReceiveTimeout > TimeSpan.Zero)
            {
                if (_receiveTimeoutTimer == null)
                {
                    _receiveTimeoutTimer = new Timer(ReceiveTimeoutCallback, null, ReceiveTimeout, ReceiveTimeout);
                }
                else
                {
                    ResetReceiveTimeout();
                }
            }
```

**Comment by rogeralsing** [comment]
You are correct, I had a look at the current code and it is worng as it rounds the duration up to non zero before trying to to reset

**Comment by cpx86** [comment]
I'm about to start porting this to protoactor-js, so while we're at it, any other changes we'd like to do? :)
