### ISSUE TITLE
There is no way to respond to Actor which is behind a NAT

### ISSUE THREAD

**Issue by pablos44** [AsynkronIT/protoactor-dotnet#254]
The problem arises especially when I need to respond to Sender PID.  
As far as I see both endpoints needs to be servers to communicate (two channels established). Is it possible to do bi-directional messaging through single channel? (In that case having a client behind a NAT is not a problem)

**Comment by rogeralsing** [comment]
@pablos44 using a single channel would be technically possible, but is not supported in ProtoActor right now. the way the endpoint readers and writers would have to be redesigned in order to make this work.

But it is a totally fair question and solution. so we will look into it

**Comment by cpx86** [comment]
Using `host:port` probably isn't a good solution for many cases. You could have multiple remote processes that are bound to a standard address locally and don't know what their external address is, meaning it's impossible to know which gRPC channel to use when responding to the sender PID.

Might it be possible to somehow instead associate each remote process with a UUID, combined with an initial handshake on connection? I'm thinking something along the lines of this:

1. When A and B start, each generates a UUID that will be used as address in the sender PID of outgoing messages
1. A connects to B and sends it's UUID
1. B associates the UUID with the channel and replies with it's UUID
1. A associates the UUID with the channel and the handshake is complete
1. Whenever a message is sent, the UUID is contained in PID.Address so the receiver knows which channel to use when sending a response back to the sender

I'm sure there are flaws with the above sketch, but thoughts? :)

**Comment by rogeralsing** [comment]
@cpx86 the issue is when you would pass such pid to yet another system, that system would have to know what that means.

**Comment by cpx86** [comment]
What if we turn the problem around instead? A part of the problem in this case is that a remote system doesn't know what it's external address is. What if we added an option to set a "from" address when configuring the remote system? So a system might _bind_ to e.g. `0.0.0.0:12345` but the _PID address_ might instead be `remote-sys-a.mydomain.com:80`. That would at least solve the cases when you know what external address each system should have. It also would apply not just to NATing but to any situation where you want to expose your remote system to another network (internal NAT, public firewall, reverse proxy, etc).

**Comment by rogeralsing** [comment]
This is what Akka/AkkaNET does. it has a "public" address.
But it doesn't really solve the problem with location transparency.
e.g. if my machine connects to a remote server, and your machine does the same.
that doesn't mean that yours and mind could also communicate p2p. 

But yes, we could separate the host/port from what is bound on the network.
That would at least solve part of the issue at hand

**Comment by cpx86** [comment]
> But it doesn't really solve the problem with location transparency.
e.g. if my machine connects to a remote server, and your machine does the same.
that doesn't mean that yours and mind could also communicate p2p.

If our machines are on networks that can connect to each other then... yes it does? If our networks can't connect there's no way around it :) This is basically how BitTorrent solves P2P for clients behind a NAT. You configure port forwarding on the router and change the advertised address on the client to match it.

**Comment by rogeralsing** [comment]
>If our machines are on networks that can connect to each other then... yes it does? 

Yes, but if they are different clients or IoT devices randomly on the internet. then no.
So what I'm trying to say is that taking a concept built for p2p meshes, and apply it to a strict client server topology should maybe be a different kind of connection, to make that more explicit what can and cannot be done.

**Comment by cpx86** [comment]
Yes if we're talking about mesh networks then it's quite different from traditional P2P :) And we'd need some different way of connecting nodes (my limited understanding of mesh networks is that they don't necessarily even run on IP)

**Comment by rogeralsing** [comment]
cc @pablos44 , @cpx86 fixed this in #258 . so you can make your system announce different host/port than it listens to
