### ISSUE TITLE
when a remote node disconnected, the endpointwriter of it will be leak. this may increase gc time.

### ISSUE THREAD

**Issue by Jesse1205** [AsynkronIT/protoactor-dotnet#256]

**Comment by rogeralsing** [comment]
Can you elaborate on this?
This seems to be a copy of https://github.com/AsynkronIT/protoactor-go/issues/134

What exactly do you mean by leak in this case?

**Comment by cpx86** [comment]
How do we dispose the endpoint (writer+watcher) if a remote system shuts down? E.g. system A sends a message to B, then shuts down - how does B know that it should dispose of the endpoint? I can't find any code that explicitly handles this.

**Comment by Jesse1205** [comment]
yes，i copy from this , good job
