### ISSUE TITLE
Reason for netstandard 1.5?

### ISSUE THREAD

**Issue by wind-rider** [AsynkronIT/protoactor-dotnet#265]
I see that Proto.Actor can be used in projects that support netstandard1.5 and higher. This makes it incompatible with UWP and therefore with Background Apps on Windows IoT Core.

Could it be retargeted to netstandard 1.4? This would make it compatible with UWP.

**Comment by rogeralsing** [comment]
We use gRPC as the base network transport. gRPC is released on netstandard 1.5
Hopefully this whole netstandard versioning problems clear up when 2.0 is released.

**Comment by wind-rider** [comment]
ok, thank you for the explanation

**Comment by tomliversidge** [comment]
Also, we could target lower versions of netstandard for certain projects - when i looked into this i think we could go down to 1.3 on a few of them (i.e. Proto.Actor and Proto.Mailbox if i recall correctly) which would increase availability if you dont intend to use something like remoting

**Comment by tomliversidge** [comment]
There's more info here: https://github.com/AsynkronIT/protoactor-dotnet/issues/223
