### ISSUE TITLE
Multiple grains picking up a message? (publish - subscribe model?)

### ISSUE THREAD

**Issue by wind-rider** [AsynkronIT/protoactor-dotnet#267]
Does proto.actor support a publish / subscription model, where multiple grains can "pick up" a task?

Say, a request for a new account is published somewhere to the cluster, can e.g. a logger, and a account creation grain pick up that request in parallel by themselves (kind of publish - subscribe model)? Or does the sender of the request need to specifically tell the cluster to do that with two calls to the two types of grains?

**Comment by rogeralsing** [comment]
There is no such support (currently) in Proto.Actor.
What you could do however is to have a grain as the entry point of the message and then from that grain publish the message to some form of subscribers.
e.g. the grain could have a list of PID's to publish to

**Comment by rogeralsing** [comment]
See #325
