### ISSUE TITLE
Remote: Port 0 solution does not work anymore?

### ISSUE THREAD

**Issue by maiorfi** [AsynkronIT/protoactor-dotnet#268]
Currently, running Chat example shows that "port 0" solution doesn't work as expected (I'm working on dev branch), i.e. whenever I specify a non-zero port in Client code I succeed in receiving (broacasted) server responses, but of course I can only connect a single client, while if I do a

> Remote.Start("127.0.0.1",0)

client never gets any response (despite its requests are correctly received by server).

**Comment by rogeralsing** [comment]
My guess is that it is a regression from the NAT Announce Host/Port change as this was working a few days ago

**Comment by rogeralsing** [comment]
Found and fixed.

**Comment by rogeralsing** [comment]
This line had the error 
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Remote/Remote.cs#L61

it made the addr use `port` which is 0 , making it impossible for remote systems to call back

**Comment by maiorfi** [comment]
👌
