### ISSUE TITLE
Cluster TODOs

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#270]
* Do we need a grain generator for non protobuf scenarios?
* Can we get the protobuf grain generator to be a build step in VS.NET?
* Passivisation of grains, should grains always stop on idle after some time?
* Retries on grain calls. if a grain call fails, should we auto retry or leave this to the user?
* Tests, tests and more tests
* Persistence, is there any sane way to connect Proto.Persistence with grains or should grains have their own persistence?

Done:
* Create a hashing formula that is consistent with Go, we can change either side or both, but they need to result in the same values

**Comment by alexeyzimarev** [comment]
Btw I want convert the grains generator to a dotnet cli tool. Should also be possible to wrap it both in a build-time reference. MinVer does that, should be easy to do.

**Comment by rogeralsing** [comment]
that would be fantastic, does that mean that it also can be generated like the proto generation on save/build?

**Comment by alexeyzimarev** [comment]
On build yes, not sure about on save.

**Comment by alexeyzimarev** [comment]
The point here just with proto source generation is not to have generated files in the repository. Generated files are placed to the obj directory and get references from there.

**Comment by rogeralsing** [comment]
Closing, let's open separate issues for each part
