### ISSUE TITLE
Use Liblog instead of Logging.Extensions directly 

### ISSUE THREAD

**Issue by adamhathcock** [AsynkronIT/protoactor-dotnet#277]
https://github.com/damianh/LibLog

I should have done logging with this as this is a library instead of a direct dependency on M.E.Logging.

**Comment by wind-rider** [comment]
Why?

With Microsoft.Extensions.Logging you have the ILogger interface which is more and more used around .Net Core/.Net Standard.

This interface can be implemented with several standard packages or 3rd party libraries and works with dependency injection which is a good thing

**Comment by rogeralsing** [comment]
I'm with @wind-rider on this one, I'd say M.E.Logging is the de-facto standard for logging in new .NET
Are there any drawbacks of ME other than the dependency?

**Comment by adamhathcock** [comment]
The dependency and possible clashing of versions and classes is the issue.  I’m mainly following what was written here:

https://nblumhardt.com/2017/07/library-logging/

**Comment by rogeralsing** [comment]
Just for reference:
In Go, we published all the logging stuff as messages on a specific EventStream.
This allows users to subscribe to that and plug in whatever logger they need.

**Comment by adamhathcock** [comment]
Not sure about Go but I remember looking at that strategy before thinking we might as well use a pre-existing shim.

I don’t mind if the call is sticking with what’s there now but I just thought going to no dependencies for a library might be better as I’m gonna try to do that personally.

**Comment by cpx86** [comment]
Seems to me there would be a risk of version problems with LibLog as well. E.g. if our version of LibLog is built against NLog version X and the user has NLog version Y with a breaking change to the interface, that would crash at runtime. Maybe unlikely since logger interfaces don't tend to change but still a possibility.

**Comment by adamhathcock** [comment]
LibLog uses reflection to integrate if the library user doesn’t custom integrate.  The interface breaks then a user can just custom integrate.

Risk of breakage is much lower.  Can just delete the default integrations code anyway if we don’t like it.

**Comment by alexeyzimarev** [comment]
@cpx86 LibLog does not include specific versions of logging frameworks it supports. It has no dependencies and it is not used as a package or library per se, it is a code file included in your project.

**Comment by rogeralsing** [comment]
What do we do with this one?

**Comment by adamhathcock** [comment]
I can do it for fun as I'm not doing much C# these days.

**Comment by rogeralsing** [comment]
@AsynkronIT/developers should we go for this?

IMO Logging Extensions are good enough for me

**Comment by adamhathcock** [comment]
I guess if there's been no real issues by now then it might not be worth doing.

**Comment by cpx86** [comment]
Microsoft.Extensions.* seems to be almost part of the standard library these days, so I see no reason to change.

**Comment by alexeyzimarev** [comment]
The point of LibLog that you just configure your favourite logging tool and it just works. With Microsoft.Extensions.Logging it is not like this.

**Comment by cpx86** [comment]
IME that's almost exactly how MS logging works, with the exception that you first configure a logging factory with your logging library, then create the loggers from that.

**Comment by tomliversidge** [comment]
I haven't used either, but this came up in my twitter feed last week:

https://blog.stephencleary.com/2018/05/microsoft-extensions-logging-part-1-introduction.html
https://blog.stephencleary.com/2018/06/microsoft-extensions-logging-part-2-types.html

**Comment by rogeralsing** [comment]
what is the state of semantic logging nowadays?

serilog still king?
and can i use it properly with any of the abstractions?

Skickat från min iPhone

**Comment by cpx86** [comment]
Serilog seems to be king yeah. I use it all the time with MS Extensions, haven't run into any gotchas yet

**Comment by rogeralsing** [comment]
using that combo, do you have to pass args digferently than if you use a normal logger?

do you pasd annon objects? what happens if you switch logger, does that work then?

Skickat från min iPhone

**Comment by raskolnikoov** [comment]
I use serilog alot with MS Extensions and I havent run into any problems with it. No you don't have to pass any args differently to use it, you just set it up in your startup configure and then use the ILogger from MS Extension in you app.

**Comment by alexeyzimarev** [comment]
> with the exception that you first configure a logging factory with your logging library
that was my point. LibLog does not require that.

Plus. LibLog is a source code package, so it creates no additional dependency. Currently, MS Logging is a nuget package, which Protoactor depends upon. In my view, less dependencies is better.

**Comment by rogeralsing** [comment]
but how does serilog know the object structure in the end?
doesnt this just make it a flat list of args?

Skickat från min iPhone

**Comment by alexeyzimarev** [comment]
No, it doesn't. In LibLog arguments are objects and messages are strings. So as soon as your message is in Serilog format and you pass your objects, everything works as it should.

**Comment by rubberduck203** [comment]
> In Go, we published all the logging stuff as messages on a specific EventStream.
This allows users to subscribe to that and plug in whatever logger they need.

I would expect protoactor to take this approach. Elixir’s logging system is a good reference for actor based design. Their logger is broken into two halves, a front end and backends. On application startup, the user configured backends are started and supervised by the Logger. Then, when the user calls the static `Logger.Log(msg,lvl)` function, messages are delivered to any & all configured backends. 

This removes the need to inject `ILogger`s into things that really shouldn’t care about logging. Just some food for thought. #467 landed me here. Neat project. Looking forward to kicking the tires.

**Comment by alexeyzimarev** [comment]
We might as well align logging with diagnostics and, therefore, with traces. If we put a diagnostic context in the actor context, we can have context-scoped logging and measurements. Then, in order to physically log, we can subscribe a logging observer to the diagnostic source and log wherever we want.

**Comment by alexeyzimarev** [comment]
For the MS logging abstraction, the version goes up and we keep referencing 2.2 for compatibility. The question is how long the compatibility will work. We cannot really upgrade the logging abstraction package version since some might get a version conflict. I like the logging through event stream idea. The MS logging could be then converted to a configuration extension, like the DI thing.

**Comment by rogeralsing** [comment]
Closing, the MS extensions works fine
