### ISSUE TITLE
Find a cross platform hash for node lookups

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#280]
When calculating what node owns what grains, we need a shared string hasher which is cross platform.

This one popped up in the github flow just now:
https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/artery/LruBoundedCache.scala#L14

Maybe just use something like that, easy to port

**Comment by adamhathcock** [comment]
If Akka uses it, it must work.

**Comment by raskolnikoov** [comment]
Ż

Den 27 juli 2017 2:50 em skrev "Adam Hathcock" <notifications@github.com>:

**Comment by rogeralsing** [comment]
![giphy](https://user-images.githubusercontent.com/647031/28968453-4d7f1d20-7920-11e7-90a8-f62674a87473.gif)

**Comment by cpx86** [comment]
Read a bit about it and related techniques and seems to be a good choice. Not sure for what purpose they modified Xorshift though - the original PR doesn't reveal anything.

**Comment by rogeralsing** [comment]
Closed by #300
