### ISSUE TITLE
Sqlite persistence is in fact EntityFramework persistence, rename?

### ISSUE THREAD

**Issue by alexeyzimarev** [AsynkronIT/protoactor-dotnet#289]
Sqlite persistence is in fact EntityFramework persistence, may be it is a good idea to name it like this so people can use the database of their choice?

**Comment by raskolnikoov** [comment]
It is EF-sqlite so why change the name?

**Comment by adamhathcock** [comment]
I think the point is that you could do a minor refactor and the same code would work for any EF supported database.

**Comment by alexeyzimarev** [comment]
Yes, I think it can be generic, since it just needs `DbContext`

**Comment by raskolnikoov** [comment]
I've done some refactoring to the sqlite plugin and will soon upload a new PR for this.
