### ISSUE TITLE
Escalate strategy behaviour is strange

### ISSUE THREAD

**Issue by florisch** [AsynkronIT/protoactor-dotnet#306]
I'm struggling with the escalate's supervision strategy behaviour. From the documentation I understood that when a child actor would fail (throw an exception) with this strategy. Then the parent actor would fail applying it's own strategy. This mean the parent (and it's children) would restart or be stopped depending on it's own parent's strategy.

Actually, it look like the child is just restarting itself 10 times and then stopping itself and not escalating anything.

Below is a simple minimal sample:
```
static void Main(string[] args)
{
	var childProps = Actor.FromFunc(context =>
	{
		Console.WriteLine($"{context.Self.Id}: MSG: {context.Message.GetType()}");
		switch (context.Message)
		{
			case Started _:
				throw new Exception("child failure");
		}
		return Actor.Done;
	});

	var rootProps = Actor.FromFunc(context =>
	{
		Console.WriteLine($"{context.Self.Id}: MSG: {context.Message.GetType()}");
		switch (context.Message)
		{
			case Started _:
				context.SpawnNamed(childProps, "child");
				break;
			case Terminated t:
				Console.WriteLine($"Terminated {t.Who.Id}");
				break;
		}
		return Actor.Done;
	})
	.WithChildSupervisorStrategy(new OneForOneStrategy((pid, reason) => SupervisorDirective.Escalate, 0, null));

	Actor.SpawnNamed(rootProps, "root");

	Console.ReadLine();
}
```

Output:
```
root: MSG: Proto.Started
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Restarting
root/child: MSG: Proto.Started
root/child: MSG: Proto.Stopping
root/child: MSG: Proto.Stopped
root: MSG: Proto.Terminated
Terminated root/child
```

**Comment by tomliversidge** [comment]
The parent has no parent here, so escalate falls back to the root / default. There is a default strategy if I recall correctly (sorry on mobile at the moment so can't show where)

**Comment by tomliversidge** [comment]
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Actor/Supervision.cs

There is a default strategy to restart 10 times defined in this file - this is what is happening in the code example

**Comment by florisch** [comment]
Ok, with this explanation I understand whant happen but it still seem reall unintuitive to me.

It would look more intuitive to have the parent fail (likt it is throwing an exception) and then it should be this parent (which has not parent) that should use the default straregy. What I mean is that with this test I would expect the root actor to be restarting 10 times, not the child actor. The child actor fail, escalate failure to parent and stop itself. Then the parent's parent supervision strategy is used to determine what to do with parent's (propagated) failure.

Of course this case would still leave the question about what happens to all root's children. But sound like a much more natural and easy to understand behaviour.

**Comment by rogeralsing** [comment]
You are correct, 
This implementation is wrong:
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Actor/LocalContext.cs#L218

It simply pass the failure forward to the grandparent like you say.
