### ISSUE TITLE
How to control the location where to spawn actor in cluster mode.

### ISSUE THREAD

**Issue by yindongfei** [AsynkronIT/protoactor-dotnet#315]
when I writing our game server, we need a watcher grain per machine to start other processes(like Unity3D) in the machine and watch on them. then report the status of processes(Unity3D) to other grains during time. my question is:

how to spawn a grain in a remote node ?
I register a watcher grain factory in the remote node
```
Grains.WorkerWatcherGrainFactory(() => new WorkerWatcherGrain());
```
then I can spawn watcher grain from other grain like:
```
var watcher = Grains.WorkerWatcherGrain("123");
```
but when I start many node, and every node has registered the watcher grain, I don't know how to spawn just one watcher grain for each node.

I have tried this:
```
await Remote.SpawnNamedAsync("127.0.0.1:12001", "123", "WorkerWatcherGrain", TimeSpan.FromSeconds(10));
 watcher = new WorkerWatcherGrainClient("123");
 var response = await watcher.ListWorkers(new ListWorkersRequest());
```

some times, it works. but some times exception raised:
```
      Restarting 127.0.0.1:12001/activator Reason Proto.ProcessNameExistException: a Process with the name '123' already exists
         at Proto.Props.DefaultSpawner(String name, Props props, PID parent)
         at Proto.Remote.Activator.ReceiveAsync(IContext context)
         at Proto.LocalContext.InvokeUserMessageAsync(Object msg)
         at Proto.Mailbox.DefaultMailbox.ProcessMessages()
```

what is the right way to do things like this?

just like orleans's   [PerSilo grain](https://github.com/dotnet/orleans/issues/610)

**Comment by rogeralsing** [comment]
There is a recent PR #319 that allows you get the PID even if the process exists, it will now return both the PID and a statuscode, if the PID is present, you can safely ignore the statuscode.

Can you verify if this solves your issue by updating to the latest DEV branch?

**Comment by rogeralsing** [comment]
See #325 discussion continues there
