### ISSUE TITLE
IndexOutOfRangeException in Persistence SqlServerProvider

### ISSUE THREAD

**Issue by anthonyhawes** [AsynkronIT/protoactor-dotnet#317]
IndexOutOfRangeException: EventIndex
at Proto.Persistence.SqlServer.SqlServerProvider.<GetEventsAsync>

**Comment by raskolnikoov** [comment]
Could you provide some info on how this occured?

**Comment by anthonyhawes** [comment]
I have a simple counter actor (like the one in the documentation).
In the counter constructor persistence is created using:-
persistence = Persistence.WithEventSourcingAndSnapshotting(provider, provider, actorId, ApplyEvent, ApplySnapshot);
There are no snapshots taken, but events are persisted.
On actor startup persistence.RecoverStateAsync is called and the exception occurs within that call.
The same code works fine when using the SqlLiteProvider.

**Comment by raskolnikoov** [comment]
fixed by #321
