### ISSUE TITLE
Suggestion: PID should have a "kind" field

### ISSUE THREAD

**Issue by PotterDai** [AsynkronIT/protoactor-dotnet#318]
Kind is a very interesting mechanism in cluster, allow user to define actor namespaces within cluster.
However this feature is heavily compromised if PID doesn't know which kind it belongs to.

For example:
A user cannot spawn both ActorKindA and ActorKindB in same node since they will share same ID which is user ID.

**Comment by raskolnikoov** [comment]
Why closed?

**Comment by PotterDai** [comment]
Made a quick test, and figure out that this brings in to much complexity to the system, you will need to call spawn(kind, name) instead of spawn(name) each time, no matter you need kind or not.

I later found that it's actually easier to generate a custom id before call spawn(name).
For example,  instead of call spawn("ActorKindA", "UserID"), just call spawn("ActorKindA/UserID").
