### ISSUE TITLE
Bundle Consul.exe with the source code

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#327]
It would be nice to allow the cluster examples to start w/o to download and install consul.
if we bundle Consul with the source code, we could have an boot application that starts Consul in Dev mode together with the cluster nodes.

Good, bad?, thoughts?

**Comment by raskolnikoov** [comment]
You mean in the cluster example?

**Comment by rogeralsing** [comment]
Done

**Comment by raskolnikoov** [comment]
@rogeralsing maybe should also bundle linux and macos versions since were dotnet core ;)
