### ISSUE TITLE
MySql (and actually "any sql") provider

### ISSUE THREAD

**Issue by MiloszKrajewski** [AsynkronIT/protoactor-dotnet#337]
Hi,

I wrote AnySql persistence provider which allows to use any SQL database as storage with no external dependencies at all. On top of this I've implemented MySql provider and I'm testing it this weekend.

My question is: do you want to to pull-request it or create separate repository?

Thanks,
Milosz

**Comment by raskolnikoov** [comment]
@MiloszKrajewski thanks for your contribution. We have already today a provider implementation for MSSQL in our repo that we maintain. Feel free to make a PR for your MySQL implementation, and place your "any sql" solution in your own repo for future considiration for now.
