### ISSUE TITLE
Microsoft.Extensions.Logging replacement for .NET 4.6 projects

### ISSUE THREAD

**Issue by vasily-kirichenko** [AsynkronIT/protoactor-dotnet#359]
Microsoft.Extensions.Logging rejects to add to a .NET 4.6 project. What should I use instead?

**Comment by keithbeller** [comment]
Microsoft.Extensions.Logging.Abstractions is looking for .NETStandard version 2.0

...
Restoring packages for E:\code\proto.actor\src\Proto.Actor\Proto.Actor.csproj...
Package Microsoft.Extensions.Logging.Abstractions 2.0.0 is not compatible with netstandard1.5 **(.NETStandard,Version=v1.5). Package Microsoft.Extensions.Logging.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)**
Package Microsoft.Extensions.Logging.Abstractions 2.0.0 is not compatible with net452 (.NETFramework,Version=v4.5.2). Package Microsoft.Extensions.Logging.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package restore failed. Rolling back package changes for 'Proto.Actor'.
...

**Comment by vasily-kirichenko** [comment]
Does this mean that Proto.Actor can run on Core only?..

**Comment by adamhathcock** [comment]
It means you need a framework that implements .NET Standard 2.0

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Some work could be done to support more full framework versions but you should upgrade to net462

**Comment by adamhathcock** [comment]
Related to https://github.com/AsynkronIT/protoactor-dotnet/pull/291

**Comment by vasily-kirichenko** [comment]
Thanks. I'd better go with akka for now.
