### ISSUE TITLE
ActorFactory fails to create actor after upgrade to 0.1.15

### ISSUE THREAD

**Issue by andreabalducci** [AsynkronIT/protoactor-dotnet#374]
Updated my project from 0.1.14 to 0.1.15 and found issues on ActorFactory.
version .14 works as expected
version .15 does not create actors

repro: https://github.com/andreabalducci/protobug 
downgrading to .14 fixes the issue.

Please consider tagging releases, will be easier to check (and possibly fix) issues like this.

**Comment by PotterDai** [comment]
I think this is due to https://github.com/AsynkronIT/protoactor-dotnet/commit/925165733a42c532301c5dcbdd1a635a170647f3
Reverting back fixes the problem.

cc @rogeralsing I think we can include this https://github.com/andreabalducci/protobug in our tests, I'll make a PR for that.

**Comment by speeddm** [comment]
Forgive me for commenting on a closed issue but our application relies heavily on instantiating actors from the ActorFactory - Is there a workaround for this issue or should I remain on 0.1.14 for now?

**Comment by rogeralsing** [comment]
We just published 0.1.16 which contains the above mentioned fixes.
Let us know if there are any issues with it
