### ISSUE TITLE
Proper C# documentation

### ISSUE THREAD

**Issue by mastorm** [AsynkronIT/protoactor-dotnet#38]
We need more documentation for C#. I would be willing to contribute, if there is a way? A Contributing.md would be awesome, too.

**Comment by rogeralsing** [comment]
Hi, and thanks for the interest.
We do have a contributing.md, but this needs to be copied and adapted for the .NET port too. 
https://github.com/AsynkronIT/protoactor-go/blob/dev/CONTRIBUTING.md

**Comment by mastorm** [comment]
Roger, im on it.

**Comment by mastorm** [comment]
Any specific style specification you guys follow? Just the standard ones from MSDN? https://msdn.microsoft.com/en-us/library/ff926074.aspx

**Comment by rogeralsing** [comment]
The MSDN standard is good.
When it comes to code formatting, I personally use just default Resharper settings, which I think is a good default as a lot of devs follow that.

**Comment by cpx86** [comment]
Yup, that's what I'm doing too.

Bear in mind that the project structure and API surface is in a bit of flux at the moment. Most things are starting to get into place now though. But for example, there are probably a lot of public stuff that should be made internal - and might not need any documentation.

**Comment by mastorm** [comment]
@cpx86 I will keep in mind. Im working on a contributing.md for now, expect it to be ready by tomorrow. Do the samples show every "permitted" use of protoactors API? Because then ill just figure out whatever classes are used in there and document them. Do you guys have any sort of workflow for contributing documentation? Because you guys will need to review it once im done. Its hard to document something from the ground up which I didnt write.

**Comment by cpx86** [comment]
@mastorm Currently the samples show _some_ of the permitted use but they are far from complete yet. They're also a bit mixed - some of them are actually benchmarks, whereas some are intended as documentation.

One idea I've been thinking about for a while is if it would be feasible to build something similar to Go's example tests. Basically the examples would be 1) runnable stand-alone, 2) contain assertions that can be verified on build-time and 3) the body of the example would be extracted and included as part of the documentation. Not sure yet of exactly how it can be done (Roslyn + Microsoft.TestPlatform.ObjectModel + DocFX maybe?) but it would be pretty cool :)

**Comment by cpx86** [comment]
Another thing I've also been thinking is that it would be good to keep the Go and the .NET documentation as close as possible. API docs will of course be separate but if we are going to write tutorials then having one documentation with samples in both languages would be nice.

**Comment by cpx86** [comment]
Current status:
Hello World, props, spawning, supervision and mailboxes have mostly been fleshed out with essential documentation.

Important topics yet to tackle:
Dispatchers, behaviors, receive/sender middleware, deadletter, lifecycle events, routers and remote

**Comment by cpx86** [comment]
More docs done. Still to do:
Deadletter, Eventstream, Cluster/Grains, ProcessRegistry(?), Receive timeout, Remote, Router, Stash (?)

**Comment by tomliversidge** [comment]
Persistence docs are awaiting PR merge, Behavior docs are done.

**Comment by tomliversidge** [comment]
Is it better to raise issues about docs improvements here or in the gam-web repo?

**Comment by tomliversidge** [comment]
I've raised issues in gam-web issues for obviously missing documentation.

**Comment by dotfelixb** [comment]
What is the state of C# documentation, I've started using Proto.Actor and looking for where I can contribute and the docs seems the right place, what the way forward.
