### ISSUE TITLE
OpenTracing support

### ISSUE THREAD

**Issue by jrouaix** [AsynkronIT/protoactor-dotnet#398]
I heard about OpenTracing initiative and wondering about using this API in our projects.
There is a .net grpc already available : https://github.com/opentracing-contrib/csharp-grpc, but it doesn't seem to be any grpc configuration setup mechanism in proto to enable some tracing plumbing in https://github.com/AsynkronIT/protoactor-dotnet/blob/58862d2c47fd403e734e44966539d3d1e3de4095/src/Proto.Remote/Remote.cs#L58-L62

Then I think following messages from actors to other actors could be achieved with Receive & Sender middlewares.

**Comment by jrouaix** [comment]
Anyone already thought about OpenTracing for proto actor ?

**Comment by rogeralsing** [comment]
>Then I think following messages from actors to other actors could be achieved with Receive & Sender middlewares

Yes, this is very much why send and receive middleware was brought into ProtoActor.
For some time we did not have the message header support for Proto.Remote. but AFAIK, all the required bits are there now.

So it should be possible to implement.
I'm not sure if involving it for gRPC itself is a good idea, we do message batching over remote, meaning there are multiple messages from many actors passed in a single call.
Thus, the trace headers needs to be per inner message for it all to work correctly

**Comment by jrouaix** [comment]
ok @rogeralsing. will do without. Thank you :-)

**Comment by rogeralsing** [comment]
Don't give up, the infrastructure is all there. just don't do it using the gRPC settings, go Sender and Receiver middleware all the way :-)

**Comment by jrouaix** [comment]
Yes I will. Sorry I meant i'll do **without grpc tracing**.
If I end up with something agnostic enough to be used by the community, are you interested by a PR ?

**Comment by jrouaix** [comment]
@rogeralsing If I have a PID, but i'm not in an actor so I don't have a context. 
Is there a way to reuse a sender middleware here of some kind to add headers ?

**Comment by jrouaix** [comment]
In progress here : https://github.com/AsynkronIT/protoactor-dotnet/pull/406
