### ISSUE TITLE
LocalContext is not immutable

### ISSUE THREAD

**Issue by ocdogan** [AsynkronIT/protoactor-dotnet#399]
LocalContext is not immutable. When a mailbox is being processed,LocalContext's ProcessMessageAsync method is being called inside its InvokeUserMessageAsync method, which sets the send parameter to the context's "_message" field member and after, the context is being send to Actor's ReceiveAsync method. In case you make an async Task run  using the given context or send the context to another actor as a message, you will loose the message of the context. I think context has to be immutable or the message has to be send separately as a parameter to actor to prevent such cases.

**Comment by rogeralsing** [comment]
This is by design, proto actor is largely allocation free (depending on mailbox impl).
Doing Task.Run will largely defeat the purpose of actors.

Could you tell us something about the usecase and what you are trying to do.

just using async await works fine, the mutability of context will come into play is if you break actor concurrency rules by leaking context into concurrently running tasks.

**Comment by ocdogan** [comment]
When I check the philosophy of the actor model, the design is made for lock-free implementation over mailbox with single call at-a-time to actor, but that does not prevent any complement the call with a future call using the context as a message. I know that this is proto's design choice but that choice seems to break the main philosophy behind actor model because of C#'s object orientation. If proto was designed in functional programming environment, calls would be with immutable parameters and it should work. I think I got this to the point, but to me, it still seem to be break of actor model. Instead, I think the context that is passed should be a struct or tuple like class which would be constructed on each receive call.

**Comment by rogeralsing** [comment]
No what breaks the philosophy is if you leak internal details into concurrent processes.
What is the specific reason why you need to pass the entire context off to a Task.Run?

Why not just pass the PID?
