### ISSUE TITLE
.NET build pipeline

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#4]
Add .NET build pipeline in Travis. possibly using Cake build

**Comment by cpx86** [comment]
I take.

**Comment by cpx86** [comment]
CI up and running on AppVeyor now :) https://ci.appveyor.com/project/cpx/protoactor-dotnet-pr5pp

Will look into using Cake as well - e.g. for generating proto contracts, and packaging/pushing NuGet packages.

**Comment by rogeralsing** [comment]
![yo da best](http://i.imgur.com/My8ucFs.gif)

**Comment by cpx86** [comment]
We should probably create an organizational account, but this'll do for now :)

**Comment by cpx86** [comment]
Closing this since we have all important pieces working:
- automatic build/test/package
- versioning of pre-release packages
- automatic push to myget feed
