### ISSUE TITLE
Major Changes coming

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#404]
In an effort to align all the parts of Proto.Actor while we are still Beta mode.
The following changes have been made:

* FromProducer and FromFunc have moved from Actor to Props. - it never really made sense to have that under Actor. it returns props, so it should live in props.

* `Tell` is renamed to `Send`. `Ask` and `Tell` are names from the Akka world. Elixir/Erlang uses `Send`.
* `Send` and `Request*` are no longer available on `PID` - this might seem strange, but in order for sender middleware to work, all calls needs to go through context.
* `RootContext` introduced, earlier, there was a context for actors, but no context for the outside world. this has changed so that creating or interacting with actors from the outside, is done through `RootContext`
* `LocalProcess` and `LocalContext` -> `ActorProcess` and `ActorContext`- many things could be local, Kafka or Rabbit processes etc.
* Actors take up much less memory by default. Proto.Actor was already extremely slim in this sense. now it's even more so.

**Comment by rogeralsing** [comment]
Snippet showcasing some of the changes

Before:
```csharp
var props = Actor.FromProducer(() => new MyActor());
var pid = Actor.Spawn(props);
pid.Tell(myMessage);
```

Now:

```csharp
var context = new RootContext(/* you can pass headers and middleware here */);
var props = Props.FromProducer(() => new MyActor());
var pid = context.Spawn(props);
context.Send(pid, myMessage);
```

Why more code?
Observability, testability, aligning the global API with the actor context API.

The new code will allow us to measure when and where actors were created, you will be able to intercept calls to context methods to do proper metrics and tracing.
You will be able to test what messages goes out or into a context.

e.g. this is what the same code would look like inside an actor:

```csharp
public Task ReceiveAsync(IContext context) 
{
    ...other code

    //we already have a context from the actor
    var props = Props.FromProducer(() => new MyActor());
    var pid = context.Spawn(props);
    context.Send(pid, myMessage);

    ...other code
}
```

So the outside and the actor inside code now looks and behaves the same way

**Comment by potterdai** [comment]
I think context.Send makes a lot of sense for middleware.
I will squeeze some time to do the same change on the Go part. = )

**Comment by rogeralsing** [comment]
I would really like to be able to ship Proto.Actor with built in tracing support.
That would be fantastic.

Also providing testing middleware to observe what goes in and out of actors

**Comment by rogeralsing** [comment]
I'm also working on Decorator support for RootContext and ActorContext. allowing users to intercept any context call.

**Comment by raskolnikoov** [comment]
This f***ing nice! 👌

**Comment by rogeralsing** [comment]
Open questions.
For some sub systems, e.g. Remote, Cluster, Router.
Right now they use the empty rootcontext `RootContext.Empty` for all their outside messaging.
Should we set up dedicated contexts for each of these. is there a need to apply middlewares for these subsystems too?

**Comment by cpx86** [comment]
Sweet, nice to see these changes finally falling into place :)

In addition to tracing support, would it make sense to also include other types of observability e.g. metrics/perf counters, more debug logging, etc?

**Comment by cpx86** [comment]
One thing that's a bit unclear to me in regards to `new RootContext()` - would there ever be a reason to have multiple contexts within a single application? Coming from Akka, that feels a bit like an ActorSystem, but it's not one. Would it make sense/be possible to have a global singleton context?

**Comment by jrouaix** [comment]
@cpx86 I should be possible to add metrics with middlewares on https://www.app-metrics.io/ or when OpenTracing instrumented, by changing the Tracer and make a composite one, it should be possible to add metrics here (It's what I plan in our private stack)
Same way, OpenTracing api present methods to log ... so again, by composition behind the interface : magic !

**Comment by rogeralsing** [comment]
> would there ever be a reason to have multiple contexts within a single application

Yes, the rootcontext would be per e.g. API request

Let's say you have an API endpoint, and there are HTTP Zipkin headers coming in.
Then you could do something like:

```
//HTTP Endpoint
public async Task<SomeResponse> GetStuff()
{
     var context = new RootContext(MapHTTPHeadersToProtoHeaders(), ZipkinMiddleware);
     return context.RequestAsync<SomeResponse>(somePid, someMessage);
}
```

So a RootContext is not like an actor system, it is a calling context that allow us to capture/model headers/middleware for sending stuff into the actor world.

**Comment by cpx86** [comment]
Ah of course, gotcha. The Root prefix confused me :P Makes sense when I think about it though.

**Comment by rogeralsing** [comment]
Any other name that would make more sense? this does not have to be final in any way

**Comment by cpx86** [comment]
Thinking freely here; within an HTTP request an intuitive name would be RequestContext or HttpContext; or within a messaging process MessageContext could make sense. What's a similarly appropriate term when talking to actors? ActorContext? SenderContext? ActorContext would be consistent naming-wise with ActorProcess, and the two are tightly coupled as well. SenderContext would probably only make sense if context was generically coupled with a process.

**Comment by jrouaix** [comment]
ClientContext ?

**Comment by BentTranberg** [comment]
I don't understand much of the architecture, but there's one thing I'd like to be possible.

I have developed a server and a client that uses Proto.Actor. I call Remote.Start in the server and in the client. This works great in a normal setting.

If I try to run the server in-process in the client, calling Remote.Start in the server and in the client doesn't work. I get an exception "Proto.ProcessNameExistException: a Process with the name 'EndpointSupervisor' already exists".

So what do I do then? My workaround is to not call Remote.Start, and instead simply use local PIDs. This works well too, but I don't like this way of doing it. There are "if-then-else" statements in the server and client that I don't like.

I would like the client and server to communicate in exactly the same way, even when they live in the same process. Now, I don't know if there's some solution to my slight problem that I haven't discovered - could well be - or if this is just the way Proto.Actor works.  If the latter, then perhaps some rethinking should be done now.

To me, it makes sense to allow "multiple separate Proto.Actor domains to exist in the same process" without this requiring a different setup than that used when they're in separate processes. This is good for a test and development scenario as I've described above, and also for unit testing.

**Comment by csharper2010** [comment]
"Yes, the rootcontext would be per e.g. API request"

I'm new to Proto.Actor and did not use any middleware yet so sorry if I don't understand that.

I thought of this RootContext being the root of the actor hierarchy, the place from where the top level actors are spawned. So how can this root context exist per API request. Maybe you can give a few words on where my thinking is wrong.

As far as I understand those changes, they are a very welcome streamlining of the API.

Do you have a timeframe when the might be a first version with those changes in place on nuget?

**Comment by BentTranberg** [comment]
A situation report: I upgraded Proto.Actor in my solution from to 0.1.16 to 0.2.0. A master-detail view that communicates with a server through Proto.Actor and had instant updates, now keeps updating for quite some seconds after I let go of the arrow key after arrowing up or down in the master list. I haven't done any further research. I'll stay on 0.1.16 for my production stuff for now.

**Comment by alexeyzimarev** [comment]
@rogeralsing it's out, what you planned, right? Closing?

**Comment by rogeralsing** [comment]
Yes lets close this, new major changes inc with the ActorSystem changes. but separate issue
