### ISSUE TITLE
Proto.HTTP

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#410]
Would it be interesting for others to have a pre-packed HTTP solution?
I'm thinking since we already are deep into Protobuf(+json) and Consul.

Why not make a package similar to my old https://github.com/rogeralsing/Microphone service discovery lib.

If we see Proto* as a distributed programming toolkit and not so much focus on Actors, then it would make sense, no?
We could even have adapters to create HTTP Endpoints for actors

**Comment by raskolnikoov** [comment]
Cool, yes it would be nice

**Comment by jrouaix** [comment]
You mean it would be possible to call [Post] http://endpoint/{actorKind}/{actorName} with a serialized command in the body ? out of the box ?

**Comment by rogeralsing** [comment]
Maybe, we could certainly play it that way.

**Comment by JohnnyMaxK** [comment]
There is a lot of tools that can be used to check the behavior of the actors if we expose the http channel.
I don't know if it already exists but we also need a RabbitMQ channel.
And why not mix the idea, call in http the actor to push the message in the RabbitMQ to be sure that the message will be dequeue even if the actor is unavailable.

What do you think guys ?

**Comment by cpx86** [comment]
> There is a lot of tools that can be used to check the behavior of the actors if we expose the http channel.

Yep this could be a huge benefit. We've discussed building a CLI for protoactor that could connect to remote processes to provide introspection. For many use cases though, an HTTP interface might be more useful - e.g. if you want to integrate it into some custom monitoring script or whatnot.

**Comment by rogeralsing** [comment]
What about scope of functionality

* Virtual Actors?
/{actorKind}/{actorName} 

* Plain Actors?
/actor/{pid.ID} 

Security? prevent some ID's to be touched?

**Comment by jrouaix** [comment]
> Security? prevent some ID's to be touched?

Perhaps it can be a default config and then opt-in/out ?
(and all system stuff are opt-outed)

**Comment by cpx86** [comment]
Security is probably best left to be configurable by the user. If this was e.g. implemented as a reusable ASP.NET Core Controller that is plugged into an existing web host, then we should be able to find a way for the user to intercept API calls and apply whatever authorization logic they wish to.

**Comment by rogeralsing** [comment]
So for normal actors, just let Asp.NET be Asp.NET but we provide some easy way to unwind the HTTP Context + payload and transform into message + headers and pipe to a PID

Least amount of magic, fully configurable and works with other things.
Yet easy to use and integrate

**Comment by JohnnyMaxK** [comment]
@cpx86 @rogeralsing  I think we have to show you what we did by using the swagger codegen to generate our actors 😄 
IMO, the same swagger should be used to generate the http api to have more flexibility as possible proposed the openapi standard and the security could we handle inside it.
The http interface could be based on the introspection but it should be also based on a swagger like Azure Function api defintion.

I propose you a call conf on Google Hangouts or Skype to make you a demo.
What do you think ?

**Comment by cpx86** [comment]
Would we want the API to be generated from the actors though? I'm rather leaning towards having the HTTP API reflect the internal API - e.g. `/pids/{pid}/send` to send messages to a PID or `/kinds/{kind}/send` to send messages to a virtual actor.

Should it also be possible to remotely spawn actors via this API? What about watching actors? How far do we want to take this?

**Comment by JohnnyMaxK** [comment]
@cpx86  The watching actors should be a supervisor related to the actor type, he will be responsible of the spawn the actor on his partition scope.
In Service Fabric they handle it quite greatly because they also integrate the concept of actor partition automatically.

**Comment by cpx86** [comment]
@Johnny-Bee The reason I'm asking is that all of this is supported using Proto.Remote. I don't really see any point in having an HTTP API implementing all the functionality - in that case it's better to go with Proto.Remote and gRPC since it's a more suitable transport.

For a pure HTTP API, I think the main benefit would be to simplify for a non-actor application to integrate with actors in another application - and also to allow for observability on a standard protocol.

**Comment by JohnnyMaxK** [comment]
Sorry, I don't know the content of Proto.Remote so I think I misunderstood your questions.
I fully agree about the main benefit of the HTTP API.

> Should it also be possible to remotely spawn actors via this API? 

Yes.

**Comment by alexeyzimarev** [comment]
Maybe it's a good candidate for contrib?

**Comment by rogeralsing** [comment]
@alexeyzimarev agree

**Comment by rogeralsing** [comment]
Closing, but the HTTP endpoint idea is very cool, would be nice for debugging / adhoc management of the cluster
