### ISSUE TITLE
Proto.Remote refactoring

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#411]
Currently, the structure for Proto.Remote looks something like this:

![protoactor](https://user-images.githubusercontent.com/647031/41424298-e840ba88-6ffd-11e8-9f7b-d76df20ae82f.png)

This could probably be simplified a lot to something like:

![protoactor-page-2](https://user-images.githubusercontent.com/647031/41424306-eda903c2-6ffd-11e8-88c5-f934664c5920.png)

**Comment by cpx86** [comment]
@rogeralsing Would you be up for kicking this off? :) I started trying to integrate Proto.Remote with the AspNetCore pipeline again and boy is it fast becoming a mess. It works better now since we introduced the ActorSystem and can now have separate instances of Remote, but the design of that class doesn't feel fitting at all anymore. 

Some issues:
- The Start method handles both wiring up the internal processes, and starting the standalone gRPC server
- The Start method will override the EndpointManager and EndpointReader on each invocation.
- The Serialization class needs to be instantiated separately from the Remote class, which feels strange and unnecessary

In addition to the changes you've already proposed (which should make further refactoring a lot easier thanks to simplification), I'm thinking it would be nice to find a way to separate the wiring of Remote from the actual server hosting. Maybe something like this (still figuring out the proper mechanics for the AspNetCore pipeline...):

```csharp
// from Startup.Configure()
app.UseProtoRemote(remote => {
    remote.RegisterMessages(FooReflection.Descriptor);
    remote.RegisterKnownKind("foo-actor", fooProps);
});
app.UseEndpoints(endpoints => {
    endpoints.MapProtoRemoteService();
});
```

or

```csharp
// from Main method or wherever
var server = new SelfHostedRemoteServer("127.0.0.1", 31337, remote => {
    remote.RegisterMessages(FooReflection.Descriptor);
    remote.RegisterKnownKind("foo-actor", fooProps);    
});
server.Start();
```

Thoughts?

**Comment by rogeralsing** [comment]
I think we need to start one level up, how do we init the actorsystem iteself in the asp.net core pipeline?

register it as a singleton on the di container.
do we need some form of config support on the system?

**Comment by cpx86** [comment]
ActorSystem would need to be registered in the DI yes. Possibly the Remote as well, so it can be gracefully shut down.

It could make sense to expose the RemoteConfig via the config system. Especially AdvertisedHostname/Port is something I think you'd want to configure outside of the application and pass in via json or env variables.

**Comment by rogeralsing** [comment]
Some thoughts:

* Does multiple endpoints for one actor system have any benefits
* Does the current pid resolution support this, I would guess not due to process reg having the host name. 

* Should actor system support plugin services like Akka. e.g. remote being an instance stored inside the actorsystem, based on some interface -> object lookup

**Comment by cpx86** [comment]
> Does multiple endpoints for one actor system have any benefits

Probably not. It would basically be the exact same endpoint but on a different port.

> Should actor system support plugin services like Akka. e.g. remote being an instance stored inside the actorsystem, based on some interface -> object lookup

It might have some benefit having the ActorSystem act as the "root" object. OTOH it feels a bit then like we're turning it into a generic container

**Comment by rogeralsing** [comment]
Agree.
So TLDR; we keep the actorsystem ignorant of the remoting layer and instead inject the actor system into the remoting layer.

I like this idea:

```
// from Main method or wherever
var server = new SelfHostedRemoteServer("127.0.0.1", 31337, remote => {
    remote.RegisterMessages(FooReflection.Descriptor);
    remote.RegisterKnownKind("foo-actor", fooProps);    
});
server.Start();
```

Maybe just pass actorsystem in there? `new SelfHostedRemoteServer(system, "127.0.0.1",`

**Comment by cpx86** [comment]
Should work, then it can create a new Remote internally and expose it so the user can configure it before starting the server.

**Comment by Damian-P** [comment]
What about a RemoteActorSystem which inherits from ActorSystem. It could be used like this: 

```csharp
var system = new RemoteActorSystem("http://localhost", 12000);
system.Serialization.RegisterFileDescriptor(ProtosReflection.Descriptor);
await system.StartAsync();
system.Root.SpawnNamed(Props.FromProducer(() => new EchoActor()), "remote");
// Do work
await system.StopAsync();


internal interface IInternalRemoteActorAsystem : IRemoteActorSystem
    {
        EndpointManager EndpointManager { get; }
        IRemoteConfig RemoteConfig { get; }
        void SendMessage(PID pid, object msg, int serializerId);
    }

public interface IRemoteActorSystem : IActorSystem
    {
        Serialization Serialization { get; }
        RemoteKindRegistry RemoteKindRegistry { get; }
        Task<ActorPidResponse> SpawnAsync(string address, string kind, TimeSpan timeout);
        Task<ActorPidResponse> SpawnNamedAsync(string address, string name, string kind, TimeSpan timeout);
        Task StartAsync(CancellationToken cancellationToken);
        Task StopAsync(CancellationToken cancellationToken);
    }

public interface IActorSystem
    {
        ProcessRegistry ProcessRegistry { get; }
        RootContext Root { get; }
        Guardians Guardians { get; }
        DeadLetterProcess DeadLetter { get; }
        EventStream EventStream { get; }
    }
```

I have a branch on my repo where I have a project for native Grpc (Proto.Remote.Grpc), a Grpc.Net project (Proto.Remote.AspNetCore) and all the shared classes are still in Proto.Remote.

Should we keep the native Grpc stuffs ?

I have some issues in Grpc.Net:

- The connection is canceled after a delay when idle when the connection is in TLS. We have to configure the HttpClient
- To gracefully shutdown the server, the connection has to be cancelled by the Writer.
- The host needs to mention the protocol and http has to be enabled by a switch
```csharp
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
```

I addressed the disconnection issue by adding a boolean to the Unit message and now it acts as a ping that is sent every x ms and is telling the EndpointWriter when it has to shutdown.

**Comment by rogeralsing** [comment]
Regarding inheriting ActorSystem, that feels like the worng approach, we burn the base class incase there are other extensions we want to do.

Although, we could have some extension method on actor system that sets up the remoting layer instead.

**Comment by rogeralsing** [comment]
WiP code here https://github.com/AsynkronIT/protoactor-dotnet/pull/553

RemoteConfig is now moved to the Remote ctor. 

```csharp
var remote = new Remote(system, config);
await remote.StartAsync();
```

or 

```csharp
var remote = new Remote(system, new RemoteConfig()
     .WithAnyHost()
     .WithAnyFreePort());

await remote.StartAsync();
```
