### ISSUE TITLE
ReceiveContext.Receive is not invoked

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#413]

**Comment by rogeralsing** [comment]
I've added a test that asserts that ActorContextDecorator.Receive is called before ActorContext.Receive.

https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/tests/Proto.Actor.Tests/MiddlewareTests.cs#L41

cc @jrouaix 

Am I misunderstanding the usecase, because this case works

**Comment by jrouaix** [comment]
It need to have a receive middleware to trigger the decorator.

https://github.com/jrouaix/protoactor-dotnet/blob/8c27f704d365429a38f514fadfaf98e90f084e72/src/Tracing/Proto.OpenTracing/OpenTracingExtensions.cs#L31

**Comment by rogeralsing** [comment]
Confirmed.
I've added a new test and fixed the issue
