### ISSUE TITLE
Performance issue with small message

### ISSUE THREAD

**Issue by Schebb** [AsynkronIT/protoactor-dotnet#428]
Hello,

I ran a benchmark program for measuring time when sending message with ProtoActor (and Tell() funcs).

I got these results:
![message test - remote](https://user-images.githubusercontent.com/1651024/45636622-81d08a80-baa8-11e8-90d0-ebb7432ba415.png)

(ProtoActorWire => using WireSerialization, ProtoActorRefl => using ProtoReflections)

It's seems under ~1500 bytes, packets are not sent immediately.

My current hypothesis is this caused by a Nagle's algorithm.
**What do you think ? If this is true; do you know if there is a simple way to disable it ?**

There are what I found so far:
ProtoActor has WriteOptions and WriteFlags but it use 0 by default, meaning no particular option.
So I searched further into gRPC. The grpc C# wrapper seems also to let everything by default.
However, in grpc core (in C) I can see two different implementations:
src/core/lib/iomgr/iomgr_windows.*
and
src/core/lib/iomgr/iomgr_posix.*

The posix one disable explicitely the Nagle's algorithm but the 'windows' does nothing (I am running on windows). I am about to change this for a test. I will tell you if it worked. But I wanted to know if there was a more official way to do this anyway.

EDIT: oops I just noticed that if this is true, this is not an issue from protoactor... but still protoactor's user may encounter this issue.

**Comment by MiloszKrajewski** [comment]
Not a fix but for those who need this addressed here's a link: https://www.fixwindowserrors.biz/blog/disable-nagle-algorithm-in-windows-10

**Comment by Schebb** [comment]
confirmed: adding a setsockopt(TCP_NODELAY) in grpc/.../tcp_windows.cc fixed my problem.

The problem is that this function requires de file description/SOCKET id, but I don't think this information is exposed in ProtoActor.

The best solution I see is to propose a pull request on grpc's github.

EDIT: before closing this "issue" thread, I will post the update plot with fair results.

**Comment by Schebb** [comment]
> Not a fix but for those who need this addressed here's a link: https://www.fixwindowserrors.biz/blog/disable-nagle-algorithm-in-windows-10

I tried this but it didn't worked on my two Windows 10.. Still it's worth to test it ;-)

**Comment by Schebb** [comment]
The updated plot ('ping test' between two computers in a local network):
![fixed](https://user-images.githubusercontent.com/1651024/45740050-9cb01580-bbf4-11e8-9c30-22215fa7bfec.png)

It's not smooth because I should run the test over more samples and in an isolated OS and network. It just give an idea. Note this is also because outputted timestamp are really close.

Note also these results should be taken ligthly as they does not reflect performances of an application using a full actor-based architecture (it is just about the time for one message). Still ProtoActor/Grpc seems pretty good.
