### ISSUE TITLE
Future<> BUG - need help

### ISSUE THREAD

**Issue by jrouaix** [AsynkronIT/protoactor-dotnet#432]
Hello @rogeralsing @cpx86 @PotterDai 
I'm turning mad on our production because of a bug repoduced on this branch : https://github.com/jrouaix/protoactor-dotnet/tree/hotfix/remote-local-nightmare

First that was a problem on local/remote calls mixing, then I narrowed it in Future<> usage in some Task situation : https://github.com/jrouaix/protoactor-dotnet/blob/f0f88456d983ad55fc913a0c429db6c84c0623dc/tests/Proto.Actor.Tests/FutureTests.cs#L118

Weirder this will break : 
```
await Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1));
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
```
but it will go fine in this order :
```
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
await Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1));

```
This one will break, but not if I had a breakpoint
```
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
await Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1));
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
```
This one is passing
```
// but if you add just one await version here, it won't
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
await Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1));
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
await Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1));
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1)).Wait();
await Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1));
await Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1));
await Context.RequestAsync<object>(pid, "hello", TimeSpan.FromSeconds(1));
```

**Comment by rogeralsing** [comment]
Is there some ASP.NET involved here? WinForms/WPF? or just pure server code?

**Comment by rogeralsing** [comment]
NVM the test should be enough. I will take a look

**Comment by jrouaix** [comment]
In some of our production services, there is aspnetcore web API involved. But in the code reproducing the problem on protoActor code, it's only console app & unit tests.

**Comment by rogeralsing** [comment]
Confirmed, there is something superfunky going on here.

I've added logging to the test:

```
Starting
Got Message hello1
got response 1
Sent Response to hello1
Got Message hello2
Sent Response to hello2
```

The actor gets the messages and also responds to them.
But the final request doesnt complete..

Digging further..

**Comment by rogeralsing** [comment]
Past self almost saw this coming, see comment.


```
            if (cts != null)
            {
                //TODO: I don't think this is correct, there is probably a more kosher way to do this
                System.Threading.Tasks.Task.Delay(-1, cts.Token)
                    .ContinueWith(t =>
                    {
                        if (_tcs.Task.IsCompleted)
                        {
                            return;
                        }

                        _tcs.TrySetException(
                            new TimeoutException("Request didn't receive any Response within the expected time."));
                        Stop(pid);
                    });
            }
```

Trying to figure out what the correct way is now

**Comment by jrouaix** [comment]
@rogeralsing not sure it's related to the cancellation token, if you don't pass any timeout, I previously observed a forever wait.
Also I tried another implementation, same behavior.

**Comment by rogeralsing** [comment]
OK, I've found the issue, not quite sure how to deal with it.

TaskCompletionSource.TrySetResult completes on the same thread that calls it.

Here is a log:
```
3       Starting
4               Enter actor
4               Enter actor
4               Got Message hello1
Got message hello1Response
4       Got response1: hello1Response
//stuck here forever
```

The first number is the thread Id.
see how the app starts in thread 3.
then the actor starts working in thread 4.
And the response is completed and continued in the same thread 4.
This thread then continues to block on .Result. preventing the actor from exiting and continuing with the next message.

Things got apparent up once I just commented out the timeout code.
The TrySetResult needs to complete asynchronously.

that is, the actor sending a response cannot invoke the response continuation synchronously.

**Comment by rogeralsing** [comment]
Same issue as this IMO https://github.com/EventStore/EventStore/issues/1179

**Comment by rogeralsing** [comment]
Solved it, not sure if this is OK, but at least this test runs... running for tests now

**Comment by rogeralsing** [comment]
Now timeout tests throws instead..

Anyway:

Changing this line 
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Actor/Futures.cs#L62

To
```
Task = _tcs.Task.ContinueWith(x => x.Resultl);
```

Gets rid of the deadlock and makes the response arrive asynchronously as intended.
So we are almost there. we just need to solve how to both handle timeout and set response async.

**Comment by rogeralsing** [comment]
PR is open. anyone with the time and knowhow, feel free to clean this one up.

**Comment by dpavsrtrl** [comment]
Take a look at PR #434
