### ISSUE TITLE
Is 'void Request(PID target, object message, PID source)' deprecated?

### ISSUE THREAD

**Issue by MiloszKrajewski** [AsynkronIT/protoactor-dotnet#435]
Hi,

Seems like in version 2.0 context is missing overload I was using:

```
void Request(PID target, object message, PID source)
```

Was it deprecated for some reason? Or is just in some extension methods which I'm missing?

Thanks,
Milosz

**Comment by alexeyzimarev** [comment]
It is `context.RequestAsync`, which sets the sender to `context.Self`

**Comment by MiloszKrajewski** [comment]
I'm not sure if I understand.
I thought that in context of actor `A` calling `Request(B, message, C)`, will send `message` to actor `B` with "return address" of actor `C`. 

None of overloads of `RequestAsync` allow to do that:

```csharp
Task<T> RequestAsync<T>(PID target, object message, TimeSpan timeout);
Task<T> RequestAsync<T>(PID target, object message, CancellationToken cancellationToken);
Task<T> RequestAsync<T>(PID target, object message);
```

I guess I could do this myself with:

```csharp
Send(B, new MessageEnvelope(message, C, null));
```

as `Send` is calling `SendUserMessage` and `SendUserMessage` is used with envelopes, but this may not be guaranteed in the future.

Am I missing something?

**Comment by alexeyzimarev** [comment]
`RequestAsync` does exactly that, then the receiver responds with the message of type `T` and the response is then delivered to the requestor. I use it in my code and have had no issues so far.

**Comment by MiloszKrajewski** [comment]
So if actor `A` uses `RequestAsync` to send message to actor `B` the response will be delivered to actor `C`?
How to pass address of actor `C` in `RequestAsync`?
I'm missing something definitely.
Or you are saying that I should use `Send` instead and wrap my message into `MessageEnvelope` myself?

**Comment by cpx86** [comment]
If actor `A` wants to send a message to actor `B` and receive a reply, the correct approach would be that `A` calls `context.RequestAsync(B, message)` such that when `B` calls `context.Respond(reply)` the reply message will be sent to `A`.

If you want a chain where `A` calls `B` calls `C` then I would think about what the actors responsibilities should be and how they should be wired up to talk to each other. E.g. if `A` creates `B` it _might_ also create `C` and tell `B` to use it when creating it. Or maybe `B` creates `C` itself. It all depends, but IMO you shouldn't be fiddling with message envelopes with a different sender than the actual one.

Closing - please reopen if this is still a problem.

**Comment by MiloszKrajewski** [comment]
I assumed that is what router is doing? When message is sent (forwarded?) to actor through the router the actor response is sent back to the sender (not the router). Otherwise, router would need to keep track which response it is?
I guess *forwarding* is the key word here.

Or I messed something up?
