### ISSUE TITLE
Simple scheduler cancelation token problem

### ISSUE THREAD

**Issue by boris6** [AsynkronIT/protoactor-dotnet#437]
Hi,
There seems to be a problem with Scheduler example project since the 0.2.0 update. System.Threading.Tasks.TaskCanceledException occurs after calling a Cancel method on a Cancelation token. Just removing token from await Task.Delay(interval, cts.Token) within Repeatedly methods seems to fix the issue. Is that ok fix?

**Comment by andreabalducci** [comment]
@boris6  found same error this morning, pushed a fix https://github.com/AsynkronIT/protoactor-dotnet/pull/454

**Comment by boris6** [comment]
> @boris6 found same error this morning, pushed a fix #454

Great. Thanks for letting me know
