### ISSUE TITLE
Shall we publish a version that is 0.1.17?

### ISSUE THREAD

**Issue by potterdai** [AsynkronIT/protoactor-dotnet#439]
@rogeralsing 
Hey Roger, finally I got some spare time to spend here, I'll continue porting the change to GO.
In the meantime, shall we publish a version that is 0.1.17?
The 0.2.0 version has big API changes compared to last 0.1.16 version, however there are some bugs being fixed prior to those API changes. For those who is not migrating to 0.2.0 yet, the 0.1.17 version could nice. What do you think? Thx! = )

**Comment by cpx86** [comment]
👍 I think this makes sense to do if there are important bugfixes. Basically the versioning scheme we have for 0.x.x is kind of a shifted semantic versioning, so major changes bump the minor number and small fixes bump the patch number. In the same spirit, I think it makes sense to fix bugs on 0.1.x until we have another bump on the minor version number.

**Comment by alexeyzimarev** [comment]
It's been more than a year, shall we focus on the next version instead? It doesn't seem obvious how to bring all the bug fixes to the older version, especially after the API change. I'd suggest for those who use ProtoActor to upgrade to the latest version.

**Comment by alexeyzimarev** [comment]
I propose to close this one due to lack of demand. @PotterDai do you agree?
