### ISSUE TITLE
IClusterProvider.DeregisterMemberAsync is not used anywhere

### ISSUE THREAD

**Issue by alexeyzimarev** [AsynkronIT/protoactor-dotnet#440]
The `DeregisterMemberAsync` method of the `IClusterProvider` interface is not called in the whole codebase. I am not sure if it is correct since when the cluster shuts down, I would expect that the node is unregistered. 

Right now, all remaining nodes try to connect to the node that was gracefully shut down, endlessly.

**Comment by jrouaix** [comment]
Hoo perhaps related to https://github.com/AsynkronIT/protoactor-dotnet/issues/403 !

**Comment by alexeyzimarev** [comment]
I was wrong because despite the interface member is never called, when Consul `Shutdown` is called, it deregisters the code.

But the issue from #403 indeed remains, since the killed node never gets deregistered and all nodes keep trying to connect. That's because the actor kind is registered in Consul and it never gets removed unless it is removed manually.
