### ISSUE TITLE
I try to use in aspnetcore API with DbContext di！But failed

### ISSUE THREAD

**Issue by gainorloss** [AsynkronIT/protoactor-dotnet#457]
Can u show me a sample ，i would like to use it in my project！

**Comment by alexeyzimarev** [comment]
A sample of what? Show what you have tried and where you have failed, at least.

**Comment by gainorloss** [comment]
I have used examples/DependencyInjection for reference to make my case  aspnetcore webapi  about using entityframeworkcore dbcontext,but failed in injecting the dbcontext.This is my repository :https://gitee.com/gainorloss_259/Zj.ActorSample.git。Glad to get u's help.

**Comment by alexeyzimarev** [comment]
The link doesn't work.

**Comment by alexeyzimarev** [comment]
I tried to check the code but accessing gitee is very very slow and there're no details on what exactly doesn't work. I am closing it for now, feel free to open it again when you can provide more details about your problem.
