### ISSUE TITLE
how can I catch unhandled exception on the ReceiveAsync(context)

### ISSUE THREAD

**Issue by Newp** [AsynkronIT/protoactor-dotnet#459]
`
        public async Task ReceiveAsync(IContext context)
        {
            throw new Exception();
        }`

when exception occurs on the IActor.ReceiveAsync(IContext context) 

how can I catch this exception or message?

context.Message deliver only restarting, no reason

thanks

**Comment by rogeralsing** [comment]
The reason is propagated to the supervisor of the actor.
This means the parent actors child supervisor will get the reason and decide what to do, restart, ignore etc.

This is a heritage from Akka, which I am not so sure we should stick to in the long run

**Comment by alexeyzimarev** [comment]
If the failed actor is a child of some parent, the parent actor will receive the `Failure` system message, which has the reason. If the failed actor belongs to the root context, the supervision strategy will be getting the reason, as Roger wrote.
