### ISSUE TITLE
Headers to store user token?

### ISSUE THREAD

**Issue by sudsy** [AsynkronIT/protoactor-dotnet#473]
I am considering using headers to store a bearer token for the user who is responsible for a particular message. I have used a similar approach in Orleans and it works well. Each Actor/Grain can check the token to see if the user is authorised to perform the action or enable features. 

I am wondering if there is a different way to handle this in the protoactor world?

It would be very useful to have these headers available to the Started message too so there is context around who started the actor and a decision can be made about where to retrieve persisted data from. It seems at least for Actors spawned by Cluster.GetAsync, there isn't a way to pass headers. would it be acceptable to pass any headers that are available on the sender context by default or is this an anti-pattern in your opinion?

**Comment by alexeyzimarev** [comment]
Proto.Actor has headers in the message envelope. For example, the OpenTracing lib uses headers to pass trace id and span id.

Not to answer the headers issue directly, I don't think passing the bearer token is the best idea. Why don't you complete all the authentication work on the HTTP API side? That's what HTTP API endpoints are for and we have extensive tooling available to do that kind of job easily. The user id is not metadata, pass it as part of the message and use to check the authorisation.
