### ISSUE TITLE
Get rid of net452 build target

### ISSUE THREAD

**Issue by alexeyzimarev** [AsynkronIT/protoactor-dotnet#485]
Today, the .NET Framework 4.5.2 build target creates too many impediments for updating dependencies. Apparently, many libs like SQLite and tons of Microsoft own libs are .NET Standard 2.0 only.

I could suggest stopping to support .NET Framework 4.5.2 and to support .NET Standard 2.0 only.

**Comment by cpx86** [comment]
I'm all for this - supporting anything below 4.6.1 isn't necessary. @alexeyzimarev up for submitting a PR? :)

**Comment by alexeyzimarev** [comment]
Yeah, I started by simply removing a couple of remaining `async void`s in the scheduler but ended up doing more, have it almost ready. Will submit soon.

**Comment by alexeyzimarev** [comment]
@cpx86 in my PR I removed 4.6.1 target as well, leaving only .NET Standard. Is it a good move? I would say yes, it allowed me to use the latest version of Sqlite client library without an ugly `#if`. If we need to ensure that everything works with 4.6.1, I can change test projects to have two targets.
