### ISSUE TITLE
Tip on how to perform server streaming

### ISSUE THREAD

**Issue by metscore** [AsynkronIT/protoactor-dotnet#489]
I've been trying to figure out how it would work with a server side streaming solution together with Proto.Actor for a substantial amount of time now, and I'm still not seeing the finish line.. (There is not too much information on this subject on the internet from what I gather)

Background
I've been requested to create an instrument server that handles different hardware (hw) devices remotely. The interfaces (created by someone else) are set and I have implemented a working client server solution for this purpose using proxies on the client side and a reflection based automation handler on the server side that is agnostic of the actual calls. This all works very well for methods, functions and properties of the interfaces, but the interface developer have also used events for notification on hw state changes, such as I/O state changes and voltage trip circuits and this is where the problem begins for me.

On the client side of my instrument server my thought have been to just send some kind of `StartListeningToEventsRequest` (when someone using the instrument client is attaching to the interface event) and somehow create a server side streaming call. This streaming call would continue with every state change on the hw side until the user of the instrument client disconnects from the event and my instrument client would simply stop listening to the instrument server side generated events and the stream is discontinued.

I've seen a few example of this being done using vanilla gRPC but have a hard time getting my head around on how to perform this integrated with Proto.Actor.
(I've been trying to study the code from @sudsy on #444 but have been unable to get my dense head around that codebase)

Someone might argue why I use Proto.Actor for this application in the first place and that's a valid argument.  However, since I did not know any better I started using Proto.Actor and liked it a lot and thus kept on using it as opposed to rewriting the application using vanilla gRPC.

With this issue I was hoping that someone would care to share their knowledge, or just point me in a good direction for some code snippets on how to set up a server streaming call with Proto.Actor to a client. My fingers are sore from googling so any, any tiny bit of help is greatly appreciated. 

Have a great day!
Magnus,

**Comment by metscore** [comment]
Update
I've tried the crude hack of actually starting a gRPC server on a different port in my Proto.Actor based instrument server. There are very few lines to this and it seems to work.

It obviously feels inherently wrong, so I would prefer not to do it like that, but I can't seem to find the missing link that makes it all work with the Proto.Actor framework.
Until I'm struck by genius or someone enlightens me I'll use this hack moving forward.    🤕

**Comment by sudsy** [comment]
Hi Magnus,

The solution I came up with in #444 allows you to run Proto.Actor on a client that can't expose a port to connect back to. It allows the client to make a connection to the Proto.Actor server and communicate as if it was another regular Proto.Actor server. 

This gives the benefits of being able to move code easily between client and server components.

The advantage of the approach that you have selected (starting a gRPC server on a different port) is that you can define the interface between your clients and your service that is independent of the Proto.Actor framework this will mean that you can change the underlying implementation to a different framework in the future if you see fit. 

Depending upon the situation, each option has it's benefits IMHO. given that my solution is really not ready for public consumption it may sway your thinking.

**Comment by metscore** [comment]
Hello Sudsy,

First of all, thank you very much for your reply !

For me it has not been so much of a decision process but more of a "getting something to work" to more forward with the entire system that I'm creating.
Since the approach with starting a gRPC server takes very little code and as far as I understand doesn't have significant drawbacks I'll stick with this solution for now.

I hope your suggested solution makes it into the framework for easy usage of this kind of concept in the future.

King regards
Magnus

**Comment by metscore** [comment]
Going with gRPC server for now so this "corner case" is probably not worth the development effort since I assume there are more important tasks at hand for the limited development resources available.
