### ISSUE TITLE
StopAsync has issues

### ISSUE THREAD

**Issue by alexeyzimarev** [AsynkronIT/protoactor-dotnet#492]
When I worked on making remote tests to use the test node that runs in Docker, I got logs from the test node on my screen. I also followed the suggestion from my IDE to use `StopAsync` instead of `Stop` in tests.

After that, tests started to randomly fail and also reliably fail in the pipeline.

When using `Stop`, the remote test node produces a lot of logs following the actor termination.

When using `StopAsync`, I only saw the log entry from the actor itself, saying "stoping" (I put the log there) and nothing happened further. I am not sure what happens since the code for `StopAsync` rather makes sense. It must be something with the handling of `Future`s.

**Comment by rogeralsing** [comment]
Nothing obvious going on here. it asks the future to watch the pid being stopped.


```
        public Task StopAsync(PID pid)
        {
            var future = new FutureProcess<object>();

            pid.SendSystemMessage(new Watch(future.Pid));
            Stop(pid);

            return future.Task;
        }
```

**Comment by rogeralsing** [comment]
Could potentially be related to the "complete task on different thread" issue we had earlier?

**Comment by alexeyzimarev** [comment]
That was supposedly solved by adding this:

```csharp
_tcs = new TaskCompletionSource<T>(TaskCreationOptions.RunContinuationsAsynchronously);
```

**Comment by alexeyzimarev** [comment]
The ClusterStabilityTest project executes a lot of requests using grains, all of them go via `RequestAsync` and it works fine. Not sure why `StopAsync` can cause any issue. I also looked at the code and it seems straightforward.

**Comment by alexeyzimarev** [comment]
Closing it for now.

**Comment by sfmskywalker** [comment]
I stumbled upon this issue while experiencing something similar (if not the same).

- I have a grain that I want to stop from external code using a grain client.
- When the grain receives the "stop" message, it calls `await Context.StopAsync(Context.Self)`
- That call never returns.

When I change the code to `Context.Stop(Context.Self)`, it returns immediately.
