### ISSUE TITLE
Tag the repo with 0.2.0 to enable SemVer for new packages

### ISSUE THREAD

**Issue by alexeyzimarev** [AsynkronIT/protoactor-dotnet#495]
I moved the CI pipeline to GitHub Actions and all seem to work as expected.

I also added minver so versions for assemblies and packages will be correctly generated.

However, minver now generates 0.0.0-alpha versions for new builds. That's because the latest release (0.2.0) was not tagged.

I have no permissions to tag the repo here. Asking people with permissions to run something like

```
git tag 0.2.0 33a0e2784514b110793f626d11a7a76db895f0c2
git push --tags
```

it's close enough to 0.2.0.

**Comment by alexeyzimarev** [comment]
For now, publishing NuGet packages is commented out. I will uncomment the job when the repo will get the release tag for 0.2.0.

**Comment by rogeralsing** [comment]
Done

**Comment by alexeyzimarev** [comment]
Thanks 👍
