### ISSUE TITLE
Port BoundedMailbox to C#

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#5]
The bounded mailbox has some nice properties in terms of low GC overhead.
It would be good to have the same for C# too.

**Comment by cpx86** [comment]
Started to have a look at this. The BoundedMailbox in Go uses the RingBuffer package, based on the bounded MPMC queue described here: http://www.1024cores.net/home/lock-free-algorithms/queues/bounded-mpmc-queue

There is a .NET implementation of that algorithm here: https://github.com/alexandrnikitin/MPMCQueue.NET
The code looks very solid to me - should we bring it in?

**Comment by rogeralsing** [comment]
Go for it! , it should be fairly easy to find out if it is OK by using it in the ping-pong benchmark.

**Comment by lust4life** [comment]
Don't know if it's appropriate to ask here, to see if you guys could give me some clues about [the usage of `Volatile.Read/Write` in MPMCQueue](https://github.com/alexandrnikitin/MPMCQueue.NET/issues/1) which had been used[ here](https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Mailbox/MPMCQueue.cs#L76)  in protoactor. @rogeralsing  @cpx86

**Comment by lust4life** [comment]
maybe this ([TryDequeue return True but get null result](https://github.com/alexandrnikitin/MPMCQueue.NET/issues/2)) will affect ProtoActor ?
