### ISSUE TITLE
Remote performance - 2.5 mil msg/sec

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#50]
As of yesterday, Remote performance in Proto.Actor .NET is now slightly better than the Go counterpart.

2.5+ million messages per sec in .NET 
vs 
2.4+ million messages per sec in Go

Which puts us on par with ZeroMQ.

This can be seen in contrast to the performance of Akka NET
https://github.com/akkadotnet/akka.net/issues/2378#issuecomment-277520209

We are now more than 50 times faster over the network, with version tolerant serialization and cross platform communication.

**Comment by mastorm** [comment]
Good work @rogeralsing & contributors!

**Comment by frankbolero** [comment]
Very nice work indeed @rogeralsing + contributors! May I ask what the hardware specs is needed to achieve these numbers?

**Comment by cpx86** [comment]
@frankbolero These benchmarks are on a modern dev laptop with a Xeon E3-1505M@2.80GHz. I don't think RAM and disk should matter much.

Would be nice to do some real benchmarks on actual server hardware :)

**Comment by mastorm** [comment]
Is the benchmarking included in the sln? I have a Xeon E5-4607 based server(long live ebay) which i could use to benchmark.

**Comment by cpx86** [comment]
@mastorm Yes they are all in the "examples" folder.

**Comment by rogeralsing** [comment]
@mastorm the different benchmarks we have are:

* RemoteBenchmark - 2.5 mil msg/sec on my machine
* InprocessBenchmark - 85 mil msg/sec on my machine
* SpawnBenchmark - 0.9 sec on my machine

**Comment by rogeralsing** [comment]
The tests should be run with release mode and with server GC enabled (settings included in projects)

**Comment by cpx86** [comment]
@mastorm Have you had time to run any benchmarks on an actual server? Would be interesting to see how it performs :)

**Comment by rogeralsing** [comment]
For anyone interested in this topic, the current numbers are 2.9 mil msg/sec for .NET
