### ISSUE TITLE
Cluster.GetAsync can return wrong kind of actor

### ISSUE THREAD

**Issue by sudsy** [AsynkronIT/protoactor-dotnet#516]
## Expected Behavior

When calling 

```
 var (firstActor, firstStatusCode) = await _cluster.GetAsync("default", "firstKind");

 var (secondActor, firstStatusCode) = await _cluster.GetAsync("default", "secondKind");

```

I would expect firstActor and secondActor to refer to instances of their respective kinds.

## Actual Behaviour

secondActor refers to the same actor as firstActor even though it is the wrong kind.

I can see why that is the case, but I think there is a case for namespacing each cluster kind so that the real id of the actors above would be firstKind/default and secondKind/default or throwing an error when the request for the second kind returns an actor of a different kind.

**Comment by cpx86** [comment]
Nice catch. I agree this isn't a very nice behavior. I think I would be in favor of throwing an error if the kind is different - if you end up requesting a grain that already exists with a different kind I would say that's likely to be a bug in the user code, which would be good to stop from happening.

@rogeralsing Thoughts?

**Comment by rogeralsing** [comment]
hmmm.

Random thoughts.
Should we ever allow a grain to be of multiple kinds? e.g. just multiple interfaces on the same instance?

If not. and if we want to have unique name per kind, the ugly but simple solution might be to just concat kind + name in the grain lookup code.

e.g the key would be "firstKind.default"

That might be most in line with rule of least surprise?

**Comment by alexeyzimarev** [comment]
It's not that ugly actually.

**Comment by sudsy** [comment]
I think the "firstKind.default" solution is good, but I am wondering if we should add a prefix character, something like "@firstKind.default". and then restrict other id's from starting with "@".

The reason I suggest it is due to a design issue I have encountered with #444 which I will document in a moment.

**Comment by rogeralsing** [comment]
Should we go for the kind+identity as key then?

**Comment by sudsy** [comment]
I'm happy with that!

**Comment by rogeralsing** [comment]
Working on this now. The new `MongoIdentityLookup` already works this way now.

**Comment by mhelleborg** [comment]
Should be OK now, after rewriting how we store spawns in the identity and placement actors.
