### ISSUE TITLE
Breaking changes in 0.3

### ISSUE THREAD

**Issue by dominikjeske** [AsynkronIT/protoactor-dotnet#517]
Is there any list of breaking changes and how to update to 0.3?

After update I have:
1. No Stop/StopAsync method on PID
2. ProcessRegistry no Instances property
3. Props.FromProducer() changed

**Comment by alexeyzimarev** [comment]
It's described in the PR. Unfortunately, we haven't managed to set up the changelog, but all samples are updated with the latest code changes, so you can find there how it works now.

We replaced static instances by the ActorSystem, you might choose to have more than one or keep it as a singleton. Start and Stop are moved the context.

**Comment by dominikjeske** [comment]
Ok I have found each change but it would be nice when breaking changes would have some docs
