### ISSUE TITLE
Make the Children collection public

### ISSUE THREAD

**Issue by alexeyzimarev** [AsynkronIT/protoactor-dotnet#524]
It is very useful for the parent actor to get a hold on its children at any time, to know how to talk to them. Now, the `Children` collection is private although it's read-only, so exposing it would do no harm.

Is there a reason to hide it? We usually have to keep another collection on the side to know the PIDs of child actors in the parent, which increases memory consumption.

**Comment by rogeralsing** [comment]
Public where? 
It is public on the IContext:

<img width="853" alt="Skärmavbild 2020-09-06 kl  11 22 43" src="https://user-images.githubusercontent.com/647031/92322725-55b2c900-f033-11ea-9448-8a0f22683254.png">
