### ISSUE TITLE
Cluster can return a terminated actor

### ISSUE THREAD

**Issue by alexeyzimarev** [AsynkronIT/protoactor-dotnet#526]
I added the receive timeout handling to normal actors, similar to how grains work. So, cluster actors now stop after 90 seconds receive timeout. Everything is fine. However, I observed that in some cases, I get an actor from the PidCache, which has been already terminated.

To understand when actors get removed from the PidCache using the PidCacheWatcher, I also added my own actor to the watchers list.

I stored all the events and the timeline looks like this (example):

| Event | Timestamp |
| ----- | ------- |
| HelloTerminated | 2020-07-04 15:08:28 |
| HelloStopped | 2020-07-04 15:08:26 |
| HelloTimedOut | 2020-07-04 15:08:25 |
| HelloRequested | 2020-07-04 15:06:55 |

Here I can see that the termination message reaches the watcher two seconds after the actor has stopped. It means that the actor remains in the PidCache for some time and can be potentially returned in `GetAsync`. When we try sending a message to such a zombie actor, it disappears. When using request-response, we get a timeout. 

And here is the log:
```
04 Jul 2020 15:08:28.971
 Unable to send message to the remote actor { "Address": "10.244.3.82:12000", "Id": "Hello-686" }
04 Jul 2020 15:08:25.993
 Actor { "Address": "10.244.3.82:12000", "Id": "Hello-686" } stopped
04 Jul 2020 15:08:25.943
 Actor { "Address": "10.244.3.82:12000", "Id": "Hello-686" } shutting down due to timeout
04 Jul 2020 15:06:55.915
 Response from { "Address": "10.244.3.82:12000", "Id": "Hello-686" }: { "Message": "Hello from node 10.244.3.82:12000" }
04 Jul 2020 15:06:55.781
 Actor started { "Address": "10.244.3.82:12000", "Id": "Hello-686" }
```

Two concerns here:
- How to avoid getting a zombie actor from `GetAsync`?
- Why does it take so long for the `Terminated` message to reach the watcher?

In case of a multi-node cluster, we could, however, expect the termination message to be delayed anyway. I am not sure if the zombie actor situation can even be fixed in this scenario. Unless, when the remote node receives a message to a zombie actor, it would reply to the sender node that the actor doesn't exist. Actually, it should work like this with one node too. Now it times out and it takes a while, also we don't really know why it times out. If we return an error saying that the actor doesn't exist, we either can handle respawning internally or let the client repeat the Get/Request operation. Returning to the client, however, won't solve the "send to zombie" situation.

**Comment by rogeralsing** [comment]
Done
