### ISSUE TITLE
Cluster restructuring

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#532]
Some efforts to undertake

## Creste a pluggable ID resolver infrastructure.

Instead of having a built in distributed hashtable for ID lookups, lets abstract this away to an ID resolver interface.
This way, we could use e.g. Redis or Memcache as storage.

This module would be dependant on cluster events such as join/leave events.
It should also be aware of cluster leader so that a specific node can take the role of updating the DB if needed.

We can likely augment the cluster events / infra to contain leader information.
And/Or, update some cluster infra to allow us to take a lock of some sort.

## Extract the core logic of the Cluster so that it becomes more testable

This goes hand in hand with the task above, but it would also make life easier if we could have a test spec for cluster, which we then run against the different cluster and id providers to verify correctness.

cc @alexeyzimarev  @cpx86 

Any thoughts / reflections on how to go about this all?

**Comment by rogeralsing** [comment]
I've made it possible to disable the PidCache for cluster.
The idea is to make sure that everything works 100% correct w/o cache, then we can enable caching ontop of this.
Easier to pinpoint issues in this case

**Comment by rogeralsing** [comment]
![cluster](https://user-images.githubusercontent.com/647031/90410746-0835e280-e0ab-11ea-914e-6c224f1152ca.png)

Current progress.

### IIdentityLookup
Responsible for returning a PID given an actor Identity/name

This allows us to plug in completely different cluster providers, eg. if you want to store all id->PIDs in mongodb, this is now totally possible

### Actors
Old partition actor per kind is now removed.
Instead each node has one PartitionIdentityActor and one PartitionPlacementActor.

PartitionIdentityActor is responsible for the lookup of ID->Pid, this is what the default IIdentityLookup uses 

PartitionPlacementActor is responsible for spawning actors on a node in the cluster. it is also responsible for transferring ownership if the ID owner of an actor leaves

### Leader Election
Cluster now does leader election, this is based on Consul session locks, the node that acquires a lock becomes the leader.

### Banned Members (not devs :D )
When a node fails, other nodes will consider it to be failed and ban it from the cluster.
This is done live whenever a topology change occurs.
But in order to feed correct information to new nodes, we also let the leader store this in the consul session.
So that newly joined nodes can read and see what previous members have been banned.

This is mostly a safetynet to prevent nodes that previously failed but later recovered tries to re-join.

We do not allow failed nodes to rejoin simply because that will mess up cluster state, lookups and placements.

**Comment by alexeyzimarev** [comment]
What happens with a failed node then? If a cluster runs in an unstable network, would it not eventually ban all the nodes and prevent them from rejoining?

**Comment by rogeralsing** [comment]
Each node has a guid to identify it's instance id, if a node fails it should preferably stop itself and be rebooted by outer infrastructure (docker/kubernetes/whatever). this will give it a new instance id, even if it has the same port and host.

This is the same as what both Orleans and Akka does. don't let corrupt state back into the system. let it crash and start fresh.

**Comment by alexeyzimarev** [comment]
Yeah, I agree. That’s what RabbitMQ suffers from, the partitioned cluster state.

**Comment by rogeralsing** [comment]
btw. Running a local 100 nodes cluster with nodes being added every second, and still have stable lookups to the actors :-)

This needs some serious battle testing but so far it looks very nice

**Comment by alexeyzimarev** [comment]
I am certain that we’ll battle test it soon enough :)

**Comment by rogeralsing** [comment]
This is done
