### ISSUE TITLE
MongoIdentityLookup finishing touch up

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#543]
We now have the MongoIdentityLookup implementation to allow us to store actor placements in MongoDB:

https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster.MongoIdentityLookup/MongoIdentityLookup.cs

From this line forward, it is subject of potential race conditions:
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster.MongoIdentityLookup/MongoIdentityLookup.cs#L57

e.g. if two requests ask for the same identity at the same time, they might end up activating it twice.

To prevent this, I'd like to have some form of pessimistic locking on Identity.
e.g. if the identity does not exist in Mongo. the first request to end up here, should lock that ID.
And by locking, I mean either locking at DB level or write some dummy data for that entry while the activation takes place.
And replace that with the final result once it's done.

If we use some form of compare and swap, we might still activate multiple times, even if only one of the lookups gets written to DB.
So the first request should claim the ID, globally, not just for the current node. 

Open for ideas on implementations

**Comment by rickevry** [comment]
I am still a protoactor noob but isn’t the whole point of using the actor model to eliminate race conditions? Can’t you implement MongoIdentityLookup with actors instead?

**Comment by rogeralsing** [comment]
Yes it is, on a process level. the race condition in this issue is between nodes querying the for the same document.
Then one might ask, why don't we use an actor on one node to handle this. because the IdentityLookup is at the heart of the system to know where other actors live, catch 22.

**Comment by rickevry** [comment]
So, what is the purpose of MongoIdentityLookup, what use case is not covered by PartitionIdentityLookup?

**Comment by rogeralsing** [comment]
>So, what is the purpose of MongoIdentityLookup, what use case is not covered by PartitionIdentityLookup?

It is an alternative strategy for actor placement.
The benefit of the Mongo strategy is that it is less sensitive to topology changes, it doesn't matter much if nodes leave or join, the DB will in the end be the source of truth of where things are.

The partition lookup is the default because it does not rely on any form of persistent store for placement.

**Comment by rogeralsing** [comment]
Another added benefit of the Mongo provider is that you can actually debug your system easier, just by checking the Mongo collection where each identity is currently placed

**Comment by rickevry** [comment]
I guess this is a robustness vs performance problem and that it all depends on the constancy model used in mongodb. My experience is that the performance hit to get mongo consistent is way too high. To get around the consistency problem, many projects implement their own locking mechanism with some kind of shared state (like Hazelcast). And then we are back where we started...

From working a lot with Kafka, I think that sharding is the only way to go. My magic trick to simplify topology changes is to set a fixed value for the maximum number of shards/partitions.

Let’s say that cluster_maxShards equals 128. The hasher will then always give me a number in that range. A simple routing table is then used to map all the shards against available nodes. Finally, the routing table is synchronized between nodes.

I am still working my way through the source of Proto.Cluster and you know this stuff much better than me. Maybe I can add some value when I understand the insides.

**Comment by alexeyzimarev** [comment]
I think it all depends on the number of actors. This code in particular aims for a production system with about half a million actors in the cluster. So, a simple replica set would work. If we start thinking about tens of millions of actors, it might not work.

**Comment by rogeralsing** [comment]
>I guess this is a robustness vs performance problem and that it all depends on the constancy model used in mongodb.

there is a in mem cache in between, so the DB is only used whenever the cache is either empty, or the PID in the cache does not respond in time and that cache entry is invalidated.

Depending on the nature of the system you build, the performance hit may or may not be noticable.
For example if you have very long lived grains, the placement will not change that often, and there are less cache invalidations and DB interaction.

A realworld case of this is gps tracking of vehicles, a vehicle, e.g. a car might be on the road for hours, and such actor is then long lived and it's placement can be cached for all of this time.

**Comment by rogeralsing** [comment]
>Let’s say that cluster_maxShards equals 128. The hasher will then always give me a number in that range. A simple routing table is then used to map all the shards against available nodes. Finally, the routing table is synchronized between nodes.

This is basically what the PartitionIdentityLookup does. 
See https://proto.actor/docs/cluster-partitions/ for some info on the strategy there.

This is however not fixed, as a fixed hash would take out at least one entire partition incase that node goes down (or, everything would have to be rebalanced and moved around to adjust for the skewing of the hash ring)

The PartitionIdentityLookup adapts in these cases and moves ownership of identities to the new algorithmic owner of an ID.
Actors that lived on the downed node are ofcourse lost, but will be re-activated elsewhere when messages are sent to them.

**Comment by rogeralsing** [comment]
This has been completed, closing
