### ISSUE TITLE
Cluster interface names

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#555]
We have `IClusterProvider` and `IIdentityLookup`.
IClusterProvider doesn't really describe what it does, it manages the member status changes of the cluster.
What members are there and the health status of those members.

IIdentityLookup is more on point, it resolves the placement of a virtual actor identity.

But maybe cleaner names would be `IClusterMemberProvider` and `IActorPlacementProvider` or something along those lines.

Let's fix all these things before going 1.0 here

**Comment by alexeyzimarev** [comment]
I have to admit that actor placement provider sounds awkward :) Is there anything more human-friendly we can come up with?

**Comment by rogeralsing** [comment]
MemberStrategy + PlacementStrategy ?

Maybe none of this is a major issue, but still, if we find something better, let's go with that before v1

**Comment by alexeyzimarev** [comment]
Strategy is a pattern, basically we already have a few strategies, which look alright.

I like that the persistence abstraction is called IPersistence. Not any manager, provider or whatever. It makes sense and easy to understand.

Can’t come up with any naming today but we can brainstorm tomorrow:)
