### ISSUE TITLE
Replace mutable Lists/Arrays with Immutable versions

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#561]
Proto.Actor have been focusing on performance and micro optimizations from day one.
I'd like to challenge that now.

Proto.Actor is _fast enough_.
Whenever there is IO involved, the last CPU cycles that we gain by any optimization becomes negligent. 

Therefore, I'd like to see that we transition to ImmutableList/ImmutableArray/ImmutableHashSet where it makes sense.
e.g. Cluster MemberList could be altered this way. we are leaking mutable references in many places, and even if we don't have bugs, it's hard to reason about, or trackdown when such bug appears.

ps. we can also use immutable records now with C# 9

**Comment by rogeralsing** [comment]
cc @mhelleborg

**Comment by mhelleborg** [comment]
I must say I agree that some details might be better off optimized for ease of use and correctness over micro-optimizations. One example is IContext, which is mutable and re-used between requests. This is fine as long as you only process in the correct actor context, but callbacks and storing the context for a message will lead to incorrect behavors. 

Having a separate message context might give a better user experience, and could act as an effectively immutable value object for the message. It should still only be a single additional object allocation,  so not very costly.

**Comment by mhelleborg** [comment]
@rogeralsing I can create an issue for the IContext seperate of this one, then we can iterate on a design :)

**Comment by umitkavala** [comment]
I just start do changes on Cluster. Its my first PR :) sorry for mistakes. Looking forward feedbacks. 
I couldn't see tests for Cluster. Good time to create tests as well?

**Comment by mhelleborg** [comment]
@umitkavala There are created cluster tests in https://github.com/AsynkronIT/protoactor-dotnet/pull/559, have a look at those first :) It could always be better covered, so feel free to add to them.

**Comment by umitkavala** [comment]
@mhelleborg I'll do. thanks 👍. How can I add my change to #559. 
Sorry for this silly question but this is my first OSS contribution. How can I do changes/add tests? Just clone that branch and do changes?
