### ISSUE TITLE
Pass ActorSystem in Actor Producer

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#586]
The current design of Props.FromProducer looks like so:

```csharp
var props = Props.FromProducer( () => new MyActor() );
```

What if we make an overload that allows passing the actor system as an argument?

```csharp
var props = Props.FromProducer( system => new MyActor(system....) );
```

This would allow us to do things like:

```csharp
var props = Props.FromProducer( system => new MyActor(system.Extensions.Get<ILogger>()) );
```

The current Logging support is lacking due to having this `static ILog Log` field, meaning we have little control over logging in tests.
Allowing the producer to get access to extensions would mean we could initialize readonly fields inside the actors instead of always relying on messaging, such as `Started` or `ClusterInit`.

**Comment by rogeralsing** [comment]
Or. we could even pass in an `IContext` for the actor. so the actor gets access to its own `IContext` in ctor.
(Which is a bit weird as there is no message or anything yet. so maybe `ISenderContext` or `IInfoContext`

Thoughts?

**Comment by alexeyzimarev** [comment]
I like `ActorSystem` to be a parameter for the producer.
