### ISSUE TITLE
Proto.Actor.Abstractions

### ISSUE THREAD

**Issue by dominikjeske** [AsynkronIT/protoactor-dotnet#591]
I like to have separation in my projects and I'm wonder can you consider to move some base abstractions (PID, IActor ect) to separate nuget named in MS convention as Proto.Actor.Abstractions?

**Comment by rogeralsing** [comment]
Hi @dominikjeske,
This is not possible for a few different reasons. e.g 
PID is partially a protobuf message and partially custom code. 
IActor needs ReceiveAsync, ReceiveAsync needs IContext etc. a lot of things belong together.

What would the added value be? 
if you want to use a PID, you still need all of the other bits.

**Comment by dominikjeske** [comment]
After second thought You probably have right - in the end we will have all bits. I just tried to over engineer ;)

**Comment by dominikjeske** [comment]
@rogeralsing  I would like to reopen this because situation just have changed with the latest version of Proto.Actor. It is now netstandard 2.1/net 5.0. I have references in my contracts to PID, IActor and couple of base types and I could not update those projects. It would be ideal to have those base contracts in net standard 2.0 and leave rest in 2.1/net5. I could give a try with PR but before start can you rethink this in this new light?

**Comment by rogeralsing** [comment]
I would say the main issue would be PID. which is both a proto generated object, and has custom code coupled with all the other infrastructure.
I personally don't see any approach from the top of my head that would make that work.

But I could be wrong, so if you find a way I would be interested to see it

**Comment by dominikjeske** [comment]
@rogeralsing I checked the code for extracting Abstractions and it looks like it will not be easy. I have an observation that only one thing is making this package not compatible with NetStandard 2.0 - IActorSystemExtension and default implementation of interface. Can You consider to move this to implementation or this is must have? 
There is also IsExternalInit.System.Runtime.CompilerServices but I think other nuget package can be used for this https://www.nuget.org/packages/IsExternalInit and it is netstandard 2.0.
