### ISSUE TITLE
[Not a bug] Potential performance improvement in HashedConcurrentDictionary

### ISSUE THREAD

**Issue by MiloszKrajewski** [AsynkronIT/protoactor-dotnet#595]
I've noticed that `HashedConcurrentDictionary` uses `1024` as a size of first level hashtable.
From what I remember this size should be a prime number to prevent clustering (and, in this case, lock congestion).

Some explanation:
https://cs.stackexchange.com/questions/11029/why-is-it-best-to-use-a-prime-number-as-a-mod-in-a-hashing-function

On the other hand this might NOT be a case because keys are strings, and hash of string can be already properly "de-clustered".

I don't know. Just a thought.

**Comment by rogeralsing** [comment]
Many thanks, I'll take a look at it.
There is an easy way to verify the impact of this, the SpawnBenchmark spawns millions of actors, and any change to the HashedConcurrentDict would be noticeable there.

**Comment by MiloszKrajewski** [comment]
I ran some tests and conclusion is:

`string.GetHashCode()` gives really good hash values: "$1" and "$2" produce hashes so different that chance of landing on the same partition is very low (thus low chance for lock congestion). Therefore tinkering with hash table size produces minimal effect a this addresses only cases of "not great hash value distribution".

Although, there is a bug in `GetPartition`:

```
private Partition GetPartition(string key)
{
    var hash = Math.Abs(key.GetHashCode()) % HashSize;
    var p = _partitions[hash];
    return p;
}
```

if `key.GetHashCode()` is exactly `int.MinValue` then `Math.Abs(...)` blows up with `System.OverflowException: Negating the minimum value of a twos complement number is invalid.`. Probability is 0.0000000233% and I still managed to get it ;-)

Changing it to: `var hash = (key.GetHashCode() & 0x7FFFFFFF) % HashSize` fixes the problem (and seems a little bit faster: no branching)

**Comment by rogeralsing** [comment]
This has been tried, no noticeable effect on the SpawnBenchmark, closing
