### ISSUE TITLE
Port Persistence to C#

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#6]
The persistence module needs to be ported over to C# too.

We need to come up with a plan how to use plugins in C#.
In Go, we use embedded fields, this is not available in C#.

I would like to avoid basing this kind of functionality on inheritance at all cost.
We did this in Akka.NET resulting in many many permutations of ReceiveActor, PersistentReceiveActor etc.

Suggestions?

**Comment by cpx86** [comment]
Given a receive pipeline like that which exists in Go right now, adding persistence without inheritance shouldn't be too difficult.

The main problem that I see is to find a suitable replacement for the mixin/embedded field. One option is to replace it with an interface that you need to implement, containing the ProviderState, EventIndex, etc. The downside of it is that the implementation of those properties will be forced upon each actor implementation. One way of making it a bit easier on the actor implementer is to wrap all of the embedded fields in a composed type.

So you would have something like the below. It is basically equivalent to the Go implementation except you need to "dot in" to access the persistence stuff, and the Actor needs to implement an auto-property from the interface. Thoughts?
```csharp
class MyPersistentActor : IPersistentActor
{
    public PersistenceState PersistenceState { get; set; }
}

public interface IPersistentActor
{
    PersistenceState PersistenceState { get; set; }
}

public class PersistenceState
{
    public ProviderState ProviderState { get; set; }
    public int EventIndex { get; set; }
    public IContext Context { get; set; }
    public bool Recovering { get; set; }

    public void Init(PersistenceProvider provider, IContext context)
    {
        ProviderState = provider.GetState();
        Context = context;
        Recovering = true;
        //... more init code
    }
}

Receive Using(PersistenceProvider provider)
{
    return context =>
    {
        switch (context.Message)
        {
            case Started started:
                break;
            case Replay replay:
                var p = context.Actor as IPersistentActor;
                if (p != null)
                {
                    p.PersistenceState = new PersistenceState();
                    p.PersistenceState.Init(provider, context);
                }
                break;
        }
    };
}
```

**Comment by rogeralsing** [comment]
Love it, your interface suggestion is as good as it gets in C# IMO.
I cant see any other non magic way of doing this with less code.

**Comment by cpx86** [comment]
Cool, I'll get to work on the receive pipeline first, then continue with persistence.

**Comment by rogeralsing** [comment]
This has been merged, closing
