### ISSUE TITLE
Can't install from myget

### ISSUE THREAD

**Issue by 0x53A** [AsynkronIT/protoactor-dotnet#64]
Hi,

when I try to add the package proto.actor via the myget feed, I get the following error:

```
Resolving packages for group Main:
 - proto.actor 0.1.0.56
 - System.ValueTuple 4.3.0
 - Google.Protobuf 3.2.0
 - NETStandard.Library 1.6.1
 - NETStandard.Library 1.6.0
 - proto.actor 0.1.0.51
There was a version conflict during package resolution.
  Resolved packages:
   - Proto.Actor 0.1.0.51
  Could not resolve package Proto.Mailbox:
   - proto.actor 0.1.0.51 requested package Proto.Mailbox: >= 1.0
   - Available versions:
     - (0.1.0.56, [https://www.myget.org/F/protoactor/api/v2])
     - (0.1.0.51, [https://www.myget.org/F/protoactor/api/v2])

  Please try to relax some conditions.
```

I was able to install it by just pinning the package versions. =)

(https://twitter.com/RogerAlsing/status/833675614360055808)

**Comment by cpx86** [comment]
Good catch! Will take a look at the build script.

**Comment by cpx86** [comment]
@0x53A Fixed now.

Apparently you need to set the project version before even running `dotnet restore`, otherwise the `project.assets.json` will get 1.0.0 as version, which is then used for setting the package dependencies. Because... that's obvious, right? 😉
