### ISSUE TITLE
Cluster PubSub

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#643]
Let's look into what the best way would be to introduce streams into ProtoActor cluster model.

a naive, from the top of my head implementation might be like so:

* A stream is a persistent virtual actor
* The stream actor has a set of subscribers, also virtual actors
* Whenever the stream actor receives a message, it delivers this message to all subscribers

We could add sugar APIs to just make this all easier to work with.
Deduplication, event versioning, etc.

**Comment by rogeralsing** [comment]
Some updates.

I have a WiP branch for this: https://github.com/AsynkronIT/protoactor-dotnet/tree/ClusterPubSub


WiP API:

```csharp
//PID subscriber
await system.Cluster().Subscribe("my-topic", pid);

//Virtual Actor Subscriber
await system.Cluster().Subscribe("my-topic", identity, kind);

//publish messages to the topic
await system.Cluster().Publish("my-topic", someMessage);    
```

Both vanilla actors and virtual actors can be subscribers to a topic.
If you have access to the cluster, you can publish to a topic.

Publish and Subscribers are currently fully linked in such a way that awaiting Publish guarantees that all subscribers have Acked the receive.

This should probably be configurable.

The topics can be persistent, meaning they can persist their set of subscribers upon subscribe and unsubscribe

**Comment by alexeyzimarev** [comment]
Are you planning to add Kafka adapters? :)

**Comment by rogeralsing** [comment]
Note to self, NATS.IO protocol https://docs.nats.io/developing-with-nats-streaming/protocol

**Comment by rogeralsing** [comment]
Maybe there should be a mediator that handles the publishing.
e.g. fire and forget publish via the mediator, but the mediator tracks what is sent or not, so that one can await the mediator to be completed.

**Comment by beatsm** [comment]
Could this be used as a signalr backplane?

**Comment by rogeralsing** [comment]
An initial working version of Cluster PubSub is now in dev branch
