### ISSUE TITLE
Parent in child actor is always null

### ISSUE THREAD

**Issue by raskolnikoov** [AsynkronIT/protoactor-dotnet#67]
When creating a child actor and in the child actors context calling the parent by typing "context.Parent" it is always null.

**Comment by cpx86** [comment]
Do you have some sample code?

You could take a look at the Supervision example; when I run it the child actor gets the parent PID on it's context set correctly.

**Comment by raskolnikoov** [comment]
I found out my problem. I was using  "Actor.Spawn()" instead of "context.Spawn()".

So I was wrong :)
