### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#7]
I want to base the initial cluster support on Consul.IO.
Making each Proto Actor process register themselves into Consul as services.
We can then simply use the Consul REST API to query for cluster changes.

Consul supports "blocking queries" where you get a token each time, and if you provide this token for the next call, the call will block until any changes occur.
This prevents polling, only returning once status changes.

This has some nice benefits:

We don't need to build any custom cluster code ourselves. (e.g. Paxos, Raft, or implement a gossip protocol).
All of the complexity is simply offloaded to a battle proven tested cluster software, and we piggy back on that.

It will work the same way for any language implementation.
(currently the Go implementation uses MemberList from Hashicorp, the lib that Consul is built ontop of.. ) 

Consul supports "Tagging" of services. this means that each Proto Actor process could provide tags when it boots up.
These tags could be used to describe "Roles". e..g. "Worker", "Frontend" etc.
This means we can have automatic placement of actors/grains across different roles.
Some actors/grains might only be available on a specific role.

Akka has similar support, but I don't think there is anything like this in Orleans(?)

**Comment by rogeralsing** [comment]
We are reworking the Cluster design to use the above mentioned Consul support for clustering.
This allows us to create a Proto.Actor cluster ontop of Consul.

As soon as the Go API is finished, work to port it over to C# will begin.

**Comment by rogeralsing** [comment]
The new Go cluster API is fairly stable now, an effort to start porting the code over to C# can begin

**Comment by mickdelaney** [comment]
We're using python & .net on kubernetes, would supporting etcd be significantly different than consul ?

**Comment by rogeralsing** [comment]
No that should be doable too, the ClusterProvider interface only need to detect changes in the registered nodes.
So it is built as pluggable for this very reason.

**Comment by rogeralsing** [comment]
This is the `ClusterProvider` interface from Go
```go
type ClusterProvider interface {
	RegisterMember(clusterName string, address string, port int, knownKinds []string) error
	MonitorMemberStatusChanges()
	Shutdown() error
}
```

See http://proto.actor/docs/golang/eventstream#usages for a visualization of how it works

**Comment by mickdelaney** [comment]
great!!! will start hacking soon ;-)

**Comment by rogeralsing** [comment]
Dependent on #74

**Comment by rogeralsing** [comment]
I've added the Proto.Cluster project to the solution and added the skeletons for the classes.

**Comment by rogeralsing** [comment]
This has been done in #91
