### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by cpx86** [AsynkronIT/protoactor-dotnet#71]
Test coverage is quite so-so at the moment, and should be improved.

I don't think 100% coverage is a target worth striving for, but there should be at least a few tests for each feature.

**Comment by cpx86** [comment]
A potentially useful source for figuring out what to test is this list of basic features that each port should support: https://gist.github.com/cpx86/bf396b02cf92996d0c42592d3e7ac8b1

**Comment by Exef** [comment]
Hi @cpx86, can I help you with this issue? Should I start from the top of your list or is there any particular area to be covered first?

**Comment by cpx86** [comment]
@Exef Awesome! Hmm I think in regards to that list, the areas where we lack coverage the most would be Router and Remote. Perhaps also EventStream and DeadLetter.

**Comment by tomliversidge** [comment]
@Exef did you start working on anything? I was considering having a look into the Router tests if you haven't started already

**Comment by tomliversidge** [comment]
I started Router tests: https://github.com/AsynkronIT/protoactor-dotnet/pull/120

**Comment by rogeralsing** [comment]
this is being actively being worked on and improved
