### ISSUE TITLE
Merge RouterProcess with the RouterActor's LocalProcess

### ISSUE THREAD

**Issue by cpx86** [AsynkronIT/protoactor-dotnet#72]
Currently there are two processes involved when using Proto.Router - the RouterActor and it's LocalProcess, and the RouterProcess which proxies system and management messages to the RouterActor, and sends other messages to the routees.

A problem with this is that we get two PIDs for the router, one for each process. This messes up the watch/unwatch functionality since any watch message would be for the RouterActor's LocalProcess, but the PID you get when you create the router is actually the RouterProcess

This should be merged so that we only have one Process involved. A way forward is to change the spawn logic so that instead of having a RouterProcess referencing a LocalProcess referencing a RouterActor, you would just have a RouterProcess referencing a RouterActor. The RouterProcess would need to handle the mailbox in the same way as the LocalProcess does though.

**Comment by rogeralsing** [comment]
closed in #241

**Comment by cpx86** [comment]
Haha I had completely forgotten that I wrote this issue :D
