### ISSUE TITLE
Enable atomic moves of ClusterIdentity activations between nodes

### ISSUE THREAD

**Issue by mhelleborg** [AsynkronIT/protoactor-dotnet#741]
It could be very useful to be able to move activations atomically, without dead letters or the chance that the identity will be activated on another node. This supports use cases such as local affinity, targeted draining of workloads to new nodes etc.

**Atomicity**
The atomic move will require updating the `IIdentityLookup` interface with a new method to support this. Ex: 
`Task<PID?> MoveAsync(ClusterIdentity clusterIdentity, PID from, Member to, CancellationToken ct);` ?
We will need to lock the ClusterIdentity while moving the activation, so no race conditions can occur.  This will also require new functionality in IdentityStorage.

**Forwarding**
In addition, if we want to prevent dead letters, we will need to have a mechanism for storing and forwarding messages while the move is in progress. This might be done with receiver middleware, or perhaps we can solve it another way. Open for suggestions here..

Ideally we would want to preserve order of messages, but that might be tricky to solve. When we update the available PID for that cluster identity, members will send their messages directly to the new activation. This might happen before the messages stored in the forwarding (old) actor have sent its messages to the new actor, and thus cause out of order processing. 

This is only going to be a problem if the sender has multiple messages in-flight though, request-response style communication should work fine.
 Open for suggestions of how we handle the cases where we have multiple messages in-flight.

**Comment by rogeralsing** [comment]
Local affinity 2.0 merged
