### ISSUE TITLE
Can Proto.Actor be used in a Unity app?

### ISSUE THREAD

**Issue by diybl** [AsynkronIT/protoactor-dotnet#776]
it there unity package for this project?

**Comment by alexeyzimarev** [comment]
No, there's no Unity package

**Comment by diybl** [comment]
> No, there's no Unity package

hope the client support the unity。
After all, unity is the most popular application in c#

**Comment by rogeralsing** [comment]
To my knowledge, Unity uses a modified Mono runtime with .NET Old and thus would not be supported.
If there is a need for this, the solution would have to come from the community as none of the frequent committers here are working with Unity (AFAIK)
