### ISSUE TITLE
Create protobuf protoc Grain generator

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#8]
In Go, we have this Protoc.exe generator: 
https://github.com/AsynkronIT/protoactor-go/blob/dev/protobuf/protoc-gen-typedgam/template.go

We need to have a similar for C#.
It should be possible to re-use the same Go generator and just switch out the template, no need to rebuild the actual generator in C#.

**Comment by raskolnikoov** [comment]
404 on the link

**Comment by cpx86** [comment]
https://github.com/AsynkronIT/protoactor-go/blob/dev/protobuf/protoc-gen-protoactor/template.go

**Comment by yindongfei** [comment]
404 again

**Comment by rogeralsing** [comment]
https://github.com/AsynkronIT/protoactor-go/blob/dev/protobuf/protoc-gen-csgrain/template.go

I'm working on translate the content to C# here. any day now
