### ISSUE TITLE
async / await using in Actor

### ISSUE THREAD

**Issue by koderhari** [AsynkronIT/protoactor-dotnet#80]
Hello, i have next problem.
I have .net core web application created from template (.net core 1.1)
In Configure method of Startup class i spawn actor and store PID in static field.
Then i send message to Actor in Controller Get Method.
Actor receive only first (firstly open page) and second (after refresh page) messages,
but next messages doesn't receive.
If i delete async, it works correctrly.
Is it bug or ProtoActor doesn't support async calling?
        
    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            var props = Actor.FromProducer(() => new HelloActor());
            pid = Actor.Spawn(props);
            app.UseMvc();
        }  
      // actor
       internal class HelloActor : IActor
        {
            public async Task ReceiveAsync(IContext context)
            {
                var msg = context.Message;
                if (msg is Hello)
                {
                    await Task.Delay(5000);
                    Console.WriteLine($"Hello {((Hello)msg).Who}");
                    context.Sender.Tell(999);
                }
            }
        }
       // controller
        [HttpGet]
        public IEnumerable<string> Get()
        {
            Startup.pid.Tell(new Hello
            {
                Who = "Alex"
            });
            return new string[] { "value1", "value2" };
        }

**Comment by rogeralsing** [comment]
I believe this is the problem:
`context.Sender.Tell(999);`

Proto.Actor works differently compared to Akka.NET.
When using `Tell` there is no `Sender` it is pure fire and forget. this is to avoid sending Senders over the wire when it is not needed.

Instead, we only pass the `Sender` when you use `Request` or `RequstAsync`
You can also use `Context.Respond` instead of `Context.Sender.Tell` to reply to the requesting actor.

**Comment by koderhari** [comment]
I have deleted 
`context.Sender.Tell(999);`
but it have resolved Null references error, 
and now it fires only one time, when starting application and call Action in controller first time.
Next times it doesn't work. If i test next code,  Actor work

```
 internal class HelloActor : IActor
        {
            public Task ReceiveAsync(IContext context)
            {
                var msg = context.Message;
                if (msg is Hello)
                {
                    Task.Delay(5000).Wait();
                    Console.WriteLine($"Hello {((Hello)msg).Who}");
                }
                return Actor.Done;
            }
        }
```

**Comment by cpx86** [comment]
Tried it locally and there does seem to be something off here. @rogeralsing - perhaps related to the handling of uncompleted tasks? Seems we maybe don't reschedule the mailbox properly. I can dig into it.

**Comment by rogeralsing** [comment]
Asp.NET is picky about where the tasks are scheduled too. `ConfigureAwait(false)` and all that.

**Comment by cpx86** [comment]
Can't get ASP.NET Core running using a locally built ProtoActor, but I tried running the same code in a normal app and it worked fine. So maybe it's something ASP.NET-specific?

**Comment by koderhari** [comment]
I have putted project on DropBox, It's visual studio 2015 project.
https://www.dropbox.com/s/adclkuhr974ilzb/WebApplication1.zip?dl=0

**Comment by koderhari** [comment]
I have uploaded project to DropBox
https://www.dropbox.com/s/adclkuhr974ilzb/WebApplication1.zip?dl=0
But i have found strange thing, if set Task.Delay to big value, and send more messages while thread waiting, all messages will be proccessed later, But if send new message after Delay, not working
it's like as something is checking messages for actor, if no more message, killing actor.

**Comment by rogeralsing** [comment]
@koderhari it is most likely some issue with the Mailbox busy/idle status flags in that case. we will investigate.

**Comment by cpx86** [comment]
Indeed it is - the ContinueWith handler does not set the mailbox back to Idle because it calls ProcessMessages. It should schedule a new mailbox run properly using RunAsync. Fix in progress.

**Comment by cpx86** [comment]
Fixed in https://github.com/AsynkronIT/protoactor-dotnet/commit/7036d9435a5571a69ba523b282f79bbf23d61893

**Comment by adamhathcock** [comment]
This actually solved a problem for me too today.  Thanks!

**Comment by cpx86** [comment]
Awesome!
