### ISSUE TITLE
PubSub - 3rd party integrations

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#875]
In the Akka world, there is Alpakka for reactive stream integrations with 3rd party tools.

Proto.Actor is more and more becoming a stream processing tool and the new PubSub feature makes even more so.
The question is, how would a proper integration look for e.g. Kafka?

Should it be able to handle subscriptions from Kafka onto actor subscribers, the same way actors can subscribe to Cluster PubSub?

Should Kafka topics be able to be subscribers to Cluster PubSub topics?

All very doable and likely easy to do, we just have to brainstorm a bit here

**Comment by marcinbudny** [comment]
This functionality go out of scope of pub-sub if #1713 is accepted

**Comment by marcinbudny** [comment]
Closing since #1713 has been merged
