### ISSUE TITLE
using protoactors as a managed actor system in process

### ISSUE THREAD

**Issue by stefan2410** [AsynkronIT/protoactor-dotnet#9]
Hello,
I  cloned and compiled your stack in VS2017 RC1 + Net.Core 1.1. Everything is running smoothly.
What I want to succeed is  to use it as  a simple but powerful managed actor system in-process, which will use actors internally and also  to communicate with other distributed  actor based systems. So to have an unified software design based on actor model (maybe partially, e.g.  services and actors when I need such behavior for specific entities ) .
As I have understood from your examples, I can use protoactors in process as C# objects and only if I need remoting (between different processes or other distributed systems), then  to create an instance of   the gam  server  and to use the Protoc.exe generator ( or in the future, the C# equivalent).
There are a lot of modules that you wanted help, I don't know if I am capable to help, as my mind is in the application design with the actor model, but if I find something as I will use it, I will try to help.
thanks

**Comment by rogeralsing** [comment]
Yes, you are correct, you can use the Proto.Actor lib for inprocess concurrency as an alternative to Tasks/Threads.

Currently only Google.Protobuf lib is the only supported serializer lib, we might possibly add support for Protobuf.NET also to make message design a bit easier.

There are a few things that could need some extra help right now, e.g. porting tests from Go to C#.
And also Routers needs to be ported over to C#.

**Comment by stefan2410** [comment]
I want to use it even in smaller systems,  not only  "for inprocess concurrency as an alternative to Tasks/Threads.". (btw, I had tried also to create actors with tpl-dataflow)
 The actor model imposes a different way of software design, more functional, more hierarchical, more distributed, message driven and it is better to design  behaviors,   in my opinion. 
I did run your code, all are good, I played a small ping-pong  between 2 actors. I like simplicity.
Last months, I have read a lot about Orleans , less about Akka.Net, but I did not have enough hands-on practice. I am trying  to understand all the components of your library (it looks somehow like Akka.Net). 
You wrote about Routers.  Is it what I have seen in the examples, that there is not a structure yet to store them and the system responsible to find the initialized actors by their Id   OR the type of message  ?
Where is the code to be ported ? or your ideas about ? I don't promise how fast or how good I can do it but I will try.  I will check and the tests.  But I am hard working daily also and my time is limited.

**Comment by rogeralsing** [comment]
>it looks somehow like Akka.Net

Yes, that is no surprise, I am the original creator of Akka.NET.
Proto.Actor is the result of the experience building Akka.NET for the last few years.
Removing all the nonsense that existed in Akka, only focusing on the core problems.

**Comment by rogeralsing** [comment]
Here are the Go based routers https://github.com/AsynkronIT/protoactor-go/tree/dev/routing
And there is the core infrastructure needed to make it work: https://github.com/AsynkronIT/protoactor-go/blob/dev/actor/router.go

I totally get that reading Go code might be a bit hard, but feel free to ask any questions on it and Ill try to help as quick as possible

**Comment by stefan2410** [comment]
I have installed the Go extension for VSCode 
https://marketplace.visualstudio.com/items?itemName=lukehoban.Go  
I will try and I will tell you about, my problem is the free time mainly.
