### ISSUE TITLE
Port EventStream subscriptions

### ISSUE THREAD

**Issue by cpx86** [AsynkronIT/protoactor-dotnet#90]
In Go you can replace the default subscriber for deadletter and supervision events.

See e.g.:
https://github.com/AsynkronIT/protoactor-go/blob/dev/actor/options.go
https://github.com/AsynkronIT/protoactor-go/blob/dev/actor/deadletter.go

**Comment by tomliversidge** [comment]
Go also has a predicate to allow filtering of messages? 

https://github.com/AsynkronIT/protoactor-go/blob/dev/eventstream/eventstream.go#L85

I've no experience of Go, but I'm presuming this is more than just filtering by type that we have in .net by using generics. i.e. a subscriber can subscribe to an event type and include a predicate to filter those types by?

**Comment by rogeralsing** [comment]
In Go, the WithPredicate simply wraps the subscriber func inside a predicate.
We can do the same with the .NET `Subscribe(Action<T> action)`

Closing as we have the bits we need here. we can re-open if further requirements arise
