### ISSUE TITLE
examples ClusterGrainHelloWorld not work

### ISSUE THREAD

**Issue by chenxyzl** [AsynkronIT/protoactor-dotnet#914]
## Actual Behavior
examples ClusterGrainHelloWorld node1 did not receive the message

## Steps to Reproduce the Problem

  1. modify http://consul:8500/ to http://127.0.0.1:8500/ and run consul
  2. run node2
  3. run node1

## Specifications

  - Version: 0.16 or master
  - Platform: windows
  - Subsystem: win10

**Comment by rogeralsing** [comment]
Found the cause. pushing fixes to the grain generator now

**Comment by rogeralsing** [comment]
Solved, available in release 0.17.0
