### ISSUE TITLE
Governance/maintenance of plugins/extensions

### ISSUE THREAD

**Issue by cpx86** [AsynkronIT/protoactor-dotnet#99]
There has been quite an influx lately of contributions (or ideas for) extending Proto.Actor in various ways. E.g. new persistence providers, scheduling/delaying of message sending, DI container integrations, logging, et cetera. I very much welcome these contributions, however, there's always a risk of bloating a library with non-essential features that complicate the code base or makes maintenance of it harder. On the other hand, these contributions are valuable enhancements to the library because they make life easier for users. Another thing is that the core library should now be very stable and between releases very little if anything should change in the API, whereas for example extensions for third-party integrations might require more frequent changes.

What I would like to discuss in this issue is how we can setup a governance/maintenance model for these extensions that achieves the following:
1. Protects the library from feature bloat.
2. An easy and contributor-friendly way of extending Proto.Actor with new functionality.
3. Allows for the core library and the extensions to move and evolve separately at their own pace.
4. Doesn't leave the maintainers with a slew of extensions that require support and maintenance.

I have two suggestions for how we could set this up, but please pitch in :)
1. Move everything except the core libraries (Actor, Mailbox, Cluster, Persistence, Remote and Router) into a separate repository, e.g. protoactor-dotnet-extensions, that is versioned and built separately.
2. Move each extension into a separate repo outside of the organization, so each of those extensions are maintained completely by their respective authors. The main repo would maintain a curated list of available extensions.
3. ???

**Comment by rogeralsing** [comment]
100% agree on this.
Let's keep the core API surface area as small as possible, but with a lot of extension points.

regarding the different ways to set things up, I believe that 1) would be the most successful _initially_.
This would show the community that we do have many plugins. to build traction around Proto.Actor.

That being said, in the long run, I do think that it would make sense to move more towards 2). 
When trust and momentum have already been established.

**Comment by tomliversidge** [comment]
Personally I'd prefer to see option 2 as I think it will help when writing integration tests for the persistence plugins. I couldn't find any tests around them so far, but imagine checking out an "extensions" repo and then having to install all databases supported to get integration tests to pass (I'm presuming not all have in-memory versions to test against). If they are separate, you only need the one you're interested in.

**Comment by raskolnikoov** [comment]
3. Move each extension into a separate repo INSIDE of the organization? :)

**Comment by adamhathcock** [comment]
My only current issue is that builds aren't quickly being done while the API and stuff is still churning a lot as it's early days.  This is why I'd prefer in the same repo for now.

I think having some "blessed" extensions in option 3 and some "extended" extensions for option 2 is good.

**Comment by tomliversidge** [comment]
Sorry just re-read the description of no. 2 and I thought it was what @raskolnikoov has proposed as 3. :)

So my vote would go for 3. (i.e. separate repos inside the organisation) and for me reading things more carefully

**Comment by tomliversidge** [comment]
How about something like

protoactor-dotnet - core libraries (Actor, Mailbox, Cluster, Persistence, Remote and Router)
protoactor-dotnet-contrib - includes things like strongly typed actors, patterns like process managers etc
protoactor-dotnet-couchdb 
protoactor-dotnet-mongodb
protoactor-dotnet-marten
protoactor-dotnet-ravendb
protoactor-dotnet-eventstore
...etc, all within AsynkronIT? Or create a ProtoActor organisation?

Should allow core library to develop and give an area (contrib) for people to add magic on top :)
Separate repo's per persistence providers would allow integration tests to be written without everyone having to install all supported databases - they would each get their own build pipelines, maintainers etc..

**Comment by adamhathcock** [comment]
I like @tomliversidge 's ideas around the repos.  Something to think about to how to manage code and updates and common files (e.g. gitignores) across repos.  It's not really a problem I've solved :)

**Comment by cpx86** [comment]
Yeah, I like that structure too :)

@adamhathcock For gitignore cp works just fine for me ;) For e.g. build scripts, we could use a Git submodule.

**Comment by raskolnikoov** [comment]
So who takes the first step :)

**Comment by jeffdoolittle** [comment]
I'm a fan of 1 for now moving toward 3 as the project matures. I think that will make it simpler for new contributors at this early stage.

**Comment by alexeyzimarev** [comment]
Ref #499
