### ISSUE TITLE
 ShutdownAsync(true) throw Exception when use RedisIdentityStorage 

### ISSUE THREAD

**Issue by chenxyzl** [AsynkronIT/protoactor-dotnet#990]
## Actual Behavior

throw RedisServerException

## Steps to Reproduce the Problem

  1. var redisIdentityStorage = new RedisIdentityStorage("mycluster", ConnectionMultiplexer.Connect("127.0.0.1:6379,password=Qwert123!"), maxConcurrency: 50);
  2.await system.Cluster().ShutdownAsync(true)

## Specifications

  - Version: 1.7.0
  - Platform: windows
  - Subsystem: win10

## StackTrace
<details>

```
StackExchange.Redis.RedisServerException:“ERR Error running script (call to f_d4c7abe0c5068cd7885b3f1c39dad867f897bd00): @user_script:5: @user_script: 5: Write commands not allowed after non deterministic commands. Call redis.replicate_commands() at the start of your script in order to switch to single commands replication mode. ”
![1621758677(1)](https://user-images.githubusercontent.com/11977514/119253548-5486f380-bbe4-11eb-87ef-c2cf602c0058.jpg)

```

</details>

**Comment by rogeralsing** [comment]
cc @mhelleborg

**Comment by mhelleborg** [comment]
@chenxyzl Could you provide a minimum reproducing program? This functionality is well tested in the ProtoActor test suite, and should work fine. What you have provided is not enough information to determine what might be wrong.

**Comment by chenxyzl** [comment]
https://github.com/chenxyzl/IW
the code is here
run consul 127.0.0.1:8500 and redis password Qwert123!
then run debug

**Comment by rogeralsing** [comment]
What version of Redis are you using?
And is it locally installed, or running in Docker?

Just so we know the details here

**Comment by chenxyzl** [comment]
redis: 3.2.0 on windows
running locally

**Comment by mhelleborg** [comment]
@chenxyzl Please test with a newer version of Redis, minimum version 5. Older versions are not tested or supported.

**Comment by chenxyzl** [comment]
redis 5.0 is ok. thanks
